<div id="content">
	<?php
		echo $this->liste;
	?>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#submit").click(function(event){
			event.preventDefault();
			var id_formations = new Array();
			
			$("input[type='checkbox']").each(function(){
				if($(this).attr("checked") == "checked")
					id_formations.push($(this).val());
			});
			
			$.ajax({
				type : "post",
				url : "facture/genererfacture",
				data : { "id_formations" : id_formations},
				success : function(){
					location.href = "facture/genererfacture";
				}
			});
		});
	});
</script>