<div id="content">
<?php  echo $this->navigation()->breadcrumbs()//fil d'ariane ou chemin de fer
?>
	<div class="indent-main">
		<h2>Profil</h2>
		<div class="col-1">
			<div class="container">
				<div id="titre_modifier">
					<h3>Modification des informations personnelles</h3>
				</div>
				<p id="info" style="color : green"></p>
			    <?php		
			        if($this->canEdit == true){
			            echo "<div id='modification_form'>".$this->form."</div>";
			        }   
			    ?>	
    		</div>
    	</div>
	</div>
</div>

<script type="text/javascript">

    $(document).ready(function(){    
    	$("dt").addClass('modification-left');
    	$("dd").addClass('modification-right');
    	$("#nom-label > label").attr('id', 'modifier_nom');
    	$("#prenom-label > label").attr('id', 'modifier_prenom');
    	$("#adresse-label > label").attr('id', 'modifier_adresse');
    	$("#adresse2-label > label").attr('id', 'modifier_adresse2');
    	$("#codePostal-label > label").attr('id', 'modifier_codePostal');
    	$("#ville-label > label").attr('id', 'modifier_ville');
        $("#telephone-label > label").attr('id', 'modifier_telephone');
        $("#mail-label > label").attr('id', 'modifier_mail');
            
        var okForSubmit = 0;
        
        $("#nom-element").append("<span class='errors' id='info_nom'>&nbsp;</span>"); 
        $("#prenom-element").append("<span class='errors' id='info_prenom'>&nbsp;</span>");
        $("#adresse-element").append("<span class='errors' id='info_adresse'>&nbsp;</span>");
        $("#codePostal-element").append("<span class='errors' id='info_codePostal'>&nbsp;</span>");
        $("#ville-element").append("<span class='errors' id='info_ville'>&nbsp;</span>");
        $("#telephone-element").append("<span class='errors' id='info_telephone'>&nbsp;</span>");
        $("#mail-element").append("<span class='errors' id='info_email'>&nbsp;</span>");
        $("#submit-element").append("<span class='errors' id='info_submit>&nbsp;</span>");
               
        $("#annuler").click(function(event){
        	event.preventDefault();
	        location.href = "/utilisateurs";
        });
                      
        // Lors que on veut submit
        $("#submit").click(function(event){
        	event.preventDefault();
            var regExp = new RegExp(/[0-9]{10}/);
                        
            if($("#telephone").val().length == 10){
                if(regExp.test($("#telephone").val())){
                    $('#info_telephone').html("");
                    var regExp2 = new RegExp(/^([a-zA-Z0-9]+(([\.\-\_]?[a-zA-Z0-9]+)+)?)\@(([a-zA-Z0-9]+[\.\-\_])+[a-zA-Z]{2,4})$/);
                    if($("#mail").val().length > 1){
                        
                        if(regExp2.test($("#mail").val())){
                            $("#info_email").html('');
                            if($('#nom').val().length > 0){
                                $("#info_nom").html('');
                                if($('#prenom').val().length > 0){
                                    $("#info_prenom").html('');
                                    if($('#adresse').val().length > 0){
                                        $("#info_adresse").html('');
                                        if($('#codePostal').val().length > 0){
                                            $("#info_codePosta").html('');
                                            if($('#ville').val().length > 0){
                                                sendData();
                                            }else{
                                                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                            }
                                        }else{
                                            $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                        }
                                    }else{
                                        $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                    }
                                }else{
                                     $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                }
                            }else{
                                 $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                            }
                        }else{
                            $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                        }
                    }else{
                         $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                    }
                }else{
                     $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                }
            }else{
                $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
            }               
        });
                
        
        // Fonction qui va envoyer les infos du formulaire
        function sendData(){
            $.ajax({
                url : 'modifierInfo',
                type : 'post',
                data : {'nom' : $("#nom").val(), 'prenom' : $("#prenom").val(), 'adresse' : $("#adresse").val(), 'adresse2' : $("#adresse2").val(), 'codePostal' : $("#codePostal").val(), 'ville' : $("#ville").val(), 'telephone' : $("#telephone").val(), 'mail' : $("#mail").val()},
                success : function(data){
                    $("#modification_form").html(data);
                    $("dt").addClass('modification-left');
			    	$("dd").addClass('modification-right');
			    	$("#info").html("La modification a été effectuée");	
                }
            });
        }        
                
            var cache = {};

            // Autocomplétion de la ville et du code postal

            $("#codePostal, #ville").autocomplete({
                source: function(request, response){

                    // Si la réponse est dans le cache
                	if (('FR' + '-' + request.term) in cache){
        				response($.map(cache['FR' + '-' + request.term], function (item){
        					return {
        						label: item.codePostal + ", " + item.ville,
        						value: function (){
        							if ($(this).attr('id') == 'codePostal'){
        								$('#ville').val(item.ville);
        								return item.codePostal;
        							}
        							else{
        								$('#codePostal').val(item.codePostal);
        								return item.ville;
        							}
        						}
        					}
        				}));
        			}

        			// Sinon -> Requete Ajax
                    else{
                        var objData = {};
                        if($(this.element).attr('id') == 'codePostal'){
                            objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                        }else{
                            objData = {ville : request.term, pays : 'FR', maxRows : 10};
                        }

                        $.ajax({
                           url : "/Autocomplete",
                           dataType : "json",
                           data : objData,
                           type : 'POST',
                           success : function(data){
                               // Ajout de reponse dans le cache
    						   cache[('FR' + '-' + request.term)] = data;
                               response($.map(data, function (item){
                                   return{
                                       label : item.code_postal + ", " + item.ville,
                                       value: function (){
    										if ($(this).attr('id') == 'codePostal'){
    											$('#ville').val(item.ville);
    											return item.code_postal;
    										}
    										else{
    											$('#codePostal').val(item.code_postal);
    											return item.ville;
    										}
    									}
                                   }
                               }));
                           }
                        });
                    }                
                }, 
                minLength: 3,
                delay: 600
            });
    });

</script>