<div id="content">
	<div id="indent-main">
		<h2>Changer de mot de passe </h2>
		<div id="container">
			<?php
			    echo $this->form;
			?>
		</div>
	</div>
</div>
<input type="hidden" id="password_changed" value="<?php echo $this->password_changed ?>">
<script type="text/javascript">
    $(document).ready(function(){
    
    	$("dt").addClass('changePassword-left');
    	$("dd").addClass('changePassword-right');
    	        
        $("#change_password").append("<p id='error' style='color: red;display : none;'></p>")
        $("#change_password").append("<p id='info' style='color: green;display : none;'></p>")
        
        $("#cancel").click(function(){
            location.href = "/utilisateurs";
            return false;
        });
        
        $("#submit").click(function(){
            
            $.ajax({
                type : 'post',
                url : 'testpassword',
                data : {'old' : $("#old").val()},
                success : function(data){
                    if(data != 'true'){
                        $("#error").html('Votre ancien mot de passe est incorrect !');
                        $("#error").show();
                        setTimeout(function() {
                            $("#error").fadeOut("slow");
                        }, 2000 );
                        return false;
                    }
                }
            });
            
            if($("#new").val().length < 6 || $("#new").val().length > 10){
                $("#error").html('La taille de votre mot de passe doit être comprise entre 6 et 10 caractères !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return false;
            }
            if($("#new").val() != $("#confirmation").val()){
                $("#error").html('Votre nouveau mot de passe et sa confirmation ne correspondent pas !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return false;
            }
            if($("#new").val() == $("#old").val()){
                $("#error").html('Votre nouveau mot de passe ne doit pas être le même que l\'ancien !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return false;
            }
            
            $("#change_password").submit();
                        
        });
        
        if($("#password_changed").val() == 'yes'){
            $("#info").html('Votre password a été changé !');
            $("#info").show();
            setTimeout(function() {
                $("#info").fadeOut("slow");
            }, 2000 );            
        }else if($("#password_changed").val() == 'no'){
        	$("#error").html('Une erreur c\'est produite');
            $("#error").show();
            setTimeout(function() {
                $("#error").fadeOut("slow");
            }, 2000 );      
        }
        
    });
</script>