<?php $this->user = new Zend_Session_Namespace('user');      ?>
<div id="content">		
    <div class="indent-main">
        <div class="container">
            <div class="col-1">
            	<?php echo "<h2>Bonjour ".utf8_encode($this->utilisateur)."</h2>";?>
                <div class="container">
					<?php
						// Les différentes étapes à remplir par le formateur pour être approuvé
					    echo $this->cv;
					    echo $this->motivation;
					    echo $this->photo;
					    echo $this->rib;
					    echo $this->lien_certification;
						echo $this->valide_document;
					    echo $this->valide;
					?>
                </div> 
                <div class="indent">
                <?php
                	echo $this->profil_inactif;
	                if($this->is_admin){
	                ?>
	                	<h3>Actions administrateur</h3>
				    	<div class="col-1">
				    		<div class="container">
							    <?php
							    if($this->voir_user){
									echo "<p><!--<img class='img-title' src='/images/forum-groupe-utilisateurs-icone-4597-48.png' />--><h5 style='display : inline;'>Actions sur les utilisateurs</h5></p>";
								?>
							    	<div class="container block-left">
									    <?php
											
											echo "<a href=".$this->url(array('controller' => 'utilisateurs', 'action' => 'listeutilisateurs'), 'default', true).">Liste des utilisateurs</a><br />";			
									        echo "<a href='utilisateurs/listeutilisateurs?id=2'>Liste des formateurs</a></div>";
										?>
									</div>
									<div class="container block-right">
										<?php
									        echo "<a href='utilisateurs/listeutilisateurs?id=1'>Liste des administrateurs</a><br />";
									        
									        echo "<a href='utilisateurs/formateuravalider'>Formateurs à valider</a>";
									    }
									    ?>
							    </div>
				    		</div>

				    	</div>
					    <div class="col-2 block-bottom" >
						    <div clas="container block-left">
						    	<h5>Autre actions</h5>
							    <?php
							    if($this->voir_groupe)    
							        echo "<p><a href=".$this->url(array('controller' => 'groupe', 'action' => 'index'), 'default', true).">Liste des groupes</a></p>";
							        
							    if($this->voir_certification)
							        echo "<a href=".$this->url(array('controller' => 'certifications', 'action' => 'index'), 'default', true).">Liste des certifications</a>";
							    ?>
							    	</div>
							    	<div class="container block-right">
							    <?php
							    if($this->voir_question)
							        echo "<p><a href=".$this->url(array('controller' => 'Questions', 'action' => 'index'), 'default', true).">Liste des questions</a></p>";
		
								if($this->voir_formation)
									echo "<a href=".$this->url(array('controller' => 'formation', 'action' => 'listeformation'), 'default', true).">Voir la liste des formation</a>";
								
				                ?>
				                	<div class="container block-left">
				               	<?php
				               	
				               	if($this->voir_liste_faq)
			               			echo "<p><a href=".$this->url(array('controller' => 'faq', 'action' => 'gestion'), 'default', true).">Gérer la FAQ</a></p>";
				               			
								if($this->voir_login_interdit)
									echo "<a href=".$this->url(array('controller' => 'logininterdit', 'action' => 'index'), 'default', true).">Voir la liste des logins interdit</a>";
				               	?>	
				                	</div>
                			</div>
                		<?php
				    		}
				    	?>
		               </div>
                </div>
            	<div class="indent">
            		<?php
            			// On affiche les options formateur que si l'utilisateur est formateur
            			 if($this->is_formateur){  
            		?>
                    <div class="container">
                    	<?php
                    		if($this->is_admin)
                    			echo "<h3>Actions formateur</h3>"
                    	?>
                        <div class="col-3">
                            <div class="container">
                            <img src="/images/certificat-icone-4129-48.png" class="img-left" />
                            <?php
                        		echo "<br /><a href=".$this->url(array('controller' => 'certifications', 'action' => 'listecertification'), 'default', true).">Passer une certification</a>";
                            ?>
                            </div>
                            <div class="container">
                            <img src="/images/evolution-calendrier-icone-6518-48.png" class="img-left" />
                            <?php
								if($this->creer_facture)
									echo "<br /><a href=".$this->url(array('controller' => 'formation', 'action' => 'viewformation'), 'default', true).">Mes formations planifiées</a>";	                                    
                            ?>
                            </div>
                        </div>
                        <div class="col-4">
                        	<div class="container">
                        	<?php
                        		if($this->voir_formation_dispo){
                        			echo '<img src="/images/livres-agenda-education-bibliotheque-icone-5155-48.png" class="img-left" />';
									echo "<br /><a href='formation/listeformation?sansFormateur=true'>Liste des formation disponibles</a>";
								}
							?>
                            </div>
                            <div class="container">
                               
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <?php  echo $this->placeholder('sidebar');?>
     	</div>
    </div>
</div>	

<script type="text/javascript">

	$(document).ready(function(){
		$("a").wTooltip();
	});

</script>