<div id="content" >
<p style="color : red"><i>Tous les champs marqué d'une * sont obligatoires</i></p>
<?php

$this->form->setAction($this->url());
echo $this->form;

?>
</div>
<script type="text/javascript">
    $(document).ready(function(){
         
        // Ajout des champs info
        
        $("#nom-element").append("<span class='errors' id='info_nom'>&nbsp;</span>"); 
        $("#prenom-element").append("<span class='errors' id='info_prenom'>&nbsp;</span>");
        $("#login-element").append("<span class='errors' id='info_login'>&nbsp;</span>");
        $("#password-element").append("<span class='errors' id='info_password'>&nbsp;</span>");
        $("#password_conf-element").append("<span class='errors' id='info_password_conf'>&nbsp;</span>");        
        $("#adresse-element").append("<span class='errors' id='info_adresse'>&nbsp;</span>");
        $("#codePostal-element").append("<span class='errors' id='info_codePostal'>&nbsp;</span>");
        $("#ville-element").append("<span class='errors' id='info_ville'>&nbsp;</span>");
        $("#telephone-element").append("<span class='errors' id='info_telephone'>&nbsp;</span>");
        $("#mail-element").append("<span class='errors' id='info_email'>&nbsp;</span>");
        $("#dateNaissance-element").append("<span class='errors' id='info_dateNaissance'>&nbsp;</span>");
        $("#departementNaissance-element").append("<span class='errors' id='info_departementNaissance'>&nbsp;</span>");
        $("#paysNaissance-element").append("<span class='errors' id='info_paysNaissance'>&nbsp;</span>");
        $("#submit-label").append("<span class='errors' id='info_submit>&nbsp;</span>");
         
        // Date picker sur le champ dateNaissance
        
        $("#dateNaissance").datepicker({changeYear : true, autoSize : true, dateFormat : 'dd-mm-yy', changeMonth : true, yearRange : '1930 : 2011'});
       
       var cache = {};
        
        // Autocomplétion de la ville et du code postal
        
        $("#codePostal, #ville").autocomplete({
            source: function(request, response){
                
                // Si la réponse est dans le cache
            	if (('FR' + '-' + request.term) in cache){
    				response($.map(cache['FR' + '-' + request.term], function (item){
    					return {
    						label: item.codePostal + ", " + item.ville,
    						value: function (){
    							if ($(this).attr('id') == 'codePostal'){
    								$('#ville').val(item.ville);
    								return item.codePostal;
    							}
    							else{
    								$('#codePostal').val(item.codePostal);
    								return item.ville;
    							}
    						}
    					}
    				}));
    			}
    			
    			// Sinon -> Requete Ajax
                else{
                    var objData = {};
                    if($(this.element).attr('id') == 'codePostal'){
                        objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                    }else{
                        objData = {ville : request.term, pays : 'FR', maxRows : 10};
                    }
                
                    $.ajax({
                       url : "/AutoComplete",
                       dataType : "json",
                       data : objData,
                       type : 'POST',
                       success : function(data){
                           // Ajout de reponse dans le cache
						   cache[('FR' + '-' + request.term)] = data;
                           response($.map(data, function (item){
                               return{
                                   label : item.code_postal + ", " + item.ville,
                                   value: function (){
										if ($(this).attr('id') == 'codePostal'){
											$('#ville').val(item.ville);
											return item.code_postal;
										}
										else{
											$('#codePostal').val(item.code_postal);
											$("#ville").attr("readonly", true);
											return item.ville;
										}
									}
                               }
                           }));
                       }
                    });
                }                
            }, 
            minLength: 3,
            delay: 600
        });
        
        // Variables pour la validation du submit, doit être à 12 pour valider le submit
        var okForSubmit = 0;
        
        // Vérification de okForSubmit et envoie du form si ok
        $("#inscription_form").submit(function(){
            if(okForSubmit >= 12)
                return true;
            else{
                $("#info_submit").html("Veuillez remplir tous les champs avant de valider votre inscription");
                return false;
            }
               
        });
        
        // Vérification de l'existance du login
        $("#login").blur(function(){
            if($("#login").val().length < 1){
                $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez remplir le nom d'utilisateur ! ");
            }else{
                $.ajax({
                   url: "/utilisateurs/testloginexist",
                   type: "post",
                   data: {'login' : $('#login').val()},
                   success: function(data){
                       if(data == 'true'){
                           $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Le nom d'utilisateur existe déjà !");
                       }else{   
                            $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                            okForSubmit ++;
                       }
                   }
                });
            }
        });
        
        // Vérification du champs téléphone
        $("#telephone").blur(function(){
            var regExp = new RegExp(/[0-9]{10}/);
            
            if($("#telephone").val().length === 10){
                if(regExp.test($("#telephone").val())){
                    $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                    okForSubmit ++;
                }else{
                    $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez rentrer un numéros de téléphone correct !");
                }
            }else{
                $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Le numéro de téléphone est trop court!");
            }
        });
        
        // Vérification de la validité et de la non-existance de l'adresse mail
        $("#mail").blur(function(){
            var regExp = new RegExp(/^([a-zA-Z0-9]+(([\.\-\_]?[a-zA-Z0-9]+)+)?)\@(([a-zA-Z0-9]+[\.\-\_])+[a-zA-Z]{2,4})$/);
            if($("#mail").val().length < 1)
                $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez remplir l'adresse email !");
            else if(regExp.test($("#mail").val())){
                $.ajax({
                   url: "/utilisateurs/testemailexist",
                   type: "post",
                   data: {'mail' : $("#mail").val()},
                   success : function(data){
                       if(data == "true")
                            $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;L'adresse email existe déjà !");
                        else{
                          $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                            okForSubmit ++;
                        }
                   } 
                });
            }else
                $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Le format de l'adresse email n'est pas correct !");
        });
        
        // Vérification de la longueur du password
        $("#password").blur(function(){
            if($("#password").val().length < 6 || $("#password").val().length > 10)
                 $("#info_password").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Votre mot de passe doit contenir entre 6 et 10 caractères !");
            else{
                $("#info_password").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }
        });
        
        $("#password_conf").blur(function(){
        	if($("#password").val() == $("#password_conf").val()){
        		$("#info_password_conf").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
        	}
			else
				$("#info_password_conf").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Votre mot de passe et sa confirmation doivent correspondre !");        		
        });
        
        // Vérification du format de la date
        $("#dateNaissance").blur(function(){
            if($('#dateNaissance').val().length > 0){
                var regExp = new RegExp(/^[0-9]{2}[-][0-9]{2}[-][0-9]{4}$/);
                if(regExp.test($("#dateNaissance").val())){
                    $("#info_dateNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                    okForSubmit ++;
                }
                else{
                    $("#info_dateNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez saisir votre date de naissance !");
                }
            }
        });
        
        // Vérification du remplissage de tout les champs
        
        $("#nom").blur(function(){
            if($('#nom').val().length > 0){
                $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre nom !");
        });
        
        $("#prenom").blur(function(){
            if($('#prenom').val().length > 0){
                $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre prenom !");
        });
        
        $("#adresse").blur(function(){
            if($('#adresse').val().length > 0){
                $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre adresse !");
        });
        
        $("#codePostal").blur(function(){
            if($('#codePostal').val().length > 0){
                $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre codePostal !");
        });
        
        $("#ville").blur(function(){
            if($('#ville').val().length > 0){
                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre ville !");
        });
            
        $("#departementNaissance").blur(function(){
            if($('#departementNaissance').val().length > 0 && $('#departementNaissance').val().length < 3){
                $("#info_departementNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_departementNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre departement de naissance !");
        });
        
        $("#paysNaissance").blur(function(){
            if($('#paysNaissance').val().length > 0){
                $("#info_paysNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_paysNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre pays de naissance !");
            if(okForSubmit >= 13){
                $("#info_submit").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");                
            }
        });
                
    });
    
    
</script>