<p><?php echo $this->navigation()->breadcrumbs()->setSeparator(' > '); ?></p>
<div id="titre_modifier">
	<h5>Modification des informations personnelles</h5>
</div>
<p id="info" style="color : green"></p>
<?php		
    if($this->canEdit == true){
        ?>
<div id="label-left">
	<label for="nom" >Nom :</label>
	<label for="prenom" >Prenom :</label>
	<label for="adresse" >Adresse :</label>
	<label for="adresse2" >Complement d'adresse :</label>
	<label for="codePostal" >Code postal :</label>
	<label for="ville" >ville :</label>
	<label for="telephone" >Téléphone :</label>
	<label for="mail" >Email :</label>
</div> <!-- label-left -->
<div id="input-right">
	<input type="text" name="nom" id="nom" value="<?php echo $this->nom ?>">
	<input type="text" name="prenom" id="prenom" value="<?php echo $this->prenom ?>">
	<input type="text" name="adresse" id="adresse" value="<?php echo $this->adresse ?>">
	<input type="text" name="adresse2" id="adresse2" value="<?php echo $this->adresse2 ?>">
	<input type="text" name="codePostal" id="codePostal" value="<?php echo $this->codePostal ?>">
	<input type="text" name="ville" id="ville" value="<?php echo $this->ville ?>">
	<input type="text" name="telephone" id="telephone" value="<?php echo $this->telephone ?>">
	<input type="text" name="mail" id="mail" value="<?php echo $this->mail ?>">
</div> <!-- input-right -->
<div id="span-right">
	<span class="errors_modifier" id="info_nom">&nbsp;</span>
	<span class="errors_modifier" id="info_prenom">&nbsp;</span>
	<span class="errors_modifier" id="info_adresse">&nbsp;</span>   
	<span class="errors_modifier" id="info_codePostal">&nbsp;</span>
	<span class="errors_modifier" id="info_ville">&nbsp;</span>
	<span class="errors_modifier" id="info_telephone">&nbsp;</span>
	<span class="errors_modifier" id="info_email">&nbsp;</span>
</div> <!-- span-right -->
<input type="submit" name="submit" id="submit_modifier" value="Valider"><input type="submit" name="annuler" onclick="javascript:history.back()" value="Annuler">	
        <?php
    }   
?>	
    		

<script type="text/javascript">

    $(document).ready(function(){    
    	            
        var okForSubmit = 0;
                       
        $("#annuler").click(function(event){
        	history.back();
        });
                      
        // Lors que on veut submit
        $("#submit_modifier").click(function(event){
        	event.preventDefault();
            var regExp = new RegExp(/[0-9]{10}/);
                        
            if($("#telephone").val().length == 10){
                if(regExp.test($("#telephone").val())){
                    $('#info_telephone').html("");
                    var regExp2 = new RegExp(/^([a-zA-Z0-9]+(([\.\-\_]?[a-zA-Z0-9]+)+)?)\@(([a-zA-Z0-9]+[\.\-\_])+[a-zA-Z]{2,4})$/);
                    if($("#mail").val().length > 1){
                        
                        if(regExp2.test($("#mail").val())){
                            $("#info_email").html('');
                            if($('#nom').val().length > 0){
                                $("#info_nom").html('');
                                if($('#prenom').val().length > 0){
                                    $("#info_prenom").html('');
                                    if($('#adresse').val().length > 0){
                                        $("#info_adresse").html('');
                                        if($('#codePostal').val().length > 0){
                                            $("#info_codePosta").html('');
                                            if($('#ville').val().length > 0){
                                                sendData();
                                            }else{
                                                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                            }
                                        }else{
                                            $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                        }
                                    }else{
                                        $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                    }
                                }else{
                                     $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                                }
                            }else{
                                 $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                            }
                        }else{
                            $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                        }
                    }else{
                         $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                    }
                }else{
                     $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
                }
            }else{
                $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='valide' />");
            }               
        });
                
        
        // Fonction qui va envoyer les infos du formulaire
        function sendData(){
            $.ajax({
                url : 'modifierInfo',
                type : 'post',
                data : {'nom' : $("#nom").val(), 'prenom' : $("#prenom").val(), 'adresse' : $("#adresse").val(), 'adresse2' : $("#adresse2").val(), 'codePostal' : $("#codePostal").val(), 'ville' : $("#ville").val(), 'telephone' : $("#telephone").val(), 'mail' : $("#mail").val()},
                success : function(data){
                    $("#modification_form").html(data);
                    $("dt").addClass('modification-left');
			    	$("dd").addClass('modification-right');
			    	$("#info").html("La modification a été effectuée");	
                }
            });
        }        
                
            var cache = {};

            // Autocomplétion de la ville et du code postal

            $("#codePostal, #ville").autocomplete({
                source: function(request, response){

                    // Si la réponse est dans le cache
                	if (('FR' + '-' + request.term) in cache){
        				response($.map(cache['FR' + '-' + request.term], function (item){
        					return {
        						label: item.codePostal + ", " + item.ville,
        						value: function (){
        							if ($(this).attr('id') == 'codePostal'){
        								$('#ville').val(item.ville);
        								return item.codePostal;
        							}
        							else{
        								$('#codePostal').val(item.codePostal);
        								return item.ville;
        							}
        						}
        					}
        				}));
        			}

        			// Sinon -> Requete Ajax
                    else{
                        var objData = {};
                        if($(this.element).attr('id') == 'codePostal'){
                            objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                        }else{
                            objData = {ville : request.term, pays : 'FR', maxRows : 10};
                        }

                        $.ajax({
                           url : "/Autocomplete",
                           dataType : "json",
                           data : objData,
                           type : 'POST',
                           success : function(data){
                               // Ajout de reponse dans le cache
    						   cache[('FR' + '-' + request.term)] = data;
                               response($.map(data, function (item){
                                   return{
                                       label : item.code_postal + ", " + item.ville,
                                       value: function (){
    										if ($(this).attr('id') == 'codePostal'){
    											$('#ville').val(item.ville);
    											return item.code_postal;
    										}
    										else{
    											$('#codePostal').val(item.code_postal);
    											return item.ville;
    										}
    									}
                                   }
                               }));
                           }
                        });
                    }                
                }, 
                minLength: 3,
                delay: 600
            });
    });

</script>