<p><?php echo $this->navigation()->breadcrumbs()->setSeparator(' > '); ?></p>
<div id="titre_modifier">
	<h5>Modification des informations personnelles</h5>
</div>
<p id="info" style="color : green"></p>
<?php		
    if($this->canEdit == true){
        ?>
<div id="label-left">
	<label for="nom" >Nom :</label>
	<label for="prenom" >Prénom :</label>
	<label for="adresse" >Adresse :</label>
	<label for="adresse2" >Complément d'adresse :</label>
	<label for="codePostal" >Code postal :</label>
	<label for="ville" >Ville :</label>
	<label for="telephone" >Téléphone :</label>
	<label for="mail" >Email :</label>
</div> <!-- label-left -->
<div id="input-right">
	<input type="text" name="nom" id="nom" value="<?php echo $this->nom ?>">
	<input type="text" name="prenom" id="prenom" value="<?php echo $this->prenom ?>">
	<input type="text" name="adresse" id="adresse" value="<?php echo $this->adresse ?>">
	<input type="text" name="adresse2" id="adresse2" value="<?php echo $this->adresse2 ?>">
	<input type="text" name="codePostal" id="codePostal" value="<?php echo $this->codePostal ?>">
	<input type="text" name="ville" id="ville" value="<?php echo $this->ville ?>">
	<input type="text" name="telephone" id="telephone" value="<?php echo $this->telephone ?>">
	<input type="text" name="mail" id="mail" value="<?php echo $this->mail ?>">
</div> <!-- input-right -->
<div id="span-right">
	<span class="errors_modifier" id="info_nom">&nbsp;</span>
	<span class="errors_modifier" id="info_prenom">&nbsp;</span>
	<span class="errors_modifier" id="info_adresse">&nbsp;</span>   
	<span class="errors_modifier" id="info_codePostal">&nbsp;</span>
	<span class="errors_modifier" id="info_ville">&nbsp;</span>
	<span class="errors_modifier" id="info_telephone">&nbsp;</span>
	<span class="errors_modifier" id="info_email">&nbsp;</span>
</div> <!-- span-right -->
<input type="submit" name="submit" class="submit" id="submit_modifier" value="Valider"><input class="submit" type="submit" name="annuler" onclick="javascript:history.back()" value="Annuler">	
<span id="info_submit" style="display : none; color : green"></span><span id="error_submit" style="display : none; color : red"></span>
        <?php
    }   
?>	
    		

<script type="text/javascript">

    $(document).ready(function(){    
    	
        // Variables pour la validation du submit            
        var nom_check = false;
        var prenom_check = false;
        var adresse_check = false;
        var code_postal_check = false;
        var telephone_check = false;
        //var mail_check = false;
        var array_check = [];

        $('#nom').blur(function(){
            nomCheck($('#nom').val()); 
        });

        $('#prenom').blur(function(){
            prenomCheck($('#prenom').val());
        })

        $('#adresse').blur(function(){
            adresseCheck($('#adresse').val());
        })

        $('#codePostal').blur(function(){
            codepostalCheck($('#codePostal').val());  
        })

        $('#telephone').blur(function(){
            telephoneCheck($('#telephone').val());  
        })
                   
        $("#submit_modifier").click(function(event){
            event.preventDefault();
            $('#submit_modifier').focus();

            if(array_check.length > 0)
               array_check = [];

            // On rapelle toutes les vérifications au cas ou
            telephone_check = telephoneCheck($('#telephone').val());
            //mailCheck($('#mail').val());
            nom_check = nomCheck($('#nom').val());
            prenom_check = prenomCheck($('#prenom').val());
            adresse_check = adresseCheck($('#adresse').val());
            code_postal_check = codepostalCheck($('#codePostal').val());

            array_check.push(nom_check);
            array_check.push(prenom_check);
            array_check.push(adresse_check);  
            array_check.push(code_postal_check);
            array_check.push(telephone_check);
            console.log(array_check);
          
            if(jQuery.inArray(false, array_check) == -1){
               sendData();
            }else{
              $("#error_submit").html("Veuillez remplir tous les champs requis avant de valider");
              $("#error_submit").show();
              setTimeout(function() {
                  $( "#error_submit" ).fadeOut("slow");
              }, 2000 );
            }
            return false;
        });
                       
        $("#annuler").click(function(event){
        	history.back();
        });  
        
        // Fonction qui va envoyer les infos du formulaire
        function sendData(){
            $.ajax({
                url : '/utilisateurs/modifierInfo',
                type : 'post',
                data : {'nom' : $("#nom").val(), 'prenom' : $("#prenom").val(), 'adresse' : $("#adresse").val(), 'adresse2' : $("#adresse2").val(), 'codePostal' : $("#codePostal").val(), 'ville' : $("#ville").val(), 'telephone' : $("#telephone").val(), 'mail' : $("#mail").val()},
                success : function(data){
                    $("#modification_form").html(data);
                    $("dt").addClass('modification-left');
			    	$("dd").addClass('modification-right');
			    	$("#info").html("La modification a été effectuée");	
                }
            });
        }        
                
            var cache = {};

            // Autocomplétion de la ville et du code postal

            $("#codePostal, #ville").autocomplete({
                source: function(request, response){

                    // Si la réponse est dans le cache
                	if (('FR' + '-' + request.term) in cache){
        				response($.map(cache['FR' + '-' + request.term], function (item){
        					return {
        						label: item.codePostal + ", " + item.ville,
        						value: function (){
        							if ($(this).attr('id') == 'codePostal'){
        								$('#ville').val(item.ville);
        								return item.codePostal;
        							}
        							else{
        								$('#codePostal').val(item.codePostal);
        								return item.ville;
        							}
        						}
        					}
        				}));
        			}

        			// Sinon -> Requete Ajax
                    else{
                        var objData = {};
                        if($(this.element).attr('id') == 'codePostal'){
                            objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                        }else{
                            objData = {ville : request.term, pays : 'FR', maxRows : 10};
                        }

                        $.ajax({
                           url : "/Autocomplete",
                           dataType : "json",
                           data : objData,
                           type : 'POST',
                           success : function(data){
                               // Ajout de reponse dans le cache
    						   cache[('FR' + '-' + request.term)] = data;
                               response($.map(data, function (item){
                                   return{
                                       label : item.code_postal + ", " + item.ville,
                                       value: function (){
    										if ($(this).attr('id') == 'codePostal'){
    											$('#ville').val(item.ville);
    											return item.code_postal;
    										}
    										else{
    											$('#codePostal').val(item.code_postal);
    											return item.ville;
    										}
    									}
                                   }
                               }));
                           }
                        });
                    }                
                }, 
                minLength: 3,
                delay: 600
            });
    });

</script>