
<h4 class="h5_modifie">Connexion</h4>
<form enctype="application/x-www-form-urlencoded" method="post" action="/Utilisateurs/connexion">
	<div id="label_login">
		<label for="login" class="required">Nom d'utilisateur :</label>
		<label for="password" class="required">Mot de passe :</label>
	</div> <!-- label_login -->
	<div id="input_login">
		<input type="text" name="login" id="login" value="" />
		<input type="password" name="password" id="password" value="" />
	</div> <!-- input_login -->
	<input type="submit" name="submit" id="submit_login" value="Connexion" />
</form>
