<h1>Connexion</h1>
<form enctype="application/x-www-form-urlencoded" method="post" action="/Utilisateurs/connexion">
	<div id="label_login">
		<label for="login" class="required">Nom d'utilisateur :</label>
		<label for="password" class="required">Mot de passe :</label>
	</div> <!-- label_login -->
	<div id="input_login">
		<input type="text" name="login" id="login" value="" />
		<input type="password" name="password" id="password" value="" />
	</div> <!-- input_login -->
	<input type="submit" class='submit' name="submit" id="submit_login" value="Connexion" />
<br /><br />	<a href="/mot-de-passe-oublie">J'ai oublié mon mot de passe</a>
</form>
<?php echo $this->placeholder('sidebar');?>
