<?php
	echo $this->placeholder('menu-connecte');
?>
<table id="tableau_formateur">
</table>
<div id="valid_dialog" style="display : none">
	<p>Etes vous sur de vouloir valider ce formateur ? </p>
	<span id="loading_valid"></span>	
</div> <!-- valid_dialog -->
<div id="entretien_dialog" style="display : none">
</div> <!-- entretien_dialog -->
<div id="refuser_dialog" style="display : none">
	<p>Etes vous sur de vouloir refuser ce formateur ? </p>
	<span id="loading_refus"></span>
</div> <!-- entretien_dialog -->
<script type="text/javascript">
	$(document).ready(function(){
		$("#tableau_formateur").flexigrid({
            url : '/utilisateurs/getformateuravalider',
            dataType: 'json',
            colModel : [
                    {display: 'Nom', name : 'nom', width : 100, sortable : true, align: 'left'},
                    {display: 'Prénom', name : 'prenom', width : 100, sortable : true, align: 'left'},
                    {display: 'Certification pédagogique', name : 'certification', width : 120, sortable : false, align: 'left'},
          			{display: 'CV', name : 'cv', width : 60, sortable : false, align: 'left'},
          			{display: 'Motivation', name : 'motivation', width : 80, sortable : false, align: 'left'},
          			{display: 'Casier', name : 'rib', width : 60, sortable : false, align: 'left'},
          			{display: 'Test de motivation passé', name : 'test_motivation', width : 150, sortable : false, align: 'left'},
          			{display: 'Entretien Skype passé', name : 'entretien_skype', width : 200, sortable : false, align: 'left'}, 
                      ],
            buttons : [
                    {name: 'Valider', bclass: 'valider', onpress : valid_record},
                    {separator: true},  
                    {name: 'Refuser', bclass: 'refuser', onpress : refuser_record},
                    {separator: true},
					{name: 'Voir les réponses du test', bclass: 'detail', onpress : detail_record},
					{separator: true},
                    {name: 'Voir les documents', bclass: 'document', onpress : document_record},
                    {separator: true},
					{name: 'Entretien Skype', bclass: 'entretien', onpress: entretien_formateur}
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom'},
                    {display: 'Prenom', name : 'prenom', isdefault: true}
                        ],
            sortname: "id_utilisateur",
            sortorder: "asc",
            usepager: true,
            title: "Liste des formateurs à valider",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 500,
            singleSelect: true
        });
        $(".ftitle").append('<span id="info" style="color : green"></span>');
        $(".ftitle").append('<span id="error" style="color : red"></span>');
        
        $("#submit_entretien").click(function(){
        	console.log('click');
        	        });
        
        function valid_record(command, grid){
        	// On vérifie que l'utilisateur a séléctionné une ligne     
        	var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }

        	// On vérifie que toutes les formalitées sont bien remplies
        	var cv;
        	var rib;
        	var lettre;
        	var test;
        	var id;
            $('.trSelected',grid).each(function(){
            	cv = $(this).children(':nth-child(3)').children().html();	
            	rib = $(this).children(':nth-child(4)').children().html();
            	lettre = $(this).children(':nth-child(5)').children().html();
                test = $(this).children(':nth-child(6)').children().html();
                id = this.id.substr(3);
            });
            
            if((cv || rib || lettre) == '<img class="icone_erreur" src="images/icone_erreur_16.png">' || test == '<img class="icone_erreur" src="images/icone_erreur_16.png">'){
            	$("#error").html('&nbsp;Ce formateur n\'a pas rempli toutes les formalitées');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            $('#valid_dialog').dialog({
            	title : "Valider un formateur",
            	buttons: [
            		{
            			text : "Valider",
            			click : function(){
            				$("#loading_valid").html("<img src='/images/loading.gif' /> En cours...");
            				$.ajax({
            					type : 'post',
            					url : '/utilisateurs/valideuserajax',
            					data : {'id_utilisateur' : id, 'valider_utilisateur' : true},
            					success : function(){
        	    					$('#valid_dialog').dialog('close');
		            				$('#tableau_formateur').flexReload();
		            				$("#info").html('&nbsp;Ce formateur a été validé');
					                $("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );
					                $("#loading_valid").html('');
					                return;
            					}
            				});           			
            			}
            		},
            		{
            			text : "Annuler",
            			click : function(){
            				$(this).dialog('close');
            			}
            		}
            	]
            });	
        }
        
        function detail_record(command, grid){
 			// On vérifie que l'utilisateur a séléctionné une ligne     
        	var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            // Si le formateur n'as pas encore passé le test

            var test;
            var id;
            $('.trSelected',grid).each(function(){
                test = $(this).children(':nth-child(7)').children().html();
				id = this.id.substr(3);
             });
            
            if(test == '<img class="icone_erreur" src="images/icone_erreur_16.png">'){
             	$("#error").html('&nbsp;Ce formateur n\'as pas encore passé le test');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;	
             }
             			
			location.href="/réponses-test-formateur?id="+id;
        }
        
        function entretien_formateur(command, grid){
        	// On vérifie que l'utilisateur a séléctionné une ligne     
        	var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            // On vide le dialog par sécurite
            $('#entretien_dialog').html('');
            
            var id;
            $('.trSelected',grid).each(function(){
				id = this.id.substr(3);
             });            
             
           	// On récupère les infos sur l'entretien
            $.ajax({
            	type: 'post',
            	url : '/utilisateurs/getentretiendata',
            	data :{'id' : id},
            	success : function(data){
            		$('#entretien_dialog').html(data);
            		$('#entretien_dialog').dialog({
            			title : 'Entretien de motivation Skype',
            			width: 680,
            			height: 470,
            			buttons : [
            				{
            					text : "Enregistrer les notes et marquer l'entretien comme terminé",
            					click : function(){
            						var temp_date = new Date();
									var mois = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"];
									date = temp_date.getDate()+"/"+mois[temp_date.getMonth()]+"/"+temp_date.getFullYear();
									
									// Si la date existe déjà, on ne la change pas.
									if($('#date_entretien').html() != "")
										date = $('#date_entretien').html();
									
									$.ajax({
										type : 'post',
										url : '/utilisateurs/edituser',
										data : {'id_utilisateur' : id, 'DateEntretienSkype' : date, 'Note' : $('#note_skype').val() }
									});
									$("#entretien_dialog").dialog('close');
									$('#tableau_formateur').flexReload();						
            					}
            				},
            				{
            					text : 'Fermer',
            					click : function(){
            						$(this).dialog('close');
									$('#tableau_formateur').flexReload();
            					}
            				}
            			]
            		});            		
            	}
            });
        }
        
        function refuser_record(command, grid){
            // On vérifie que l'utilisateur a séléctionné une ligne     
        	var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }

            var id;
            $('.trSelected',grid).each(function(){
				id = this.id.substr(3);
            });   
             
        	$('#refuser_dialog').dialog({
        		title : "Refuser un formateur",
        		buttons : [
        			{
        				text : 'Valider',
        				click : function(){
							$("#loading_refus").html("<img src='/images/loading.gif' /> En cours...");
        					$.ajax({
        						type : 'post',
        						url : '/utilisateurs/refuserformateur',
        						data : {'id_utilisateur' : id},
        						success : function(){
        							$('#refuser_dialog').dialog('close');
		            				$('#tableau_formateur').flexReload();
		            				$("#info").html('&nbsp;Ce formateur a été refusé');
					                $("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );
					                $("#loading_refus").html('');
					                return;
        						}
        					});
        				}
        			},
        			{
        				text : "Annuler",
        				click : function(){
        					$(this).dialog('close');
        				}
        			}
        		]
        	});
        }

        function document_record (command, grid) {
            // On vérifie que l'utilisateur a séléctionné une ligne     
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }

            var id;
            $('.trSelected',grid).each(function(){
                id = this.id.substr(3);
            });   

            location.href = "/utilisateurs/voirdocument?id="+id;
        }
	});
</script>