<?php $this->user = new Zend_Session_Namespace('user');  	        
echo $this->placeholder('menu-connecte');
echo $this->placeholder('sidebar');
    if($this->is_admin){
    ?>

 <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil administrateur !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

<div id="action_admin">
<!-- 	<h4>Actions administrateur</h4> -->
		<div id="action_utilisateur">
		    <?php
		    if($this->voir_user){
				echo "<p><img id='img_utilisateur' class='img-title' src='/images/forum-groupe-utilisateurs-icone-4597-48.png' /><h5 style='display : inline;margin-left : 3em'>Actions sur les utilisateurs</h5></p>";
			?>
		    	<div class="block-left block-top">
				    <?php
						
						echo "<a href='liste-des-utilisateurs'>Liste des utilisateurs</a><br />";			
				        echo "<a href='liste-des-utilisateurs?id=2'>Liste des formateurs</a>";
					?>
				</div>
				<div class="block-right block-top">
					<?php
				        echo "<a href='liste-des-utilisateurs?id=1'>Liste des administrateurs</a><br />";
				        
				        echo "<a href='formateurs-a-valider'>Formateurs à valider</a>";
				    }
				    ?>
		    </div>
	    </div> <!-- action_utilisateur -->
	    <div id="autre_action">
	    	<h5 id="toggle">Autres actions <img style="vertical-align : middle" src="/images/bullet-fleche-vers-le-bas-icone-5704-16.png" /></h5>
	    	<div class="block-left block-top hidden">
			    <?php
			    if($this->voir_groupe)    
			        echo "<a href=".$this->url(array('controller' => 'groupe', 'action' => 'index'), 'default', true).">Liste des groupes</a><br />";
			        
			    if($this->voir_certification)
			        echo "<a href=".$this->url(array('controller' => 'certifications', 'action' => 'index'), 'default', true).">Liste des certifications</a>";
			    ?>
		    </div>
		    <div class="block-top block-right block-bottom hidden">
			    <?php
			    if($this->voir_question)
			        echo "<a href=".$this->url(array('controller' => 'questions', 'action' => 'index'), 'default', true).">Liste des questions</a><br />";
	
				if($this->voir_formation)
					echo "<a href=".$this->url(array('controller' => 'formation', 'action' => 'listeformation'), 'default', true).">Voir la liste des formations</a>";
				
	            ?>
	        </div>
            <div class="block-left-bottom hidden">
	           	<?php
	           	
	           	if($this->voir_liste_faq)
	       			echo "<a href=".$this->url(array('controller' => 'faq', 'action' => 'gestion'), 'default', true).">Gérer la FAQ</a><br />";
	           			
				if($this->voir_login_interdit)
					echo "<a href=".$this->url(array('controller' => 'logininterdit', 'action' => 'index'), 'default', true).">Voir la liste des logins interdits</a><br />";
					echo "<a href='/factures'>Factures (".$this->nombre_facture.")</a>";
					echo "<input type='hidden' id='nombre_facture' value=".$this->nombre_facture." />";
	           	?>	
	       </div>
	       <div class="block-right-bottom hidden">
				<?php
					echo "<a href=".$this->url(array('controller' => 'questions', 'action' => 'listequestionmotivation'), 'default', true).">Liste des questions de motivation</a><br />";
				?>
				<?php
					echo "<a href=".$this->url(array('controller' => 'formation', 'action' => 'gererformation'), 'default', true).">Administrer les formations</a><br />";
					echo "<a href='/pages-dynamique'>Administrer les pages dynamiques</a><br />";
				?>	       
	       </div>
		</div> <!-- autre_action -->
	</div> <!-- action_admin -->

<script type="text/javascript">
	$(document).ready(function(){
		// On regarde si il y a des nouvelles factures
		if($('#nombre_facture').val() > 0){
       		$.blockUI({ 
            message: $('#growl'), 
            fadeIn: 700, 
            fadeOut: 700, 
            timeout: 4000, 
            showOverlay: false, 
            centerY: false, 
            css: { 
                width: '350px', 
                top: '10px', 
                left: '', 
                right: '10px', 
                border: 'none', 
                padding: '5px', 
                backgroundColor: 'black', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: 1, 
                color: 'white' 
            } 
        })
		}

		$('.hidden').hide();

		$('#toggle').click(function(){
			$('.hidden').toggle('blind', function(){
				if($('.hidden').is(':visible')){
					$('#toggle').attr('src', '/images/bullet-fleche-vers-le-haut-icone-8574-16.png');
				}else
					$('#toggle').attr('src', '/images/bullet-fleche-vers-le-bas-icone-5704-16.png');
			});
		})
	});
</script>

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil formateur !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

	<?php
		}
		// On affiche les options formateur que si l'utilisateur est formateur
		 if($this->is_formateur){  
			if($this->is_admin)
/*     			echo "<h3>Actions formateur</h3>" */
    	?>
    <div id="action_formateur">
        <div class="block-left-formateur block-top-formateur">
	        <?php
	    		echo "<br /><a href=certification-disponible><img src='/images/certificat-icone-4129-48.png' class='img-left' /> Passer une certification</a>";
	        ?>
        </div>
        <div class="block-top-formateur block-right-formateur">
    	<?php
    		if($this->voir_formation_dispo){
				echo "<br /><a href='formations-disponibles?sansFormateur=true'><img src='/images/livres-agenda-education-bibliotheque-icone-5155-48.png' class='img-left' /> Formations disponibles (".$this->nombre_formation.")</a>";
			}
		?>
        </div>
        <div class="block-left-bottom-formateur">
	        <?php
				if($this->creer_facture)
					echo "<br /><a href='mes-formations'><img src='/images/evolution-calendrier-icone-6518-48.png' class='img-left' /> Mes formations planifiées</a>";	                                    
	        ?>
        </div>
        <div class="block-right-bottom-formateur">
	        <?php
				if($this->creer_facture)
					echo "<br /><a href='/gerer-facture'><img src='/images/facture-icone-7188-48.png' class='img-left' /> Gérer mes facture</a>";	                                    
	        ?>
        </div>
    </div> <!-- action_formateur -->
    <div id="grow_formateur" style='display : none'>
    	<p>Veuillez penser à envoyer votre rib (<a href="/document">ici</a>), afin que nous puissions effectuer les virement pour solder les factures</p>
    </div>
    <input type="hidden" id="rib" value="<?php echo $this->rib?>" />
    <script type="text/javascript">
	$(document).ready(function(){
		// On regarde si il y a des nouvelles factures
		if($('#rib').val() == 'false'){
       		$.blockUI({ 
            message: $('#grow_formateur'), 
            fadeIn: 700, 
            fadeOut: 700, 
            timeout: 5000, 
            showOverlay: false, 
            centerY: false, 
            css: { 
                width: '350px', 
                top: '10px', 
                left: '', 
                right: '10px', 
                border: 'none', 
                padding: '5px', 
                backgroundColor: 'black', 
                '-webkit-border-radius': '10px', 
                '-moz-border-radius': '10px', 
                opacity: 1, 
                color: 'white' 
            } 
        })
		} 		
	});
</script>
    <?php 
    	}
	    if($this->is_client){ 
	?>

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil client !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

    <div id="action_client">
     	<div >
	        <?php
	    		echo "<br /><a href=/liste-des-formations><img src='/images/panier-acheter-ecommerce-shopping-icone-8314-48.png' class='img-left' /> Commander une formation</a>";
	        ?>
        </div>
        <div>
        	<?php
        		echo "<br /><a href=/formations-commandees>Voir mes formations</a>";
        	?>
        </div>
    </div> <!-- action_client -->
    <?php }
		 ?>
<div id="growl" style="display : none">
	<img src="/images/brown-nouveau-splash-icone-8189-32.png" style="float : left"/> <span id="message_growl">Des factures sont en attente de paiement !</span>
</div>
