<?php $this->user = new Zend_Session_Namespace('user');  	        
echo $this->placeholder('menu-connecte');
echo $this->placeholder('sidebar');
    if($this->is_admin){
    ?>

 <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil administrateur !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

<div id="action_admin">
<!-- 	<h4>Actions administrateur</h4> -->
		<div id="action_utilisateur">
		    <?php
		    if($this->voir_user){
				echo "<p><img id='img_utilisateur' class='img-title' src='/images/forum-groupe-utilisateurs-icone-4597-48.png' /><h5 style='display : inline;margin-left : 3em'>Actions sur les utilisateurs</h5></p>";
			?>
		    	<div class="block-left block-top">
				    <?php
						
						echo "<a href='liste-des-utilisateurs'>Liste des utilisateurs</a><br />";			
				        echo "<a href='liste-des-utilisateurs?id=2'>Liste des formateurs</a>";
					?>
				</div>
				<div class="block-right block-top">
					<?php
				        echo "<a href='liste-des-utilisateurs?id=1'>Liste des administrateurs</a><br />";
				        
				        echo "<a href='formateurs-a-valider'>Formateurs à valider</a>";
				    }
				    ?>
		    </div>
	    </div> <!-- action_utilisateur -->
	    <div id="autre_action" >
	    	<h5>Autre actions</h5>
	    	<div class="block-left block-top">
			    <?php
			    if($this->voir_groupe)    
			        echo "<a href=".$this->url(array('controller' => 'groupe', 'action' => 'index'), 'default', true).">Liste des groupes</a><br />";
			        
			    if($this->voir_certification)
			        echo "<a href=".$this->url(array('controller' => 'certifications', 'action' => 'index'), 'default', true).">Liste des certifications</a>";
			    ?>
		    </div>
		    <div class="block-top block-right block-bottom">
			    <?php
			    if($this->voir_question)
			        echo "<a href=".$this->url(array('controller' => 'questions', 'action' => 'index'), 'default', true).">Liste des questions</a><br />";
	
				if($this->voir_formation)
					echo "<a href=".$this->url(array('controller' => 'formation', 'action' => 'listeformation'), 'default', true).">Voir la liste des formations</a>";
				
	            ?>
	        </div>
            <div class="block-left-bottom ">
	           	<?php
	           	
	           	if($this->voir_liste_faq)
	       			echo "<a href=".$this->url(array('controller' => 'faq', 'action' => 'gestion'), 'default', true).">Gérer la FAQ</a><br />";
	           			
				if($this->voir_login_interdit)
					echo "<a href=".$this->url(array('controller' => 'logininterdit', 'action' => 'index'), 'default', true).">Voir la liste des logins interdits</a>";
	           	?>	
	       </div>
	       <div class="block-right-bottom">
				<?php
					echo "<a href=".$this->url(array('controller' => 'questions', 'action' => 'listequestionmotivation'), 'default', true).">Liste des questions de motivation</a><br />";
				?>
				<?php
					echo "<a href=".$this->url(array('controller' => 'formation', 'action' => 'gererformation'), 'default', true).">Administrer les formations</a><br />";
					echo "<a href='/pages-dynamique'>Administrer les pages dynamiques</a><br />";
				?>	       
	       </div>
		</div> <!-- autre_action -->
	</div> <!-- action_admin -->

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil formateur !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

	<?php
		}
		// On affiche les options formateur que si l'utilisateur est formateur
		 if($this->is_formateur){  
			if($this->is_admin)
/*     			echo "<h3>Actions formateur</h3>" */
    	?>
    <div id="action_formateur">
        <div class="block-left-formateur block-top-formateur">
	        <?php
	    		echo "<br /><a href=certification-disponible><img src='/images/certificat-icone-4129-48.png' class='img-left' /> Passer une certification</a>";
	        ?>
        </div>
        <div class="block-top-formateur block-right-formateur">
    	<?php
    		if($this->voir_formation_dispo){
				echo "<br /><a href='formations-disponible?sansFormateur=true'><img src='/images/livres-agenda-education-bibliotheque-icone-5155-48.png' class='img-left' /> Formations disponibles (".$this->nombre_formation.")</a>";
			}
		?>
        </div>
        <div class="block-left-bottom-formateur">
	        <?php
				if($this->creer_facture)
					echo "<br /><a href='mes-formations'><img src='/images/evolution-calendrier-icone-6518-48.png' class='img-left' /> Mes formations planifiées</a>";	                                    
	        ?>
        </div>
    </div> <!-- action_formateur -->
    <?php 
    	}
	    if($this->is_client){ 
	?>

<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Profil client !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->

    <div id="action_client">
     	<div >
	        <?php
	    		echo "<br /><a href=/liste-des-formations><img src='/images/panier-acheter-ecommerce-shopping-icone-8314-48.png' class='img-left' /> Commander une formation</a>";
	        ?>
        </div>
        <div>
        	<?php
        		echo "<br /><a href=/formations-commandees>Voir mes formations</a>";
        	?>
        </div>
    </div> <!-- action_client -->
    <?php }
		 ?>
