<div id="content">
	<h1>Formulaire d'inscription au poste de formateur</h1>
	<div class="indent-main">
		<div class="container">
			<div class="form-center">
				<p id="info_inscription"><i>Tous les champs marqué d'une * sont obligatoires</i></p>
				<form id="inscription_form" enctype="application/x-www-form-urlencoded" method="post" action="/utilisateurs/inscriptionformateur">
				<dl class="zend_form">
					<div id="form-content">
						<div id="inscription_civilite">
							<h4>Informations personelles</h4>
						</div>
						<dt id="inscription_type-label"><label for="inscription_type" class="optional"><span class="red">*</span> Civilité :</label></dt>
						<dd id="inscription_type-element">
							<select name="inscription_type" id="inscription_type">
							    <option value="M." label="Mr">M.</option>
							    <option value="Mme" label="Mme">Mme</option>
							</select></dd>
						<dt id="nom-label"><label for="nom" class="optional"><span class="red">*</span> Nom :</label></dt>
						<dd id="nom-element">
							<input type="text" name="nom" id="nom" value="" /></dd>
						<dt id="prenom-label"><label for="prenom" class="optional"><span class="red">*</span> Prenom :</label></dt>
						<dd id="prenom-element">
							<input type="text" name="prenom" id="prenom" value="" /></dd>
						<dt id="siret-label"><label for="siret" class="optional">Siret :</label></dt>
						<dd id="siret-element">
							<input type="text" name="siret" id="siret" value="" /></dd>
						<dt id="adresse-label"><label for="adresse" class="optional"><span class="red">*</span> Adresse :</label></dt>
						<dd id="adresse-element">
							<input type="text" name="adresse" id="adresse" value="" /></dd>
						<dt id="adresse2-label"><label for="adresse2" class="optional">Complément d'adresse :</label></dt>
						<dd id="adresse2-element">
							<input type="text" name="adresse2" id="adresse2" value="" /></dd>
						<dt id="codePostal-label"><label for="codePostal" class="optional"><span class="red">*</span> Code postal :</label></dt>
						<dd id="codePostal-element">
							<input type="text" name="codePostal" id="codePostal" value="" /></dd>
						<dt id="ville-label"><label for="ville" class="optional"><span class="red">*</span> Ville :</label></dt>
						<dd id="ville-element">
							<input type="text" name="ville" id="ville" value="" disabled="disabled"/></dd>
						<dt id="telephone-label"><label for="telephone" class="optional"><span class="red">*</span> Téléphone :</label></dt>
						<dd id="telephone-element">
							<input type="text" name="telephone" id="telephone" value="" /></dd>
						<dt id="dateNaissance-label"><label for="dateNaissance" class="optional"><span class="red">*</span> Date de naissance :</label></dt>
						<dd id="dateNaissance-element">
							<input type="text" name="dateNaissance" id="dateNaissance" value="" /></dd>
						<dt id="departementNaissance-label"><label for="departementNaissance" class="optional"><span class="red">*</span> Département de naissance :</label></dt>
						<dd id="departementNaissance-element">
							<input type="text" name="departementNaissance" id="departementNaissance" value="" /></dd>
						<dt id="paysNaissance-label"><label for="paysNaissance" class="optional"><span class="red">*</span> Pays de naissance :</label></dt>
						<dd id="paysNaissance-element">
							<input type="text" name="paysNaissance" id="paysNaissance" value="" /></dd>
	
						<div id="inscription_login">
							<h4>Informations de connexion</h4>
						</div>
						<dt id="login-label"><label for="login" class="optional"><span class="red">*</span> Nom d'utilisateur :</label></dt>
						<dd id="login-element">
							<input type="text" name="login" id="login" value="" /></dd>
						<dt id="password-label"><label for="password" class="optional"><span class="red">*</span> Mot de passe :</label></dt>
						<dd id="password-element">
							<input type="password" name="password" id="password" value="" /></dd>
						<dt id="password_conf-label"><label for="password_conf" class="optional"><span class="red">*</span> Confirmez le mot de passe :</label></dt>
						<dd id="password_conf-element">
							<input type="password" name="password_conf" id="password_conf" value="" /></dd>
						<dt id="mail-label"><label for="mail" class="optional"><span class="red">*</span> Adresse E-mail :</label></dt>
						<dd id="mail-element">
							<input type="text" name="mail" id="mail" value="" /></dd>
						<dt id="submit-label">&#160;</dt><dd id="submit-element">
							<input type="submit" name="submit" id="submit_inscription" value="Valider" /></dd>
						<dt id="csrf-label">&#160;</dt>
						<dd id="csrf-element">
							<input type="hidden" name="csrf" value="aba16d4f1bf0547303d91b4a02ceb80a" id="csrf" />
						</dd>
					</div>
				</dl>
				</form>	
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
                  
        // Ajout des champs pour le design
        $("dd").addClass("inscription-right"); 
        $("dt").addClass("inscription-left");
        $("#login-label > label").attr("id","inscription-login");
        $("#password-label > label").attr("id","inscription-password");
        $("#nom-label > label").attr('id', 'inscription_nom');
        $("#prenom-label > label").attr('id', 'inscription_prenom');
        $("#adresse-label > label").attr('id', 'inscription_adresse');
        $("#adresse2-label > label").attr('id', 'inscription_adresse2');
        $("#codePostal-label > label").attr('id', 'inscription_codePostal');
        $("#ville-label > label").attr('id', 'inscription_ville');
        $("#telephone-label > label").attr('id', 'inscription_telephone');
        $("#mail-label > label").attr('id', 'inscription_mail');
                 
        // Ajout des champs info
                
        $("#nom-element").append("<span class='errors_inscription' id='info_nom'>&nbsp;</span>"); 
        $("#prenom-element").append("<span class='errors_inscription' id='info_prenom'>&nbsp;</span>");
        $("#login-element").append("<span class='errors_inscription' id='info_login'>&nbsp;</span>");
        $("#password-element").append("<span class='errors_inscription' id='info_password'>&nbsp;</span>");
        $("#password_conf-element").append("<span class='errors_inscription' id='info_password_conf'>&nbsp;</span>");        
        $("#adresse-element").append("<span class='errors_inscription' id='info_adresse'>&nbsp;</span>");
        $("#codePostal-element").append("<span class='errors_inscription' id='info_codePostal'>&nbsp;</span>");
        $("#ville-element").append("<span class='errors_inscription' id='info_ville'>&nbsp;</span>");
        $("#telephone-element").append("<span class='errors_inscription' id='info_telephone'>&nbsp;</span>");
        $("#mail-element").append("<span class='errors_inscription' id='info_email'>&nbsp;</span>");
        $("#dateNaissance-element").append("<span class='errors_inscription' id='info_dateNaissance'>&nbsp;</span>");
        $("#departementNaissance-element").append("<span class='errors_inscription' id='info_departementNaissance'>&nbsp;</span>");
        $("#paysNaissance-element").append("<span class='errors_inscription' id='info_paysNaissance'>&nbsp;</span>");
        $("#submit-label").append("<span class='errors_inscription' id='info_submit>&nbsp;</span>");
        $("#inscription_type-label").append("<span class='errors_inscription' id='info_typet>&nbsp;</span>");
         
        // Date picker sur le champ dateNaissance
        
        $("#dateNaissance").datepicker({changeYear : true, autoSize : true, dateFormat : 'dd-mm-yy', changeMonth : true, yearRange : '1930 : 2011'});
       
       var cache = {};
        
        // Autocomplétion de la ville et du code postal
        
        $("#codePostal, #ville").autocomplete({
            source: function(request, response){
                
                // Si la réponse est dans le cache
            	if (('FR' + '-' + request.term) in cache){
    				response($.map(cache['FR' + '-' + request.term], function (item){
    					return {
    						label: item.codePostal + ", " + item.ville,
    						value: function (){
    							if ($(this).attr('id') == 'codePostal'){
    								$('#ville').val(item.ville);
    								$('#ville').attr('disabled', 'disabled');
    								return item.codePostal;
    							}
    							else{
    								$('#codePostal').val(item.codePostal);
							    	$('#codePostal').attr('disabled', 'disabled');
    								return item.ville;
    							}
    						}
    					}
    				}));
    			}
    			
    			// Sinon -> Requete Ajax
                else{
                    var objData = {};
                    if($(this.element).attr('id') == 'codePostal'){
                        objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                    }else{
                        objData = {ville : request.term, pays : 'FR', maxRows : 10};
                    }
                
                    $.ajax({
                       url : "/Autocomplete/index",
                       dataType : "json",
                       data : objData,
                       type : 'POST',
                       success : function(data){
                           // Ajout de reponse dans le cache
						   cache[('FR' + '-' + request.term)] = data;
                           response($.map(data, function (item){
                               return{
                                   label : item.code_postal + ", " + item.ville,
                                   value: function (){
										if ($(this).attr('id') == 'codePostal'){
											$('#ville').val(item.ville);
											$('#ville').attr('disabled', 'disabled');
											return item.code_postal;
										}
										else{
											$('#codePostal').val(item.code_postal);
											$('#codePostal').set('disabled', true);
											return item.ville;
										}
									}
                               }
                           }));
                       }
                    });
                }                
            }, 
            minLength: 3,
            delay: 600
        });
        
        // Variables pour la validation du submit, doit être à 12 pour valider le submit
        var okForSubmit = 0;
        
        // Vérification de okForSubmit et envoie du form si ok
        $("#inscription_form").submit(function(event){
            if(okForSubmit >= 11){
				$("#inscription_form").submit();
            }else{
                $("#info_submit").html("Veuillez remplir tous les champs avant de valider votre inscription");
            }
            return false;
        });
        
        // Vérification de l'existance du login
        $("#login").blur(function(){
            if($("#login").val().length < 1){
                $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez remplir le nom d'utilisateur ! ");
            }else{
                $.ajax({
                   url: "/utilisateurs/testloginexist",
                   type: "post",
                   data: {'login' : $('#login').val()},
                   success: function(data){
                       if(data == 'true'){
                           $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Le nom d'utilisateur existe déjà !");
                       }else{   
                            $("#info_login").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                            okForSubmit ++;
                       }
                   }
                });
            }
        });
        
        // Vérification du champs téléphone
        $("#telephone").blur(function(){
            var regExp = new RegExp(/[0-9]{10}/);
            
            if($("#telephone").val().length === 10){
                if(regExp.test($("#telephone").val())){
                    $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                    okForSubmit ++;
                }else{
                    $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez rentrer un numéros de téléphone correct !");
                }
            }else{
                $("#info_telephone").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Le numéro de téléphone est trop court!");
            }
        });
        
        // Vérification de la validité et de la non-existance de l'adresse mail
        $("#mail").blur(function(){
            var regExp = new RegExp(/^([a-zA-Z0-9]+(([\.\-\_]?[a-zA-Z0-9]+)+)?)\@(([a-zA-Z0-9]+[\.\-\_])+[a-zA-Z]{2,4})$/);
            if($("#mail").val().length < 1)
                $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez remplir l'adresse email !");
            else if(regExp.test($("#mail").val())){
                $.ajax({
                   url: "/utilisateurs/testemailexist",
                   type: "post",
                   data: {'mail' : $("#mail").val()},
                   success : function(data){
                       if(data == "true")
                            $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;L'adresse email existe déjà !");
                        else{
                          $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                            okForSubmit ++;
                        }
                   } 
                });
            }else
                $("#info_email").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Le format de l'adresse email n'est pas correct !");
        });
        
        // Vérification de la longueur du password
        $("#password").blur(function(){
        	var regExp = new RegExp(/(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/);
            if(!regExp.test($("#password").val()))
                 $("#info_password").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' style='font-size:5px' alt='erreur' />&nbsp;8 charactères, 1 majuscule, 1 chiffre minimum!");
            else{
                $("#info_password").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }
        });
        
        $("#password_conf").blur(function(){
        	if($("#password").val() == $("#password_conf").val()){
        		$("#info_password_conf").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
        	}
			else
				$("#info_password_conf").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; La confirmation ne correspond pas!");        		
        });
        
        // Vérification du format de la date
        $("#dateNaissance").blur(function(){
            if($('#dateNaissance').val().length > 0){
                var regExp = new RegExp(/^[0-9]{2}[-][0-9]{2}[-][0-9]{4}$/);
                if(regExp.test($("#dateNaissance").val())){
                    $("#info_dateNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                    okForSubmit ++;
                }
                else{
                    $("#info_dateNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp;Veuillez saisir votre date de naissance !");
                }
            }
        });
        
        // Vérification du remplissage de tout les champs
        
        $("#nom").blur(function(){
            if($('#nom').val().length > 0){
                $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_nom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre nom !");
        });
        
        $("#prenom").blur(function(){
            if($('#prenom').val().length > 0){
                $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_prenom").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre prenom !");
        });
        
        $("#adresse").blur(function(){
            if($('#adresse').val().length > 0){
                $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_adresse").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre adresse !");
        });
        
        $("#codePostal").blur(function(){
            if($('#codePostal').val().length > 0){
                $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_codePostal").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre codePostal !");
        });
        
        $("#ville").blur(function(){
            if($('#ville').val().length > 0){
                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre ville !");
        });
            
        $("#departementNaissance").blur(function(){
            var regExp = new RegExp(/[0-9]{2}/);
            if(!regExp.test($("#departementNaissance").val()) || $("#departementNaissance").val().length > 2){
            	$("#info_departementNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Votre département doit être de la forme suivante : 33 !");
            }else{
                $("#info_departementNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }
        });
        
        $("#paysNaissance").blur(function(){
            if($('#paysNaissance').val().length > 0){
                $("#info_paysNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");
                okForSubmit ++;
            }else
                $("#info_paysNaissance").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre pays de naissance !");
            if(okForSubmit >= 13){
                $("#info_submit").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />");                
            }
        });
                
    });
    
    
</script>