<?php echo $this->placeholder('menu-connecte') ?>
<table id="tableau_utilisateur">    
    
</table>
<div id="form" style="display : none;">
	<div id="label_edit_user">
		<label for="nom" class="optional">Nom :</label>
		<label for="prenom" class="optional">Prénom :</label>
<!-- 		<label for="login" class="optional">Nom d'utilisateur :</label> -->
		<label for="nom_groupe" class="optional">Groupe :</label>
		<label for="adresse" class="optional">Adresse :</label>
		<label for="adresse2edit" class="optional">Complément d'adresse :</label>
		<label for="code_postal" class="optional">Code postal :</label>
		<label for="ville" class="optional">Ville :</label>
		<label for="telephone" class="optional">Téléphone :</label>
		<label for="mail" class="optional">Email :</label>
		<label for="date_naissance" class="optional">Date de naissance :</label>
	</div> <!-- label_edit_user -->
	<div id="input_edit_user">
		<input type="text" name="nom" id="nom"  />
		<input type="text" name="prenom" id="prenom"  />
<!-- 		<input type="text" name="login" id="login"  /> -->
		<select name="nom_groupe" id="nom_groupe"></select>
		<input type="text" name="adresse" id="adresse"  />
		<input type="text" name="adresse2edit" id="adresse2edit"  />
		<input type="text" name="code_postal" id="code_postal"  />
		<input type="text" name="ville" id="ville"  />
		<input type="text" name="telephone" id="telephone"  />
		<input type="text" name="mail" id="mail"  />
		<input type="text" name="date_naissance" id="date_naissance"  />
	</div> <!-- input_edit_user -->
</div> <!-- form -->
<div id="add_form" style="display : none;">
    <div id="label_add_user">
        <label for="civilite_add">Civilité :</label>
        <label for="nom_add" class="optional">Nom :</label>
        <label for="prenom_add" class="optional">Prénom :</label>
        <label for="login_add" class="optional">Nom d'utilisateur :</label>
        <label for="mdp_add">Mot de passe :</label>
        <label for="nom_groupe_add" class="optional">Groupe :</label>
        <label for="adresse_add" class="optional">Adresse :</label>
        <label for="adresse2_add" class="optional">Complément d'adresse :</label>
        <label for="code_postal_add" class="optional">Code postal :</label>
        <label for="ville_add" class="optional">Ville :</label>
        <label for="telephone_add" class="optional">Téléphone :</label>
        <label for="mail_add" class="optional">Email :</label>
        <label for="date_naissance_add" class="optional">Date de naissance :</label>
        <label for="pays_naissance_add" class="optional">Pays de naissance :</label>
        <label for="departement_naissance_add">Département de naissance :</label>
    </div> <!-- label_add_user -->
    <div id="input_add_user">
        <select name="civilite" id="civilite_add">
                    <option value="mr">M.</option>
                    <option value="mlle">Mlle</option>
                    <option value="mme">Mme</option>
        </select>
        <input type="text" name="nom" id="nom_add"  />
        <input type="text" name="prenom" id="prenom_add"  />
        <input type="text" name="login" id="login_add"  />
        <input type="text" name="mdp" id="mdp_add" />
        <select name="nom_groupe" id="nom_groupe_add"></select>
        <input type="text" name="adresse" id="adresse_add"  />
        <input type="text" name="adresse2edit" id="adresse2_add"  />
        <input type="text" name="code_postal" id="code_postal_add"  />
        <input type="text" name="ville" id="ville_add"  />
        <input type="text" name="telephone" id="telephone_add"  />
        <input type="text" name="mail" id="mail_add"  />
        <input type="text" name="date_naissance" id="date_naissance_add"  />
        <input type="text" name="pays_naissance" id="pays_naissance_add" />
        <input type="text" name="departement_naissance" id="departement_naissance_add" />
    </div> <!-- input_add_user -->
</div> <!-- add_form -->
<input type="hidden" id="editer_info" value="<?php echo $this->editer_info?>" />
<input type="hidden" id="supprimer_utilisateur" value="<?php echo $this->supprimer_utilisateur ?>" />
<input type="hidden" id="groupe_demande" value="<?php echo $this->groupe_demande?>" />
<div id="delete_modal" style="display : none">
    <p>Etes vous sur de vouloir supprimer cet utilisateur ? </p>
</div>

<script type="text/javascript">

    $(document).ready(function(){
            
        // Datepicker sur la date de naissance
        $("#dateNaissance, #date_naissance_add").datepicker({
            changeYear : true, 
            autoSize : true,
            defaultDate: null,
            dateFormat : 'dd/mm/yy', 
            changeMonth : true, 
            yearRange : '-80 : -18',
            maxDate : -6570,
        });     
        
            // Autocomplétion de la ville et du code postal

         $("#code_postal,#ville").autocomplete({
            source: function(request, response){
                var objData = {};
                if($(this.element).attr('id') == 'codePostal'){
                    objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                }else{
                    objData = {ville : request.term, pays : 'FR', maxRows : 10};
                }
            
                $.ajax({
                   url : "/Autocomplete/index",
                   dataType : "json",
                   data : objData,
                   type : 'POST',
                   success : function(data){
                       // Ajout de reponse dans le cache
                       response($.map(data, function (item){
                           return{
                               label : item.code_postal + ", " + item.ville,
                               value: function (){
    								if ($(this).attr('id') == 'code_postal'){
    									$('#ville').val(item.ville);
    									return item.code_postal;
    								}
    								else{
    									$('#codePostal').val(item.code_postal);
    									return item.ville;
    								}
    							}
                           }
                       }));
                   }
                });                
            }, 
            minLength : 2,
            delay : 0
        });

        $("#code_postal_add, #ville_add").autocomplete({
            source: function(request, response){
                var objData = {};
                if($(this.element).attr('id') == 'codePostal'){
                    objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
                }else{
                    objData = {ville : request.term, pays : 'FR', maxRows : 10};
                }
            
                $.ajax({
                   url : "/autocomplete/index",
                   dataType : "json",
                   data : objData,
                   type : 'POST',
                   success : function(data){
                       response($.map(data, function (item){
                           return{
                               label : item.code_postal + ", " + item.ville,
                               value: function (){
                                    if ($(this).attr('id') == 'code_postal_add'){
                                        $('#ville_add').val(item.ville);
                                        return item.code_postal;
                                    }
                                    else{
                                        $('#code_postal_add').val(item.code_postal);
                                        return item.ville;
                                    }
                                }
                           }
                       }));
                   }
                });                
            }, 
            minLength : 2,
            delay : 0
        });
        
        // delete_record
        function delete_record(command,grid)
        {            
            // On vérifie si l'utilisateur à le droit
            if($("#supprimer_utilisateur").val() != 'true'){
                 $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#error").show();
                 setTimeout(function() {
                     $( "#error" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }         
             $("#delete_modal").dialog({
                title : "Supprimer",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $('.trSelected',grid).each(function(){
                                 var id = this.id.substr(3);
                                 $.ajax({
                                    type : 'post',
                                    url : '/utilisateurs/deleteuser',
                                    data : {'id_utilisateur' : id, 'delete' : $("#supprimer_utilisateur").val()},
                                    success : function(){
                                        $("#tableau_utilisateur").flexReload();
                                        $("#delete_modal").dialog('close');
                                        $("#info").html('&nbsp;L\'utilisateur à été supprimé');
                                        $("#info").show();
                                        setTimeout(function() {
                                            $( "#info" ).fadeOut("slow");
                                        }, 2000 );
                                    }
                                 });
                             });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
             });
             
         }
         
         // edit_record
         function edit_record(command,grid)
         {
             // On vérifie si l'utilisateur à le droit
             if($("#editer_info").val() != 'true'){
                $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
             var record_count = $('.trSelected',grid).length;
             if (0 == record_count)
             {
                 $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                 $("#error").show();
                 setTimeout(function() {
                     $("#error").fadeOut("slow");
                 }, 2000 );
                 return;
             }
             $('.trSelected',grid).each(function(){
                 var id = this.id.substr(3);
                 
                 // Séparation de l'adresse pour la modification et l'enregistrement
                 var adresse_complete = $('td[abbr="adresse"] > div',this).html();
                 var adresse1 = adresse_complete.split('-'); 
                 var adresse2 = adresse1[1].split('<br>');
                 var complement = adresse2[0].substring(1, adresse2[0].length);
                 var ville = adresse1[2].substring(1, adresse1[2].length);
                 var mail_temp = $('td[abbr="mail"] >div', this).html().split('>');
                 var mail = mail_temp[1].split('</a')

                 $("#nom").val($('td[abbr="nom"] >div', this).html());
                 $("#prenom").val($('td[abbr="prenom"] >div', this).html());
                 $("#adresse").val(adresse1[0]);
                 $("#adresse2edit").val(complement);
                 $("#code_postal").val(adresse2[1]);
                 $("#ville").val(ville);
                 $("#telephone").val($('td[abbr="telephone"] >div', this).html());
                 $("#mail").val(mail[0]);
                 $("#date_naissance").val($('td[abbr="date_naissance"] >div', this).html());
                 var groupe_name = $('td[abbr="groupe_name"] >div', this).html();
                
                 $.ajax({
                      type : 'post',
                      async : false,
                      url : '/groupe/getnomgroupe',
                      success : function(data){
                          $("#nom_groupe").html(data);
                      }
                 });
                    
                $('#nom_groupe > option').each(function(){
                    if($(this).html() == groupe_name)
                        $(this).attr('selected', 'selected');
                });
                
                 $("#form").dialog({
                     title : 'Editer',
                     width : 650,
                     buttons: [
                        {
                            text : "Valider",
                            click : function(){
                                $.ajax({
                                    type : 'post',
                                    url : '/utilisateurs/listeutilisateurs',
                                    data : {
                                        'id_utilisateur' : id,
                                        'nom' : $("#nom").val(),
                                        'prenom' : $("#prenom").val(),
                                        'adresse' : $("#adresse").val(),
                                        'adresse2' : $("#adresse2edit").val(),
                                        'code_postal' : $("#code_postal").val(),
                                        'ville' : $("#ville").val(),
                                        'telephone' : $("#telephone").val(),
                                        'mail' : $("#mail").val(),
                                        'date_naissance' : $("#date_naissance").val(),
                                        'id_groupe' : $("#nom_groupe").val(),
                                        'edit' : $("#editer_info").val()
                                    },
                                    success : function(){
                                        $("#tableau_utilisateur").flexReload();
                                        $("#form").dialog('close');
                                        $("#info").html('&nbsp;L\'utilisateur à été modifié');
                                        $("#info").show();
                                        setTimeout(function() {
                                            $( "#info" ).fadeOut("slow");
                                        }, 2000 );
                                    }
                                });
                            }
                        },
                        {
                            text : "Annuler",
                            click : function(){
                                $(this).dialog('close');
                            }
                        }
                    ]
                 });
             });
         }

        function add_record(command, grid){
             $.ajax({
                  type : 'post',
                  async : false,
                  url : '/groupe/getnomgroupe',
                  success : function(data){
                      $("#nom_groupe_add").html(data);
                  }
             });

            $('#add_form').dialog({
                title : 'Ajouter un utilisateur',
                width : 650,
                buttons : [
                    {
                        text : 'Ajouter',
                        click : function(){
                            // On envoie les donnés au controller
                            $.ajax({
                                type : 'post',
                                url : '/utilisateurs/adduser',
                                data : {
                                    'Type' : $('#civilite_add').val(),
                                    'Nom' : $("#nom_add").val(),
                                    'Prenom' : $("#prenom_add").val(),
                                    'Login' : $('#login_add').val(),
                                    'Password' : $('#mdp_add').val(),
                                    'Adresse' : $("#adresse_add").val(),
                                    'Adresse2' : $("#adresse2_add").val(),
                                    'CodePostal' : $("#code_postal_add").val(),
                                    'Ville' : $("#ville_add").val(),
                                    'Telephone' : $("#telephone_add").val(),
                                    'Mail' : $("#mail_add").val(),
                                    'DateNaissance' : $("#date_naissance").val(),
                                    'PaysNaissance' : $('#pays_naissance_add').val(),
                                    'DateNaissance' : $('#date_naissance_add').val(),
                                    'IdGroupe' : $("#nom_groupe_add").val(),
                                },
                                success : function(){
                                    $('#tableau_utilisateur').flexReload();
                                    $('#add_form').dialog('close'); 
                                    $("#info").html('&nbsp;L\'utilisateur à été ajouté');
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );    
                                }
                            })
                        }
                    },
                    {
                        text : 'Annuler',
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
         
        var nom_page = "";
        
        var temp = $("#groupe_demande").val();
        
        if(temp == 1)
        	nom_page = "Liste des administrateurs";
        else if(temp == 2)
        	nom_page = "Liste des formateurs";
        else
        	nom_page = "Liste des utilisateurs"
         
        $("#tableau_utilisateur").flexigrid({
            url : '/utilisateurs/getlisteutilisateurs?id_groupe='+$("#groupe_demande").val(),
            dataType: 'json',
            colModel : [
                    {display: 'Nom', name : 'nom', width : 100, sortable : true, align: 'left'},
                    {display: 'Prénom', name : 'prenom', width : 100, sortable : true, align: 'left'},
                    /* {display: 'Nom d\'utilisateur', name :'login', width : 100, sortable : true, align: 'left'}, */
                    {display: 'Groupe', name :'groupe_name', width : 100, sortable : true, align: 'left'},                    
                    {display: 'Adresse', name : 'adresse', width : 250, sortable : true, align: 'left'},
                    {display: 'Téléphone', name : 'telephone', width : 60, sortable : true, align: 'left'},
                    {display: 'Mail', name : 'mail', width : 170, sortable : true, align: 'left'},
                    {display: 'Date de naissance', name : 'date_naissance', width : 70, sortable : true, align: 'left'}
            ],
            buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},                    
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},                    
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
                   /*
 {separator: true},
                    {name: 'Detail', bclass: 'detail', onpress : detail_record}
*/
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom'},
                    {display: 'Prenom', name : 'prenom', isdefault: true},
                    {display: 'Nom d\'utilisateur', name : 'login'},
                    {display: 'Groupe', name :'groupe_name'},                                        
                    {display: 'Adresse', name : 'adresse', isdefault: true},
                    {display: 'Code postal', name : 'code_postal', isdefault: true},
                    {display: 'Ville', name : 'ville', isdefault: true},
                    {display: 'Téléphone', name : 'telephone', isdefault: true},
                    {display: 'Mail', name : 'mail', isdefault: true},
                    {display: 'Date de naissance', name : 'date_naissance', isdefault: true}
            ],
            sortname: "id_utilisateur",
            sortorder: "asc",
            usepager: true,
            title: nom_page,
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 500,
            singleSelect: true
        });
        $(".ftitle").append('<span id="info" style="color : green"></span>');
        $(".ftitle").append('<span id="error" style="color : red"></span>');
    });

</script>