<?php 
$user = new Zend_Session_Namespace('user');
$this->placeholder('menu-connecte')->captureStart();
if($user->id_groupe == 1){
?>
<div id="menu-connecte">
	    <li><a href="/profil-utilisateur">Accueil</a></li>
	    <li><a>Actions utilisateurs</a>
	        <ul>            
	            <li><a href="/liste-des-utilisateurs">Liste des utilisateurs</a></li>
	            <li><a href="/liste-des-utilisateurs?id=1">Liste des administrateurs</a></li>
	            <li><a href="/liste-des-utilisateurs?id=2">Liste des formateurs</a></li>
	            <li><a href="/formateurs-a-valider">Formateurs à valider</a></li>	            
	        </ul>
	    </li>
	    <li><a>Certifications</a>
	        <ul>
	            <li><a href="/liste-des-questions">Liste des questions</a></li>
	            <li><a href="/liste-des-certifications">Liste des certifications</a></li>
	            <li><a href="/liste-questions-motivation">Liste des questions de motivation</a></li>
	        </ul>
	    </li>
	    <li><a>Autres actions</a>
	        <ul>
				<li><a href="/liste-des-groupes">Liste des groupes</a></li>
	            <li><a href="/liste-des-formations">Liste des formations</a></li>
	            <li><a href="/liste-logins-interdits">Liste des logins interdits</a></li>
	            <li><a href="/gerer-faq">Gérer la FAQ</a></li>
	        </ul>
	    </li>
	    <li><a id="deconnexion_menu">Déconnexion</a></li>
</div> <!-- menu-connecte -->
<p><?php echo $this->navigation()->breadcrumbs()->setSeparator(' > '); ?></p>
<?php
}else{
?>
<div id="menu-connecte">
	    <li><a href="/profil-utilisateur">Profil</a></li>
	    <li><a href="/certification-disponible">Passer une certification</a></li>
	    <li><a href="/formations-disponible">Formations disponibles</a></li>
   	    <li><a href="/mes-formations">Mes formations</a>
	    <li><a id="deconnexion_menu">Déconnexion</a></li>
</div> <!-- menu-connecte -->
<p><?php echo $this->navigation()->breadcrumbs()->setSeparator(' > '); ?></p>
<?php 
}
?>
<script type="text/javascript">
	$(document).ready(function(){
	
		// functions pour le menu déroulants
		
		var timeout    = 500;
		var closetimer = 0;
		var ddmenuitem = 0;
		
		function MenuDeroulant_open(){
			MenuDeroulant_canceltimer();
			MenuDeroulant_close();
			ddmenuitem = $(this).find('ul').css('visibility', 'visible');
		}

		function MenuDeroulant_close(){
			if(ddmenuitem) ddmenuitem.css('visibility', 'hidden');
		}

		function MenuDeroulant_timer(){
			closetimer = window.setTimeout(MenuDeroulant_close, timeout);
		}

		function MenuDeroulant_canceltimer(){
			if(closetimer){
				window.clearTimeout(closetimer);
				closetimer = null;
			}
		}
		
		$('#menu-connecte > li').bind('mouseover', MenuDeroulant_open)
	
  		$('#menu-connecte > li').bind('mouseout',  MenuDeroulant_timer)});
  		
  		$('#deconnexion_menu').click(function(){
  			location.href = '/utilisateurs/deconnexion';
  		});
</script>

<?php $this->placeholder('menu-connecte')->captureEnd() ?>