<?php
	echo $this->placeholder('menu-connecte');
	echo $this->placeholder('sidebar');

	echo "<h1>Présentation du poste de formateur</h1>";

	echo $this->contenu;
?>
<div class="separateur" style="margin-left : 27em"></div>

<div id="div_refuser_presentation">
	<p>
		Cela ne me convient pas. Je suis conscient que mon inscription sera alors complètement annulée et que l'ensemble des données que possède Easylia à mon sujet sera détruit.
	</p>
	<input type="submit" class="submit" id="refuser" value="Je supprime mon dossier" />
</div>

<div id="div_accepter_presentation">
	<p>
		Cela me convient.
	</p>
	<input type="submit" class="submit" id="accepter" value="J'accepte" />
</div>

<div id="refuser_dialog" style="display : none">
	<p>
		Etes vous sur de vouloir refuser la convention ? <br />
		Toutes vos données seront supprimées, et vous devrez recommencer tout le processus si vous changer d'avis.
	</p>
</div>
<input type="hidden" id="id_utilisateur" value="<?php echo $this->id_utilisateur ?>" />
<input type="hidden" id="presentation_accepte" value="<?php echo $this->presentation_accepte ?>" />

<script type="text/javascript">
	$(document).ready(function(){
		// Lorsque on clique sur le bouton accepter
		$('#accepter').click(function(){
			// Envoie d'une requete ajax pour signifier l'acceptation
			$.ajax({
				type : 'post',
				url : '/utilisateurs/setpresentationaccepte',
				success : function(data){
					if(data == "true")
						location.href = "/profil-utilisateur";
				}
			});
		});

		// Lorsque on clique sur le bouton refuser
		$('#refuser').click(function(){
			$('#refuser_dialog').dialog({
				width : 500,
				title : 'Supprimer mon dossier',
				buttons : [
					{
						text : 'Valider',
						click : function(){
							$.ajax({
								type : 'post',
								url : '/utilisateurs/deleteuser',
								data : { 
									'delete' : true, 
									'id_utilisateur' : $('#id_utilisateur').val()
								},
								success : function(){
									location.href = "http://www.easylia.com";
								}
							})
						}
					},
					{
						text : 'Annuler',
						click : function(){
							$(this).dialog('close');
						}
					}
				]
			});
		});

		// Si la présentation a déjà été accepté on masque les boutons accepter et refuser
		if($('#presentation_accepte').val() == true){
			$('#div_accepter_presentation, #div_refuser_presentation').hide();
		}
	});
</script>