<?php 
$user = new Zend_Session_Namespace('user');
$this->placeholder('sidebar')->captureStart();
	if($user->id_groupe == 3)
		echo "<div id='sidebar_parcour'>";
	else if($user->id_groupe == 2)
		echo "<div id='sidebar_formateur'>";
	else if($user->id_groupe == 5)
		echo "<div id='sidebar_client'>";
	else if(!$user->is_logged)
		echo "<div id='sidebar_nonconnecte'>";
	else 
		echo '<div id="sidebar">';

	if($user->is_logged){
?>
	<h2>Espace privé</h2>
	<div id="isNotLogged">
		<form action="" id="form-espace-prive" class="form-espace-prive">
			<fieldset class="fieldset-espace-prive">
				<p>
					<label for="login" class="text">Utilisateur : </label>
					<input type="text" name="login" id="login" value="Votre nom d'utilisateur" onblur="if(this.value=='') this.value='Votre nom d\'utilisateur'" onfocus="if(this.value =='Votre nom d\'utilisateur' ) this.value=''">
				</p>
				<p>
					<label for="password" class="text">Mot de passe : </label>
					<input type="password" name="password" id="password" value="Votre mot de passe" onblur="if(this.value=='') this.value='Votre mot de passe'" onfocus="if(this.value =='Votre mot de passe' ) this.value=''">
				</p>
				<p>
					<input type="checkbox" id="remember">
					<label for="remember"> Se souvenir de moi</label>
					<br><a href="">Mot de passe oublié</a>
				</p>
				<p>
					
					<button class="button" onclick="return false;" id="submitLogin">Connexion</button>
				</p>
			</fieldset>
		</form>
	</div> <!-- isNotLogged -->		<?php 
		}
	?>
	<div id="navigation-content">
		<div id="isLogged" style="display : none;">
			<p id="userHello"><?php echo utf8_encode($user->prenom." ".$user->nom);?> [<a href="/deconnexion" id="deconnexion" >Déconnexion</a>]</p>
			<?php
			if($this->profil_inactif == ""){					
				?>
				<ul>
					<li><a href='/modification-informations-personnelles'>Voir mon profil</a></li>
					<li><a href='/changer-mot-de-passe'>Changer mon mot de passe</a></li>
					<?php
						if($user->id_groupe == 1 || $user->id_groupe == 2 || $user->id_groupe == 5)
							echo "<li><a href='/document'>Documents</a></li>";

						if($user->id_groupe == 2){
							echo "<li><a href='/presentation-detaillee'>Présentation détaillée </a></li>";
							echo "<li><a href='/convention-formateur'>Convention formateur </a></li>";
						}
					?>
				</ul>
			<?php
			}
			?>
		</div> <!-- isLogged -->
			<h2 class="crayon article-titre-8 titre">Recrutement des formateurs : faites-nous confiance</h2>
			<div class="crayon article-texte-8 texte"><p><span class="spip_document_9 spip_documents spip_documents_left" style="float:left; width:100px;">
	<img src="/images/81-fcfa9.png" width="100" height="112" alt="" style="height:112px;width:100px;"></span>Pour vous proposer les intervenants les plus compétents qui se déplaceront à votre domicile, Easylia sélectionne avec attention ses formateurs et applique un processus de recrutement strict. Découvrez <a href="http://www.easylia.com/Devenir-formateur">ici</a> notre méthode de sélection.</p></div>
		
			<h2 class="crayon article-titre-7 titre">Liens divers</h2>
			<div class="crayon article-texte-7 texte"><ul class="spip"><li><a href="foire-aux-questions" class="spip_ancre">Une question&nbsp;? Direction la FAQ&nbsp;!</a></li><li><a href="http://www.easylia.com/Avantages-fiscaux" class="spip_ancre">Tout savoir sur les avantages fiscaux liés aux services à la personne.</a></li></ul></div>
	</div> <!-- navigation-content -->
</div> <!-- sidebar -->

<?php $this->placeholder('sidebar')->captureEnd() ?>