<?php
	echo $this->placeholder('menu-connecte');
?>
<div class="container">
	<table id="tableau_faq"></table>
</div>
<input type="hidden" id="ajouter_faq" value="<?php echo $this->ajouter_faq ?>" />
<input type="hidden" id="modifier_faq" value="<?php echo $this->modifier_faq ?>" />
<input type="hidden" id="supprimer_faq" value="<?php echo $this->supprimer_faq ?>" />
<div id="add_dialog" style="display : none;" width="800px" height="270px">
	<p id="question_gestion"><label style="vertical-align : top" for="question">Question : </label><textarea id="question" nom="question"> </textarea></p>
	<p id="reponse_gestion"><label style="vertical-align : top" for="reponse">Reponse : </label><textarea id="reponse" nom="reponse"></textarea></p>
	<p id="categorie_gestion"><label for="categorie">Catégorie : </label><br /><br />
		<input type="checkbox" id="formateur" name="checkbox_categorie" class="checkbox_categorie" value="Formateur" /><label for="formateur">Formateur</label><br />
		<input type="checkbox" id="administrateur" name="checkbox_categorie" class="checkbox_categorie" value="Administrateur" /><label for="administrateur">Administrateur</label><br />
		<input type="checkbox" id="client" name="checkbox_categorie" class="checkbox_categorie" value="Client" /><label for="formateur">Client</label><br />
		<input type="checkbox" id="non-connecte" name="checkbox_categorie" class="checkbox_categorie" value="Non-connecté" /><label for="non-connecte">Non-connecté</label><br />
	</p>
	<p id="active_gestion"><label for="active">Active : </label><input type="checkbox" id="active" nom="active" /></p>
</div>
<div id="delete_dialog" style="display : none">
	<p>Etes vous sur de vouloir supprimer cette question de la FAQ ?</p>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#tableau_faq").flexigrid({
            url : '/faq/getlistequestion',
            dataType: 'json',
            colModel : [
                    {display: 'Question', name : 'question', width : 433, sortable : true, align: 'left'},
                    {display: 'Reponse', name : 'reponse', width : 433, sortable : true, align: 'left'},
                    {display: 'Active', name : 'active', width : 100, sortable : true, align: 'left'},
                    {display : 'Catégorie', name : 'categorie', width : 150, sortable : true, align : 'left'}
            ],
            buttons : [
            		{name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},            
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},                    
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
            ],
            searchitems : [
                    {display: 'Question', name : 'question', isDefault : true},
                    {display: 'Reponse', name : 'reponse'},
                    {display: 'Active', name : 'active'},
                    {display : 'Catégorie', name : 'categorie'}
            ],
            sortname: "question",
            sortorder: "asc",
            usepager: true,
            title: "Liste des questions/reponses de la FAQ",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 475,
            singleSelect: true
        });
        $(".ftitle").append('<span id="info" style="color : green"></span>');
        $(".ftitle").append('<span id="errors" style="color : red"></span>');
        
        function add_record(command, grid){
        	// On reinitialise les champs
			$("#question").val('');
			$("#reponse").val('');
			$("#categorie").val('');
			$("#active").removeAttr("checked");
        	
			// On vérifie si l'utilisateur à le droit
            if($("#ajouter_faq").val() != 'true'){
               $("#errors").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
               $("#errors").show();
               setTimeout(function() {
                   $("#errors").fadeOut("slow");
               }, 2000 );     
               return false;
            }
            
            // On vide les champs
            $('#question').val('');
            $('#reponse').val('');
            $(".checkbox_categorie[type=checkbox]").each(function(){
            	$(this).removeAttr('checked');
            });
            $("#active").removeAttr('checked');
            
            $("#add_dialog").dialog({
            	width : 815,
            	height : 480,
            	title : "Ajouter une question",
            	buttons : [
            		{	text : "Valider",
            			click : function(){
            			
            				var categorie = [];
            				$(".checkbox_categorie[type=checkbox]:checked").each(function(){
           						categorie.push($(this).val());
            				});
            				
            				$.ajax({
            				type : 'post',
            				url : 'add',
            				data : {'question' : $("#question").val(),'reponse' : $("#reponse").val(),'active' : $("#active").attr("checked"), 'categorie' : categorie},
             				success : function(){
             					$("#tableau_faq").flexReload();
             					$("#add_dialog").dialog('close');
             					$("#info").html('&nbsp;La question à été ajotuée !');
					                $("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );
             					}
            				});
            			}
            		},
            		{
            			text : "Annuler",
            			click : function(){
            				$(this).dialog('close');
            			}
            		}	
            	]
            });
        }
        
        function edit_record(command, grid){
        	// On vérifie si l'utilisateur à le droit
            if($("#modifier_faq").val() != 'true'){
               $("#errors").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
               $("#errors").show();
               setTimeout(function() {
                   $("#errors").fadeOut("slow");
               }, 2000 );     
               return false;
            }
             
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#errors").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#errors").show();
                setTimeout(function() {
                    $("#errors").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            //On vide les champs
            $('#question').val('');
            $('#reponse').val('');
            $(".checkbox_categorie[type=checkbox]").each(function(){
            	$(this).removeAttr('checked');
            });
            $("#active").removeAttr('checked');
            
            var id;
            $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
                 
                 var active;
                 if($('td[abbr="active"] >div', this).html() == "oui")
                 	active = true;
                 else
                 	active = false;
				
                 var categorie_temp = $('td[abbr="categorie"] >div', this).html();
                 var categorie = categorie_temp.split(',');
                 $(".checkbox_categorie[type=checkbox]").each(function(){
                 	var test = $.inArray($(this).val(), categorie)
                 	if(test != -1)
                 		$(this).attr('checked', true);
                 });
				
                 $("#question").val($('td[abbr="question"] >div', this).html());
                 $("#reponse").val($('td[abbr="reponse"] >div', this).html());                 
                 $("#active").attr("checked", active);
             });
             
             $("#add_dialog").dialog({
            	width : 815,
            	height : 480,
             	title : "Modifier une question",
             	buttons : [
             		{
             			text : "Valider",
             			click : function(){
            			
            				var categorie = [];
            				$(".checkbox_categorie[type=checkbox]:checked").each(function(){
           						categorie.push($(this).val());
            				});
            				
             				$.ajax({
             					type : "post",
             					url : "edit",
             					data : {"id" : id, "question" : $("#question").val(), "reponse" : $("#reponse").val(), "active" : $("#active").attr("checked"), 'categorie' : categorie},
             					success : function(){
             						$("#tableau_faq").flexReload();
             						$("#add_dialog").dialog('close');
             						$("#info").html('&nbsp;La question à été modifiée !');
					                $("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );
             					}
             				});
             			}
             		},
             		{
             			text : "Annuler",
             			click : function(){
             				$(this).dialog('close');
             			}
             		}
             	]
             });
        }

		function delete_record(command, grid){
			// On vérifie si l'utilisateur à le droit
            if($("#supprimer_faq").val() != 'true'){
               $("#errors").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
               $("#errors").show();
               setTimeout(function() {
                   $("#errors").fadeOut("slow");
               }, 2000 );     
               return false;
            }
             
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#errors").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#errors").show();
                setTimeout(function() {
                    $("#errors").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            var id;
            
            $(".trSelected", grid).each(function(){
            	id = this.id.substr(3);
            });
            
            $("#delete_dialog").dialog({
            	title : "Supprimer une question",
            	buttons : [
            		{
            			text : "Valider",
            			click : function(){
            				$.ajax({
            					type : 'post',
            					url : 'delete',
            					data : {'id' : id},
            					success : function(){
            						$("#tableau_faq").flexReload();
            						$("#delete_dialog").dialog('close');
            						$("#info").html('&nbsp;La question à été supprimée !');
					                $("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );
            					}
            				});	
            			}
            		},
            		{
            			text : "Annuler",
            			click : function(){
            				$(this).dialog('close');
            			}
            		}
            	]
            });
		}
	});
</script>