
<h1>Foire aux questions</h1>

<h5 class="h5_modifie">Liste des questions</h5>
<?php
echo $this->faq;
?>
<script type="text/javascript">
	$(document).ready(function(){
		
		// Gestion des effets de la FAQ
		
		// On cache toutes les réponses
		$(".reponse-faq").hide();
		
		// Lorsque on clique sur une question
		$(".question-faq").click(function(){
			// On cache la réponses déjà affichée
			$(".reponse-faq").slideUp();
			
			if($(this).next().is(":visible") == false)
				// On affiche la réponse associée
				$(this).next().slideDown();
		});
		
	});
</script>