<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="#LANG" lang="#LANG" dir="#LANG_DIR">
	<head> 
    <title>Easylia</title>          
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
          <meta http-equiv="Content-Style-Type" content="text/css" />
          <link href="css/style.css" rel="stylesheet" type="text/css" />
          <link href="css/layout_index.css" rel="stylesheet" type="text/css" />
          <script src="js/jquery.1.6.2.min.js" type="text/javascript"></script>
          <script type="text/javascript" src="js/jquery.slideshow.js"></script>  
          <script type="text/javascript" src="js/script.js"></script>     
      </head>

	<body class="page_sommaire">
		<div id="page">
			<div class="right_bgd"></div>
				<div id="header">
					<div id="onglets">
						<ul>
	                    	<li><a href="http://dev.easylia.com" class="current">Accueil</a></li>
	                        <li><a href="/utilisateurs">Profil</a></li>
		                </ul>	   
					</div> <!-- onglets -->
					<div id="header_content">
						<div id="logo">
							<a href="http://dev.easylia.com"><img alt="" src="<?php APPLICATION_PATH?>/images/logo.jpg" class="logo" /></a><br />
						</div> <!-- logo -->
						<div id="search">
							<h2>0810 123 456</h2>
							<form action="" id="form1">
								<p>
									<input type="text" class="input" value="Rechercher…" onblur="if(this.value=='') this.value='Rechercher…'" onfocus="if(this.value =='Rechercher…' ) this.value=''"  />
									<a href="#" onclick="document.getElementById('form1').submit()"><img alt="" src="images/button.gif" /></a>
								</p>
							</form>
						</div> <!-- search -->
					</div> <!-- header_content -->
				</div> <!-- header -->
				<div id="content">
					<div id="content-main">
						<!--
<div class="playPauseExample slideShow">
	  						<ul class="slides">
	  								<li class="slide"><img src="<?php APPLICATION_PATH?>/images/img1.jpg" alt="" width="691" height="288"/></li>
	  								<li class="slide"><img src="<?php APPLICATION_PATH?>/images/img2.jpg" alt="" width="691" height="288"/></li>
	  								<li class="slide"><img src="<?php APPLICATION_PATH?>/images/img3.jpg" alt="" width="691" height="288"/></li>
	  								<li class="slide"><img src="<?php APPLICATION_PATH?>/images/img4.jpg" alt="" width="691" height="288"/></li>
	  								<li class="slide"><img src="<?php APPLICATION_PATH?>/images/img5.jpg" alt="" width="691" height="288"/></li>
	  						</ul>
	  						<a href="#" class="togglePlayback"><img src="<?php APPLICATION_PATH?>/images/stop.png" alt="" /></a>
	  					</div>
-->
					</div> <!-- content-main> -->
                        <div id="navigation">
							<h2>Espace privé</h2>
							<form action="" id="form-espace-prive" class="form-espace-prive">
								<fieldset class="fieldset-espace-prive">
									<p>
										<label for="login" class="text">Utilisateur : </label>
										<input type="text" name="login" id="login" value="Votre nom d'utilisateur" onblur="if(this.value=='') this.value='Votre nom d\'utilisateur'" onfocus="if(this.value =='Votre nom d\'utilisateur' ) this.value=''" />
									</p>
									<p>
										<label for="password" class="text">Mot de passe : </label>
										<input type="password" name="password" id="password" value="Votre mot de passe" onblur="if(this.value=='') this.value='Votre mot de passe'" onfocus="if(this.value =='Votre mot de passe' ) this.value=''" />
									</p>
									<p>
										<input type="checkbox" id="remember" />
										<label for="remember"> Se souvenir de moi</label>
										<br /><a href="">Mot de passe oublié</a>
									</p>
									<p>
										
										<button class="button" onclick="return false;" id="submitLogin">Connexion</button>
									</p>
								</fieldset>
							</form>
		                    <div id="navigation-content">
		                    </div>
						</div>
						<div style="clear: both;"> </div>
				</div> <!-- content -->
			</div>	<!-- right_bgd -->
			<div id="footer">
				<div id="footer_content">
					<div id="footer_content_left">
						<p><span class="h3" style="margin-rigth: 0.5em;">Easylia</span> &copy; 2012</p>
					</div>
					<div id="footer_content_right">
						<h1 style="margin-bottom: 0;">0810 123 456</h1>
						<p>Prix d'un appel local</p>
					</div> <!-- footer_content_right -->
				</div> <!-- footer-content -->
			</div> <!-- footer -->
		</div><!--Fin Page -->
	</body>		
</html>	

			                <!--
      <div id="notLogged">
	                        	<h2 >Connexion utilisateur</h2>
	                            <form action="" id="form2"><div class=" container">
	                               	<div class="h3 txt"><input id="login" type="text" class="input2" />Nom d'utilisateur:</div>
	                                <div class="h3 txt"><input id="password" type="password" class="input2" />Mot de passe:</div>
		                           	<p class="txt"><button class="fright button" onClick="return false;" id="submitLogin">Valider</button> <input type="checkbox" id="remember" class="input3" /> &nbsp;Se souvenir de moi</p>
	                               	<br /><a href="#" class="link1 txt" >Vous avez oublié votre mot de passe ?</a><br />
		                           	<a class="link1 txt" href="<?php echo $this->url(array('controller' => 'utilisateurs', 'action' =>'inscriptionClient'), 'default', true)?>">Créer un compte</a>
	                              </form>
	                              <p id="erreur" style="color : red;"></p>
	                          </div>
	                          </div>
	                          <div id="isLogged" style="display : none;">
	                              <p id="userHello">Bonjour <?php echo $user->login;?> !</p>
	                              <a href="#" id="votreCompte"  onClick='return false;'>Votre compte</a> / <a href="#"  id="deconnexion" onClick="return false;">Deconnexion</a>
	                          </div>
	                  </div>
-->
<script type="text/javascript">

    $(document).ready(function(){

         var isLogged = false;
         <?php
            // le namespace est setté en haut de la page
            if(!empty($user->is_logged) && $user->is_logged == true) {?> 
             isLogged = true;
         <?php } ?>
        
       //Récupération des infos et envoie à l'action login du controller utilisateurs.
       $("#submitLogin").click(function(){
           $.ajax({
              type: 'post',
              url: '/utilisateurs/connexionFromIndex',
              data: {'login' : $("#login").val(), 'password' : $("#password").val(), 'loginFromIndex' : true},
              success : function(data){
                   if(data != ''){
                      /*
$("#userHello").html('Bonjour '+ data + " !");
                       $("#notLogged").hide();
                       $("#isLogged").show();
*/
                       location.href = "/utilisateurs";
                    }else{
                        $("#erreur").html("Votre nom d'utilisateur ou votre mot de passe ne correspond pas !");
                        $("#erreur").show();
                        setTimeout(function() {
                            $( "#erreur" ).fadeOut("slow");
                        }, 2000 );
                    }                
              }
           });
       });
       
       $("#deconnexion").click(function(){
           $.ajax({
               type: 'post',
               url: '/utilisateurs/deconnexion',
               success: function(){
                    $("#notLogged").show('slow');
                    $("#isLogged").hide('slow');
               }
           }); 
       });
       
       $("#votreCompte").click(function(){
            window.location.replace("/utilisateurs");
       });
                  
       if( isLogged === true){
            $("#notLogged").hide();
            $("#isLogged").show();
       }else{
           $("#notLogged").show();
           $("#isLogged").hide();
       }
    });


</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23892247-1']);
  _gaq.push(['_setDomainName', '.easylia.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

        </html>
        
        
