<?php
	echo $this->placeholder('menu-connecte');
?>
<div class="container">
	<table id="tableau_login"></table>
</div>
<div id="delete_dialog" style="display : none">
	<p>Etes vous sur de vouloir supprimer ce nom d'utilisateur de la liste des interdits ? </p>
</div>
<div id="add_dialog" style="display : none">
	Nom d'utilisateur : <input type="text" id="login_interdit" />
</div>
<input type="hidden" id="ajouter_login" value="<?php echo $this->ajouter_login?>" />
<input type="hidden" id="modifier_login" value="<?php echo $this->modifier_login?>" />
<input type="hidden" id="supprimer_login" value="<?php echo $this->supprimer_login?>" />

<script type="text/javascript">
	$(document).ready(function(){
		$("#tableau_login").flexigrid({
            url : 'logininterdit/getlistelogin',
            dataType: 'json',
            colModel : [
                    {display: 'Nom d\'utilisateur', name : 'login', width : 100, sortable : true, align: 'left'},
            ],
            buttons : [
            		{name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},            
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},                    
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
            ],
            searchitems : [
                    {display: 'Nom d\'utilisateur', name : 'login', isDefault : true},
            ],
            sortname: "login",
            sortorder: "asc",
            usepager: true,
            title: "Liste des nom d'utilisateur interdits",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 475,
            singleSelect: true
        });
        
        function add_record(command, grid){
        	// On vide le champs
        	$('#login_interdit').val('');
        
        	 // On vérifie si l'utilisateur à le droit
             if($("#ajouter_login").val() != 'true'){
                $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
	         $("#add_dialog").dialog({
	        	title : 'Ajouter un nom d\'utilisateur', 
	        	buttons : [
	        		{
	        			text : 'Valider',
	        			click : function(){
	        				$.ajax({
	        					type : 'post',
	        					url : '/logininterdit/add',
	        					data : {'login' : $("#login_interdit").val()},
	        					success : function(){
	        						$("#info").html('&nbsp;Le nom d\'utilisateur à été ajouté !');
					            	$("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );     
					                $("#add_dialog").dialog('close');
					                $("#tableau_login").flexReload();
							  }
	        				});
	        			}
	        		},
	        		{
	        			text : 'Annuler',
	        			click : function(){
	        				$(this).dialog('close');
	        			}
	        		}
	        	]
	        });
		
		}
        
        function edit_record(command, grid){
             // On vérifie si l'utilisateur à le droit
             if($("#modifier_login").val() != 'true'){
                $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
             var record_count = $('.trSelected',grid).length;
             if (0 == record_count)
             {
                 $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                 $("#error").show();
                 setTimeout(function() {
                     $("#error").fadeOut("slow");
                 }, 2000 );
                 return;
             }
             
             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3); 
                 $("#login_interdit").val($('td[abbr="login"] >div', this).html());
             });   
                 
        	$("#add_dialog").dialog({
        		title : 'Editer un nom d\'utilisateur', 
	        	buttons : [
	        		{
	        			text : 'Valider',
	        			click : function(){
	        				$.ajax({
	        					type : 'post',
	        					url : '/logininterdit/edit',
	        					data : {'id' : id, 'login' : $("#login_interdit").val()},
	        					success : function(){
	        						$("#info").html('&nbsp;Le nom d\'utilisateur à été modifié !');
					            	$("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );     
					                $("#add_dialog").dialog('close');
					                $("#tableau_login").flexReload();
							  	}
	        				});
	        			}
	        		},
	        		{
	        			text : 'Annuler',
	        			click : function(){
	        				$(this).dialog('close');
	        			}
	        		}
	        	]

        	});
        }
        
        function delete_record(command, grid){
             // On vérifie si l'utilisateur à le droit
             if($("#supprimer_login").val() != 'true'){
                $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
             var record_count = $('.trSelected',grid).length;
             if (0 == record_count)
             {
                 $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                 $("#error").show();
                 setTimeout(function() {
                     $("#error").fadeOut("slow");
                 }, 2000 );
                 return;
             }
             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);     
             });   
                 
        	$("#delete_dialog").dialog({
        		title : 'Supprimer un nom d\'utilisateur', 
	        	buttons : [
	        		{
	        			text : 'Valider',
	        			click : function(){
	        				$.ajax({
	        					type : 'post',
	        					url : '/logininterdit/delete',
	        					data : {'id' : id},
	        					success : function(){
	        						$("#info").html('&nbsp;Le nom d\'utilisateur à été supprimé !');
					            	$("#info").show();
					                setTimeout(function() {
					                    $("#info").fadeOut("slow");
					                }, 2000 );     
					                $("#delete_dialog").dialog('close');
					                $("#tableau_login").flexReload();
							  }
	        				});
	        			}
	        		},
	        		{
	        			text : 'Annuler',
	        			click : function(){
	        				$(this).dialog('close');
	        			}
	        		}
	        	]

        	});
        }
        
        $(".ftitle").append('<span id="error" style="color : red"></span>');
        $('.ftitle').append('<span id="info" style="color : green"></span>');
	});
</script>
