<div id="content">
    <div id="groupe">
        <table id="tableau_groupe">    
        </table>
    </div>
    <div id="autorisation">
        <table id="tableau_autorisation">
        </table>
    </div>
    <div id="edit_form" style="display : none">
    <?php
        echo $this->form;
    ?>
    </div>
</div>
<div id="delete_modal" style="display : none">
    Etes vous sur de vouloir supprimer ce groupe ? 
</div>
<div id="ajout_utilisateur_groupe" style="display : none">
    <p id="nom_groupe"></p><br />
    Veuillez sélectionner le nom de l'utilisateur que vous voulez ajouter : <br />
    <br /><select id="select_ajout_utilisateur_groupe">
    </select>
</div>
<div id="add_form" style="display : none">
    <?php
        echo $this->form_ajout;
    ?>
</div>

<input type="hidden" id="editer_groupe" value="<?php echo $this->editer_groupe?>" />
<input type="hidden" id="supprimer_groupe" value="<?php echo $this->supprimer_groupe ?>" />
<input type="hidden" id="ajouter_groupe" value="<?php echo $this->ajouter_groupe ?>" />
<input type="hidden" id="ajouter_utilisateur_groupe" value="<?php echo $this->ajouter_utilisateur_groupe ?>"/>

<script type="text/javascript">

    $(document).ready(function(){
        
        // Tableau et fonction des groupes
        $("#tableau_groupe").flexigrid({
            url : 'groupe/getlistegroupe',
            dataType: 'json',
            colModel : [
                    {display: 'ID', name : 'id_groupe', width : 40, sortable : true, align: 'left'},
                    {display: 'Nom', name : 'nom', width : 250, sortable : true, align: 'left'},
                    {display: 'Description', name : 'description', width : 500, sortable : true, align: 'left'}
            ],
            buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},                    
                    {name: 'Ajouter un utilisateur à un groupe', bclass: 'add_user', onpress : add_user},
                    {separator: true},
                    {name: 'Détails', bclass: 'detail', onpress : detail},
                    {separator: true},
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record}
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom'},
                    {display: 'Prenom', name : 'prenom', isdefault: true},
                    {display: 'Description', name : 'description'}
            ],
            sortname: "id_groupe",
            sortorder: "asc",
            usepager: true,
            title: "Liste des groupes",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 500,
            singleSelect: true
        });
        $(".ftitle").append('<span id="info" style="color : red">&nbsp;</span>');
        
        // Détail
        function detail(command, grid){
            // L'utilisateur doit dabord séléctionner une ligne
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#info").html('Veuillez dabord sélectionner une ligne !');
                $("#info").show();
                setTimeout(function() {
                    $("#info").fadeOut("slow");
                }, 2000 );
                return;
             }
             $('.trSelected',grid).each(function(){
                  var id = this.id.substr(3);
                  $.ajax({
                     type : 'post',
                     url : 'groupe/detailgroupe',
                     data : {'id_groupe' : id},
                     success : function(){
                         location.href = "groupe/detailgroupe?id_groupe="+id;
                     }
                  });
             });
        }
        
        // add_record
        function add_record(command, grid){
            // On vérifie si l'utilisateur à le droit
            if($("#ajouter_groupe").val() != 'true'){
                 $("#info").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#info").show();
                 setTimeout(function() {
                     $( "#info" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
            $("#add_form").dialog({
                title : "Ajouter un groupe",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                               type : 'post',
                               url : 'groupe/ajoutergroupe',
                               data : { 'nom' : $("#nom_groupe_add").val(), 'description' : $("#description_groupe").val()},
                               success : function(){
                                    $("#add_form").dialog('close');
                                    $("#tableau_groupe").flexReload();
                                    $("#info").html('&nbsp;Le groupe à été ajouté');
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );
                               } 
                            });
                            $("#add_form").dialog('close');
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            })
        }
        
        // Ajoute un utilisateur à un groupe
        function add_user(command, grid){
            // On vérifie si l'utilisateur à le droit
            if($("#ajouter_utilisateur_groupe").val() != 'true'){
                 $("#info").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#info").show();
                 setTimeout(function() {
                     $( "#info" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#info").html('Veuillez dabord sélectionner une ligne !');
                $("#info").show();
                setTimeout(function() {
                    $("#info").fadeOut("slow");
                }, 2000 );
                return;
             }
             
             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
                 $("#nom_groupe").html(" Groupe : " + $('td[abbr="nom"] >div', this).html());
             });
             
             // Récupération de la liste des noms
             $.ajax({
                type : 'post',
                url : 'utilisateurs/getlistenomformate',
                data : {'id_groupe' : id},
                success : function(data){
                    $("#select_ajout_utilisateur_groupe").html(data);
                } 
             });
             
            $("#ajout_utilisateur_groupe").dialog({
                title : 'Ajouter un utilisateur à un groupe',
                width : 450,
                height : 300,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                               type : 'post',
                               url : 'groupe/ajoututilisateur',
                               data : {'id_groupe' : id, 'id_utilisateur' : $("#select_ajout_utilisateur_groupe").val()},
                               success : function(){
                                     $("#ajout_utilisateur_groupe").dialog('close');
                                     $("#info").html('&nbsp;L\'utilisateur à été ajouté');
                                     $("#info").show();
                                     setTimeout(function() {
                                         $( "#info" ).fadeOut("slow");
                                     }, 2000 );
                               }
                            });
                           $("#ajout_utilisateur_groupe").dialog('close');
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        // delete_record
        function delete_record(command,grid)
        {            
            // On vérifie si l'utilisateur à le droit
            if($("#supprimer_groupe").val() != 'true'){
                 $("#info").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#info").show();
                 setTimeout(function() {
                     $( "#info" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#info").html('Veuillez dabord sélectionner une ligne !');
                $("#info").show();
                setTimeout(function() {
                    $("#info").fadeOut("slow");
                }, 2000 );
                return;
             }         
             $("#delete_modal").dialog({
                title : "Supprimer",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $('.trSelected',grid).each(function(){
                                 var id = this.id.substr(3);
                                 $.ajax({
                                    type : 'post',
                                    url : 'groupe/deletegroupe',
                                    data : {'id_groupe' : id},
                                    success : function(){
                                        $("#delete_modal").dialog('close');
                                        $("#tableau_groupe").flexReload();
                                        $("#info").html('&nbsp;Le groupe à été supprimé');
                                        $("#info").show();
                                        setTimeout(function() {
                                            $( "#info" ).fadeOut("slow");
                                        }, 2000 );
                                    }
                                 });
                             });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
             });
             
         }
         
         // edit_record
         function edit_record(command,grid)
         {
             // On vérifie si l'utilisateur à le droit
             if($("#editer_groupe").val() != 'true'){
                $("#info").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#info").show();
                setTimeout(function() {
                    $("#info").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
             var record_count = $('.trSelected',grid).length;
             if (0 == record_count)
             {
                 $("#info").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                 $("#info").show();
                 setTimeout(function() {
                     $("#info").fadeOut("slow");
                 }, 2000 );
                 return;
             }
             $('.trSelected',grid).each(function(){
                 var id = this.id.substr(3);
                 $("#nom").val($('td[abbr="nom"] >div', this).html());
                 $("#description").val($('td[abbr="description"] >div', this).html());
                                     
                 $("#edit_form").dialog({
                     title : 'Editer',
                     buttons: [
                        {
                            text : "Valider",
                            click : function(){
                                $.ajax({
                                    type : 'post',
                                    url : 'groupe',
                                    data : {
                                        'id_groupe' : id,
                                        'nom' : $("#nom").val(),
                                        'description' : $("#description").val()
                                    },
                                    success : function(){
                                        $("#tableau_groupe").flexReload();
                                        $("#edit_form").dialog('close');
                                    }
                                });
                            }
                        },
                        {
                            text : "Annuler",
                            click : function(){
                                $(this).dialog('close');
                            }
                        }
                    ]
                 });
             });
         }
            
    });

</script>