<table id="tableau_question">
</table>
<div id="delete_dialog" style="display:none">
    <p>Etes vous sur de vouloir supprimer cette question ?</p>
</div>
<div id="edit_form" style="display : none">
    <?php
        echo $this->edit_form;
    ?>
</div>
<div id="lier_question" style="display : none" >
	<p>
		<label for="recherche_question">Rechercher par une question</label><br />
		<input type="text" id="recherche_question" />
	</p>
	<br />
	<p>
		<label for="recherche_id">Rechercher par un numéro</label><br />
		<input type="text" id="recherche_id" />
	</p>
		<input type="checkbox" id="question_obligatoire_lier" /><label for="question_obligatoire_lier">Question obligatoire</label>
	<br />
	<p>
		<input type="submit" id="enregistrer_lier" value="lier" />
		<br />
		<span id="info_enregistrer_lier" style="color : green"></span>
		<span id="erreur_enregistrer_lier" style="color : red"></span>
	</p>
</div>
<div id="ajouter_question" style="display : none">
	<div id="question_reponse">
		<p style="text-align : center"><label for="question_obligatoire">Question obligatoire : </label><input type="checkbox" id="question_obligatoire" /></p><br />
		<p style="margin-left : 0.7em; margin-bottom : 0.5em"><label class="ajouter_question_label" for="question">Question : </label><textarea id="question" class="question"></textarea></p>
		<p><label class="ajouter_question_label" for="reponse">Réponse 1: </label><textarea id="reponse" class="reponse"></textarea><input type="checkbox" id="reponse_juste" class="reponse_juste"/><label for="reponse_juste">Réponse juste</label></p>
		<p><label class="ajouter_question_label" for="reponse2">Réponse 2: </label><textarea id="reponse2" class="reponse"></textarea><input type="checkbox" id="reponse_juste" class="reponse_juste"/><label for="reponse_juste">Réponse juste</label></p>
		<div id="container_reponse"></div>
	</div>
	<a id="ajouter_reponse" ><img alt="Ajouter une reponse" src="<?php APPLICATION_PATH?>/images/ajouter-modifier-icone-9159-16.png" />&nbsp;Ajouter une réponse</a>
	<input type="checkbox" id="reponse_ouverte" /><label for="reponse_ouverte">Réponse ouverte</label>
	<p><input type="submit" id="valider_question_reponse" value="Enregistrer" /> <span id="info_enregistrer" style="color : green"></span><span id="erreur_enregistrer" style="color : red"></span></p>
</div>

<input type="hidden" id="certification_demande" value="<?php echo $this->certification_demande?>" />
<input type="hidden" id="ajouter_question_droit" value="<?php echo $this->ajouter_question?>" />
<input type="hidden" id="editer_question" value="<?php echo $this->editer_question?>" />
<input type="hidden" id="supprimer_question" value="<?php echo $this->supprimer_question?>" />

<script type="text/javascript">
    $(document).ready(function(){
    
    	// Lorsque on coche la case réponse ouverte
    	$("#reponse_ouverte").change(function(){
    		// Si on coche la case, on efface toute les réponses, et on les disabled
    		if($(this).attr('checked') == "checked"){
    			$(".reponse").each(function(){
    				$(this).attr('disabled', 'disabled');
    				$(this).val('');
    			});
    		}else{
    			// Sinon on les réactive
    			$(".reponse").each(function(){
    				$(this).removeAttr('disabled');
    			});
    		}
   	
    	});
    	    	
    	// Lorsque on enregistre une question
    	$("#valider_question_reponse").click(function(){

			// OOn récupère les valeurs
			var reponse = [];
			var question = $(".question").val();
			var question_obligatoire = $("#question_obligatoire").attr('checked');
			var reponse_ouverte = $("#reponse_ouverte").attr('checked');
			$(".reponse").each(function(){
				if($(this).val() == "")
					return;
				reponse.push($(this).val() + ',' + $(this).next('input[:checked]').attr('checked'));
			});
			
			// On vérifie que la question a été remplie
			if(question == ""){
				$("#erreur_enregistrer").html("Veuillez remplir la question");
	            $("#erreur_enregistrer").show();
	                setTimeout(function() {
	                    $( "#erreur_enregistrer" ).fadeOut("slow");
	                }, 2000 );  
				return;
			}
				
			// On vérifie que il y a au moins deux réponses de remplies		
			if(reponse.length < 2){
				if(reponse_ouverte == "checked"){
					// On ne fait rien et on sors de la boucle si la réponse ouverte est cochée
				}else{
					$("#erreur_enregistrer").html("Veuillez remplir au moins deux réponses");
	            	$("#erreur_enregistrer").show();
	                setTimeout(function() {
	                    $( "#erreur_enregistrer" ).fadeOut("slow");
	                }, 2000 );  
				return;
				}
			}
									
			// On enregistre le tout
			$.ajax({
				type : "post",
				url : "/questions/ajouter",
				data : {question : question, reponse : reponse, id_certification : $("#certification_demande").val(), question_obligatoire : question_obligatoire, reponse_ouverte : reponse_ouverte},
				success : function(){
					// On remet le formulaire à zero
					resetAddForm();
					
					// On affiche la confirmation
					$("#info_enregistrer").html("Votre question a été enregistrée");
	                $("#info_enregistrer").show();
	                setTimeout(function() {
	                    $( "#info_enregistrer" ).fadeOut("slow");
	                }, 2000 );    
				}
			});		
       	});
    	
    	// Ajoute un champ de réponse supplémentaire
    	$("#ajouter_reponse").click(function(){	
    		var nombre_reponse = 0;
	
    		$(".reponse").each(function(){
    			nombre_reponse ++;
    		});
    		
    		$("#container_reponse").append("<p><label class='ajouter_question_label' for='reponse"+nombre_reponse+"'>Réponse "+(nombre_reponse+1)+": </label><textarea id='reponse"+nombre_reponse+"' class='reponse'></textarea><input type='checkbox' class='reponse_juste' id='reponse_juste"+nombre_reponse+"'/><label for='reponse_juste"+nombre_reponse+"'>Réponse juste</label></p>");
    	});
    	
    	// Lorsque on lie une question
    	$("#enregistrer_lier").click(function(){
			
			// Si un des deux champs est vide
			if($("#recherche_id").val() == "" || $("#recherche_question").val() == ""){
				// On affiche une erreur
				$("#erreur_enregistrer_lier").html("Veuillez renseigner un des deux champs");
                $("#erreur_enregistrer_lier").show();
                setTimeout(function() {
                    $( "#erreur_enregistrer_lier" ).fadeOut("slow");
                }, 2000 );    
				return;
			}
			
			// Lie la question à la certification
			$.ajax({
				type : 'post',
				url : '/certifications/ajouteracertification',
				data : {id_question : $("#recherche_id").val(), id_certification : $("#certification_demande").val(), question_obligatoire : $("#question_obligatoire_lier").attr('checked')},
				success : function(){
					// On affiche la confirmation
					$("#info_enregistrer_lier").html("La question à bien été liée à la certification");
	                $("#info_enregistrer_lier").show();
	                setTimeout(function() {
	                    $( "#info_enregistrer_lier" ).fadeOut("slow");
	                }, 2000 );    
	                
	                // On remet les champs à zéro
	                $("#recherche_question").val('');
	                $("#recherche_id").val('');
	                $("#question_obligatoire_lier").removeAttr('checked');
				}
			})
			
    	});
    
        $("#tableau_question").flexigrid({
            url : 'getlistequestionreponse?id_certification='+$("#certification_demande").val(),
            dataType: 'json',
            colModel : [
                    {display: 'Question', name : 'question', width : 150, sortable : true, align: 'left'},
                    {display: 'Nombre de réponse', name : 'nbr_reponse', width : 150, sortable : true, align: 'left'},                    
                    {display: 'Question obligatoire', name : 'question_obligatoire', width : 150, sortable : false, align: 'left'},
                    {display: 'Réponse ouverte', name : 'reponse_ouverte', width : 150, sortable : false, align: 'left'}
            ],
           buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},                    
                    {name: 'Lier', bclass: 'relier', onpress : link_question},
                    {separator: true},
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
            ],
            searchitems : [
                    {display: 'Question', name : 'question', isdefault: true}
            ],
            sortname: "id_question",
            sortorder: "asc",
            usepager: true,
            title: "Liste des questions",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 480,
            singleSelect: true
        });
        $(".ftitle").append('<span id="error" style="color : red">&nbsp;</span>');
        $(".ftitle").append('<span id="info" style="color : green">&nbsp;</span>');
               	
        // Autocomplete de la question
        $("#recherche_question, #recherche_id").autocomplete({
            source: function(request, response){
	            var objData = {};
	            if($(this.element).attr('id') == 'recherche_id'){
	                objData = {id : request.term, id_certification : $("#certification_demande").val(), maxRows : 10};
	            }else{
	                objData = {question : request.term, id_certification : $("#certification_demande").val(), maxRows : 10};
	            }
	        
	            $.ajax({
	               url : "/Autocomplete/autocompletequestion",
	               dataType : "json",
	               data : objData,
	               type : 'POST',
	               success : function(data){
	                   // Ajout de reponse dans le cache
	                   response($.map(data, function (item){
	                       return{
	                           label : item.id_question + " - " + item.question,
	                           value: function (){
									if ($(this).attr('id') == 'recherche_id'){
										$('#recherche_question').val(item.question);
										return item.id_question;
									}
									else{
										$('#recherche_id').val(item.id_question);
										return item.question;
									}
								}
	                       }
	                   }));
	               }
	            });                
            },
            minLength : 2,
            delay : 0
        });

        function resetAddForm(){
        	// Remet le formulaire d'ajout de question à zéro
			var div = $("#question_reponse");
    		div.html('<p style="text-align : center"><label for="question_obligatoire">Question obligatoire : </label><input type="checkbox" id="question_obligatoire" /></p><br />');
    		div.append('<p style="margin-left : 0.7em; margin-bottom : 0.5em"><label class="ajouter_question_label" for="question">Question : </label><textarea id="question" class="question"></textarea></p>');
    		div.append('<p><label class="ajouter_question_label" for="reponse">Réponse 1: </label><textarea id="reponse" class="reponse"></textarea><input type="checkbox" id="reponse_juste" class="reponse_juste"/><label for="reponse_juste">Réponse juste</label></p>');
    		div.append('<p><label class="ajouter_question_label" for="reponse2">Réponse 2: </label><textarea id="reponse2" class="reponse"></textarea><input type="checkbox" id="reponse_juste" class="reponse_juste"/><label for="reponse_juste">Réponse juste</label></p>');
    		div.append('<div id="container_reponse"></div>');
        }
        
        function add_record(command, grid){
        
        	// On vérifie si l'utilisateur à l'authorisation d'ajouter une question
        	if($("#ajouter_question_droit").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
                return;
            }  
            
            // On remet le formulaire à zéro
            resetAddForm();
            
        	$("#ajouter_question").dialog({
        		title : "Ajouter une question",
        		width : 900,
        		height : 600,
        		buttons : [
        			{
        				text : "Fermer",
        				click : function(){
        					$("#tableau_question").flexReload();
        					$(this).dialog('close');
        				}
        			}
        		]
        	});
        }
        
        function edit_record(command, grid){
            if($("#editer_question").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
                return;
            }
            
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }
             
             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
                 $("#question").val($('td[abbr="question"] >div', this).html());
                 $("#nbr_reponse").val($('td[abbr="nbr_reponse"] >div', this).html());                 
             });            
             
             $("#edit_form").dialog({
                 title : "Editer une question",
                 buttons : [
                     {
                         text : "Valider",
                         click : function(){
                             $.ajax({
                                 type : 'post',
                                 url : '/Questions/editer',
                                 data : {
                                     'id_question' : id,
                                     'question' : $("#question").val(),
                                     'nbr_reponse' : $("#nbr_reponse").val(),
                                 },
                                 success : function(){
                                     $("#tableau_question").flexReload();
                                     $("#edit_form").dialog('close');
                                     $("#info").html("Question editée !");
                                     $("#info").show();
                                     setTimeout(function() {
                                         $( "#info" ).fadeOut("slow");
                                     }, 2000 );                                    
                                 }
                             })
                         }
                     },
                     {
                         text : "Annuler",
                         click : function(){
                             $(this).dialog('close');
                         }
                     }
                 ]
             });
            
        }
        
        function delete_record(command, grid){
            if($("#supprimer_question").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
                return;
            }
            
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }

             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
             });
             
             $("#delete_dialog").dialog({
                 title : "Supprimer une question",
                 buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : '/Questions/delete',
                                data : {'id_question' : id},
                                success : function(){
                                    $("#tableau_question").flexReload();
                                    $("#delete_dialog").dialog('close');
                                    $("#info").html("Question supprimée !");
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );
                                }
                            })
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                 ]
             });
        }
        
        function link_question(){
        	// Lie une question existante à la certification
        	
        	// On vérifie si l'utilisateur à l'authorisation d'ajouter une question
        	if($("#ajouter_question_droit").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
                return;
            }  

        	$("#lier_question").dialog({
        		title : "Lier une question",
        		width : 400,
        		buttons : [
        			{
						text : "Fermer",
						click : function(){
							$("#tableau_question").flexReload();
							$(this).dialog('close');
						}        			
        			}
        		]
        	});	
        	
        }
    });
</script>