<?php
    echo $this->placeholder('menu-connecte');
?>
<table id="tableau_certifications">
</table>
<div id="add_form" style="display : none">
    <div id="label_certification">
        <label for="nom" class="optional">Nom :</label>
        <label for="type" class="optional">Type :</label>
        <label for="nombre_question" class="optional">Nombre de question :</label>
        <label for="temps_certification" class="optional">Temps certification (mn) :</label>
        <label for="score_minimum" class="optional">Score minimum (%) :</label>
        <label for="duree_validite" class="optional">Durée de validité (années) :</label>   
    </div> <!-- label_certification -->
    <div id="input_certification">
        <input type="text" name="nom" id="nom" value="" />
        <input type="text" name="type" id="type" value="" />
        <input type="text" name="nombre_question" id="nombre_question" value="" />
        <input type="text" name="temps_certification" id="temps_certification" value="" />
        <input type="text" name="score_minimum" id="score_minimum" value="" />
        <input type="text" name="duree_validite" id="duree_validite" value="" />
    </div> <!-- input_certification -->
</div>
<div id="delete_dialog" style="display : none">
    <p>Etes vous sur de vouloir supprimer cette certification ? </p>
</div>
<div id="edit_form" style="display : none">
    <?php
        echo $this->edit_form;
    ?>
</div>
<input type="hidden" id="ajouter_certification" value="<?php echo $this->ajouter_certification?>" />
<input type="hidden" id="modifier_certification" value="<?php echo $this->modifier_certification?>" />
<input type="hidden" id="supprimer_certification" value="<?php echo $this->supprimer_certification?>" />

<script type="text/javascript">
    $(document).ready(function(){
        $("#tableau_certifications").flexigrid({
            url : 'certifications/getlistecertification',
            dataType: 'json',
            colModel : [
                    {display: 'Nom', name : 'nom', width : 150, sortable : true, align: 'left'},
                    {display: 'Type', name : 'type', width : 150, sortable : true, align: 'left'},
                    {display: 'Nombre de question', name : 'nombre_question', width : 150, sortable : true, align: 'left'},
                    {display: 'Temps de passage', name : 'temps_certification', width : 150, sortable : true, align: 'left'},
                    {display: 'Score minimum', name : 'score_minimum', width : 100, sortable : true, align: 'left'},
                    {display: 'Durée de validité (années)', name : 'duree_validite', width : 150, sortable : true, align: 'left'}
            ],
           buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record},
                    {separator: true},                    
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
                    {separator : true},
                    {name: 'Détails', bclass: 'detail', onpress : detail_record}
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom', isdefault: true},
                    {display: 'Type', name : 'type'}
            ],
            sortname: "id_certification",
            sortorder: "asc",
            usepager: true,
            title: "Liste des certifications",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 480,
            singleSelect: true
        });
        $(".ftitle").append('<span id="error" style="color : red">&nbsp;</span>');
        $(".ftitle").append('<span id="info" style="color : green">&nbsp;</span>');
        
        function add_record(command, grid){
            if($("#ajouter_certification").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
            }
            
            // On vide les champs par sécurité            
            $("#nom").val('');
            $("#type").val('');
            $("#nombre_question").val('');
            $("#temps_certification").val('');
            $('#score_minimum').val('');
            $('#duree_validite').val('');
            
            $("#add_form").dialog({
                title : "Ajouter une certification",
                width : 560,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : 'certifications/addcertification',
                                data : { "nom" : $("#nom").val(), 'type' : $("#type").val(), "nombre_question" : $("#nombre_question").val(), "temps_certification" : $("#temps_certification").val(), 'score_minimum' : $('#score_minimum').val(), 'duree_validite' : $('#duree_validite').val()},
                                success : function(){
                                    $("#tableau_certifications").flexReload();
                                    $("#add_form").dialog('close');
                                    $("#info").html("Certification ajoutée");
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );
                                }
                            });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        function edit_record(command, grid){
            // On vérifie si l'utilisateur à le droit
            if($("#modifier_certification").val() != 'true'){
                $("#error").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );     
                return false;
            }
             
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                     $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            var id;
            $('.trSelected',grid).each(function(){
                id = this.id.substr(3);
                                  
                $("#nom").val($('td[abbr="nom"] >div', this).html());
                $("#type").val($('td[abbr="type"] >div', this).html());
                $("#nombre_question").val($('td[abbr="nombre_question"] >div', this).html());
                $("#temps_certification").val($('td[abbr="temps_certification"] >div', this).html());
                $("#score_minimum").val($('td[abbr="score_minimum"] >div', this).html());
                $("#duree_validite").val($('td[abbr="duree_validite"] >div', this).html());
            });
            
            $("#add_form").dialog({
                title : "Modifier une certification",
                width : 560,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : '/certifications/editcertification',
                                data : {'id_certification' : id, 'nom' : $("#nom").val(), 'type' : $("#type").val(), "nombre_question" : $("#nombre_question").val(), "temps_certification" : $("#temps_certification").val(), 'score_minimum' : $('#score_minimum').val(), 'duree_validite' : $('#duree_validite').val()},
                                success : function(){
                                    $("#tableau_certifications").flexReload();
                                    $("#edit_form").dialog('close');
                                    $("#info").html('&nbsp;La certification à été modifiée !');
                                    $("#info").show();
                                    setTimeout(function() {
                                        $("#info").fadeOut("slow");
                                    }, 2000 );
                                }
                            });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        function delete_record(command, grid){
            if($("#supprimer_certification").val() != "true"){
                $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
                $("#error").show();
                setTimeout(function() {
                    $( "#error" ).fadeOut("slow");
                }, 2000 );
            }
            
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }

             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
             });
             
            $("#delete_dialog").dialog({             
                title : "Supprimer une certification",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : 'certifications/delete',
                                data : {'id_certification' : id},
                                success : function(){
                                    $("#tableau_certifications").flexReload();
                                    $("#delete_dialog").dialog('close');  
                                    $("#info").html("Certification supprimée");
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );                                  
                                }
                            })
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            })
        }
        
        function detail_record(command, grid){
            
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
            }
            
            var id;
            $('.trSelected',grid).each(function(){
                id = this.id.substr(3);
            });
            location.href = "certifications/detailcertification?id="+id;
        }
    });
</script>