<h1>Passage de certification</h1>
<p><?php echo $this->navigation()->breadcrumbs()->setSeparator(' > '); ?></p>
<div id="nom_certification">
<?php
    echo "<h4 class='h5_modifie'>$this->nom_certification</h4>"
?>
</div> <!-- nom_certification -->

<h4 id="countdown" ></h4>

<div id="qcm">
    <?php
        foreach($this->question as $row){
            echo $row;
        }
    ?>
    <p id="last"></p>			    	
	<br /><p id="bouton_certification"><button class='submit' id="previous">Précédent</button><button class='submit' id="next">Suivant</button><button class='submit' id="finish" style="display : none">Finir</button></p>
</div> <!-- qcm -->

<div id="confirmer_fini" style="display : none">
	Attention, en validant vous allez terminer la certification !<br />
	Etes vous sur de vouloir valider ? 
</div> <!-- confirmer_fini -->
<input type="hidden" id="temps_certification" value="<?php echo $this->temps_certification?>">
<input type="hidden" id="id_certification" value="<?php echo $this->id_certification ?>"/>
 
<script type="text/javascript">
    $(document).ready(function(){
        
        // On affiche le premier élément
        $("#qcm :first-child").addClass('active');
        $(".active").show();
        
        // Si c'est le premier élément on cache le bouton précédent
        if($("#qcm").find('div.active').is(":first-child")){
            $("#previous").hide();
        }
                        
        $("#next").click(function(){   
            // Lorsque on clique sur next on affiche le suivant et cache le précédent     
            $("#qcm").find('div.active').next().addClass('active').prev().removeClass('active');
            $(".question").slideUp();
            $('.active').slideDown();
            
			if($("#qcm").find('div.active').next().attr('id') == 'last'){
				$("#next").hide();
				$("#finish").show();
			}			
            
        });
        
        $("#previous").click(function(){
            // Lorsque on clique sur précédent, on affiche le précédent et on cache le suivant
            $("#qcm").find('div.active').prev().addClass('active').next().removeClass('active');
            $(".question").slideUp();
            $('.active').slideDown(function(){
                if($("#qcm").find('div.active').is(":first-child")){
                    $("#previous").hide();
                }
            });
            $("#next").show();
            $("#finish").hide();
        });
        
        function sendCertification(){
        	// On récupère les trois type de réponses possible, 1 réponses, multiples réponses, réponses ouvertes
			var reponse = [];
            $("input[type='radio']:checked").each(function(){
                reponse.push($(this).attr('name')+","+$(this).val());
            });
            $("input[type='checkbox']:checked").each(function(){
                reponse.push($(this).attr('name')+","+$(this).val());
            });
            $("textarea").each(function(){
            	reponse.push($(this).attr('name')+','+$(this).val());
            });
            
            //console.log(reponse);
            
            // On envoie le tout à la correction           
            $.ajax({
                type : 'post',
                url : '/certifications/corrigecertification',
                data : { 'certification' : reponse, 'id_certification' : $("#id_certification").val()},
                success : function(){
                    $("#confirmer_fini").dialog('close');
                	location.href = "/score-certification";
                }
            });
        }
               
        $('#countdown').countdown({
        	date: $("#temps_certification").val(),
        	onComplete: function( event ) {
				$("#next").hide().attr('disabled', 'disabled');
				$("#previous").hide().attr('disabled', 'disabled');
				$(".question").hide();
				$("#finish").show();
				$("#countdown").hide();
			},
			leadingZero: true,
			direction: "down"
        });
        
        $("#finish").click(function(){
        	$("#confirmer_fini").dialog({
        		buttons : [
        			{
        				text : 'Valider',
        				click : function(){
        					sendCertification();				            
        				}
        			},
        			{
        				text : 'Annuler',
        				click : function(){
        					$(this).dialog('close');
        				}
        			}
        		]
        	});
        });
        
	});
</script>