<h1>Résultat de votre certification</h1>
<?php
	if($this->pourcentage >= $this->score_minimum)
		echo "<p id='pourcentage'>Votre score est de <span style='color : green'>".$this->pourcentage."%</span></p>";
	else
		echo "<p id='pourcentage'>Votre score est de <span style='color : red'>".$this->pourcentage."%</span></p>";		
?>
<p><button id="retour">Retour à votre profil</button></p>
<script type="text/javascript">
	$(document).ready(function(){
		$("#retour").click(function(){
			location.href = "/utilisateurs/";
		});
	});
</script>