
<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="#LANG" lang="#LANG" dir="#LANG_DIR">
	<head> 
	    <title>Easylia</title>
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <meta http-equiv="Content-Style-Type" content="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/style.css" rel="stylesheet" type="text/css" />
<!-- 	    <link href="<?php APPLICATION_PATH?>/css/gabarit.css" rel="stylesheet" type="text/css" /> -->
	    <link href="<?php APPLICATION_PATH?>/css/zend.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/flexigrid.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/fullcalendar.css" rel="stylesheet" type="text/css" />
	    <link rel="icon" type="image/png" href="<?php APPLICATION_PATH ?>/images/favicon.ico" />
	    <script src="<?php APPLICATION_PATH?>/js/jquery.1.6.2.min.js" type="text/javascript"></script>
	    <script src="<?php APPLICATION_PATH?>/js/flexigrid.js" type="text/javascript"></script>
	    <script src="<?php APPLICATION_PATH?>/js/wtootltip.js" type="text/javascript"></script>
	    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.slideshow.js"></script>  
	    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/script.js"></script>     
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery-ui-1.8.16.custom.min.js"></script>
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.jcountdown1.3.2.js"></script>	
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/timepicker.js"></script>	
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/fullcalendar.js"></script>
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/ckeditor/ckeditor.js"></script> 
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/ckeditor/adapters/jquery.js"></script> 
		<script src="<?php APPLICATION_PATH?>/js/cufon-yui.js" type="text/javascript"></script> 
		<script src="<?php APPLICATION_PATH?>/js/cufon-replace.js" type="text/javascript"></script> 
		<script src="<?php APPLICATION_PATH?>/js/Myriad_Pro_400.font.js" type="text/javascript"></script>
		<script src="<?php APPLICATION_PATH?>/js/Humnst777_BT_700.font.js" type="text/javascript"></script>
		<script src="<?php APPLICATION_PATH?>/js/function.js" type="text/javascript"></script>

		<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
	<!--
	<script src="<?php APPLICATION_PATH?>/js/cufon-yui.js" type="text/javascript"></script> 
		<script src="<?php APPLICATION_PATH?>/js/cufon-replace.js" type="text/javascript"></script> 
-->
	</head>
	
	<body class="page_sommaire">
		<div id="page">
			<div class="right_bgd"></div>	<!-- right_bgd -->
				<div id="header">
					<div id="onglets">
						<ul class="menu-liste menu-items">
							<li class="menu-entree item first">
								<a href="http://easylia.com/"> <cufon class="cufon cufon-canvas" alt="Accueil" style="width: 67px; height: 16px; "><canvas width="76" 	height="20" style="width: 76px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Accueil</cufontext></cufon></a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Installation"> <cufon class="cufon cufon-canvas" alt="Installation" style="width: 111px; height: 16px; "><canvas width="117" height="20" style="width: 117px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Installation</cufontext></cufon></a>	 
						 	</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Formation"><cufon class="cufon cufon-canvas" alt="Formation" style="width: 95px; height: 16px; "><canvas width="101" height="20" style="width: 101px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Formation</cufontext></cufon></a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Assistance-optimisation"  style="margin-top: -0.5em; height: 2.95em; "><cufon class="cufon cufon-canvas" alt="Assistance " style="width: 100px; height: 16px; "><canvas width="113" height="20" style="width: 113px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Assistance </cufontext></cufon><cufon class="cufon cufon-canvas" alt="&amp; " style="width: 17px; height: 16px; "><canvas width="30" height="20" style="width: 30px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>&amp; </cufontext></cufon><cufon class="cufon cufon-canvas" alt="optimisation" style="width: 114px; height: 16px; "><canvas width="119" height="20" style="width: 119px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>optimisation</cufontext></cufon></a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Tarifs" ><cufon class="cufon cufon-canvas" alt="Tarif" style="width: 43px; height: 16px; "><canvas width="52" height="20" style="width: 52px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Tarif</cufontext></cufon></a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/contact" ><cufon class="cufon cufon-canvas" alt="Contact" style="width: 74px; height: 16px; "><canvas width="83" height="20" style="width: 83px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Contact</cufontext></cufon></a>
							</li>
							<li class="menu-entree item item_formateur">
								<a href="http//easylia.com/Devenir-formateur" style="margin-top: -0.5em; height: 2.95em; "><cufon class="cufon cufon-canvas" alt="Devenir " style="width: 74px; height: 16px; "><canvas width="86" height="20" style="width: 86px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>Devenir </cufontext></cufon><cufon class="cufon cufon-canvas" alt="formateur" style="width: 97px; height: 16px; "><canvas width="105" height="20" style="width: 105px; height: 20px; top: -4px; left: -1px; "></canvas><cufontext>formateur</cufontext></cufon></a>
							</li>
						</ul>
					</div> <!-- onglets -->
					<div id="header_content">
						<div id="logo">
							<a href="http://in.easylia.com"><img alt="" src="<?php APPLICATION_PATH?>/images/logo.jpg" class="logo" /></a><br />
						</div> <!-- logo -->
						<div id="phone">
							<h2><cufon class="cufon cufon-canvas" alt="0800" style="width: 84px; height: 40px; "><canvas width="106" height="46" style="width: 106px; height: 46px; top: -5px; left: -2px; "></canvas><cufontext>0800</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 20" style="width: 51px; height: 40px; "><canvas width="73" height="46" style="width: 73px; height: 46px; top: -5px; left: -2px; "></canvas><cufontext> 20</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 33" style="width: 51px; height: 40px; "><canvas width="73" height="46" style="width: 73px; height: 46px; top: -5px; left: -2px; "></canvas><cufontext> 33</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 20" style="width: 51px; height: 40px; "><canvas width="73" height="46" style="width: 73px; height: 46px; top: -5px; left: -2px; "></canvas><cufontext> 20</cufontext></cufon></h2>
						</div>
					</div> <!-- header_content -->
				</div> <!-- header -->
				<div id="content">
					<div id="content-main">
						<?php
							echo $this->layout()->content; 
						 ?>
					</div> <!-- content-main> -->
				</div> <!-- content -->
			<div id="footer">
				<div id="footer_content">
					<div id="footer_content_left">
						<p><span class="h3" style="margin-rigth: 0.5em;">Easylia</span> &copy; 2012 | <a href="./Mentions-legales">Mentions légales</a></p>
						<ul class="menu-liste menu-items">
							<li class="menu-entree item first">
								<a href="http//easylia.com/">Accueil</a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Installation">Installation</a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Formation">Formation</a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Assistance-optimisation">Assistance &amp; optimisation</a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/Tarifs">Tarif</a>
							</li>
							<li class="menu-entree item">
								<a href="http//easylia.com/contact">Contact</a>
							</li>
							<li class="menu-entree item item_formateur">
								<a href="http//easylia.com/Devenir-formateur">Devenir formateur</a>
							</li>
						</ul>
					</div>
					<div id="footer_content_right">
						<h1 style="margin-bottom: 0;"><cufon class="cufon cufon-canvas" alt="0800" style="width: 51px; height: 24px; "><canvas width="65" height="28" style="width: 65px; height: 28px; top: -3px; left: -1px; "></canvas><cufontext>0800</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 20" style="width: 31px; height: 24px; "><canvas width="44" height="28" style="width: 44px; height: 28px; top: -3px; left: -1px; "></canvas><cufontext> 20</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 33" style="width: 31px; height: 24px; "><canvas width="44" height="28" style="width: 44px; height: 28px; top: -3px; left: -1px; "></canvas><cufontext> 33</cufontext></cufon><cufon class="cufon cufon-canvas" alt=" 20" style="width: 31px; height: 24px; "><canvas width="44" height="28" style="width: 44px; height: 28px; top: -3px; left: -1px; "></canvas><cufontext> 20</cufontext></cufon></h1>	
						<p>Appel gratuit</p>
					</div>  <!-- footer_content_right -->
				</div> <!-- footer-content -->
			</div> <!-- footer -->
		</div><!--Fin Page -->
	</body>		
</html>	
<script type="text/javascript">
$(document).ready(function(){

		// Infobulle sur les liens
		$("a").wTooltip();

         var isLogged = false;
         <?php
            // le namespace est setté en haut de la page
            if(!empty($user->is_logged) && $user->is_logged == true) {?> 
             isLogged = true;
         <?php } ?>
        
       //Récupération des infos et envoie à l'action login du controller utilisateurs.
       $("#submitLogin").click(function(){
           $.ajax({
              type: 'post',
              url: '/utilisateurs/connexionFromIndex',
              data: {'login' : $("#login_top").val(), 'password' : $("#password_top").val(), 'loginFromIndex' : true, 'remember' : $("#remember").val()},
              success : function(data){
                   if(data != ''){
                       $("#userHello").html('Bonjour '+ data + " !");
                       $("#isNotLogged").hide();
                       $("#isLogged").show();
                       location.reload();
                    }else{
                        $("#erreur").html("Votre nom d'utilisateur ou votre mot de passe ne correspond pas !");
                        $("#erreur").show();
                        setTimeout(function() {
                            $( "#erreur" ).fadeOut("slow");
                        }, 2000 );
                    }                
              }
           });
       });
       
       $("#deconnexion").click(function(){
           $.ajax({
               type: 'post',
               url: '/utilisateurs/deconnexion',
               success: function(){
               		location.href = "http://easylia.com";
               }
           }); 
       });
       
       $("#votreCompte").click(function(){
            window.location.replace("/utilisateurs");
       });
                  
       if( isLogged === true){
            $("#isNotLogged").hide();
            $("#isLogged").show();
       }else{
           $("#isNotLogged").show();
           $("#isLogged").hide();
       }

    });
    
	// google analytics
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-23892247-1']);
	_gaq.push(['_setDomainName', '.easylia.com']);
	_gaq.push(['_trackPageview']);
	
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();



</script>

</html>



