
<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="#LANG" lang="#LANG" dir="#LANG_DIR">
	<head> 
	    <title>Easylia</title>
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <meta http-equiv="Content-Style-Type" content="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/style.css" rel="stylesheet" type="text/css" />
<!-- 	    <link href="<?php APPLICATION_PATH?>/css/gabarit.css" rel="stylesheet" type="text/css" /> -->
	    <link href="<?php APPLICATION_PATH?>/css/zend.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/flexigrid.css" rel="stylesheet" type="text/css" />
	    <link href="<?php APPLICATION_PATH?>/css/fullcalendar.css" rel="stylesheet" type="text/css" />
	    <link rel="icon" type="image/png" href="<?php APPLICATION_PATH ?>/images/favicon.ico" />
	    <script src="<?php APPLICATION_PATH?>/js/jquery.1.6.2.min.js" type="text/javascript"></script>
	    <script src="<?php APPLICATION_PATH?>/js/flexigrid.js" type="text/javascript"></script>
	    <script src="<?php APPLICATION_PATH?>/js/wtootltip.js" type="text/javascript"></script>
	    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.slideshow.js"></script>  
	    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/script.js"></script>     
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery-ui-1.8.16.custom.min.js"></script>
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.jcountdown1.3.2.js"></script>	
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/timepicker.js"></script>	
		<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/fullcalendar.js"></script>  
		<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
	<!--
	<script src="<?php APPLICATION_PATH?>/js/cufon-yui.js" type="text/javascript"></script> 
		<script src="<?php APPLICATION_PATH?>/js/cufon-replace.js" type="text/javascript"></script> 
-->
	</head>
	
	<body class="page_sommaire">
		<div id="page">
			<div class="right_bgd"></div>	<!-- right_bgd -->
				<div id="header">
					<div id="onglets">
						<ul>
	                    	<li class="menu-entree item first">
								<a href="http://spip.easylia.com/" >Accueil</a>
							 </li>
							<li class="menu-entree item">
								<a href="Installation" >Installation</a>
							</li>
							<li class="menu-entree item">
								<a href="Formation" >Formation</a>
							</li>		
							<li class="menu-entree item">
								<a href="Assistance" >Assistance</a>
							</li>	
							<li class="menu-entree item">
								<a href="Tarifs" >Tarifs</a> 
							 </li>	
							<li class="menu-entree item">
								<a href="Contact">Contact</a>		 
							 </li>		
							<li class="menu-entree item item_formateur">
								<a href="Devenir-formateur">Devenir <br />formateur</a>		                
							</li>
						</ul>	   
					</div> <!-- onglets -->
					<div id="header_content">
						<div id="logo">
							<a href="http://dev.easylia.com"><img alt="" src="<?php APPLICATION_PATH?>/images/logo.jpg" class="logo" /></a><br />
						</div> <!-- logo -->
						<div id="search">
							<h2>0810 123 456</h2>
							<form action="" id="form1">
								<p>
									<input type="text" class="input" value="Rechercher…" onblur="if(this.value=='') this.value='Rechercher…'" onfocus="if(this.value =='Rechercher…' ) this.value=''"  />
									<a href="#" onclick="document.getElementById('form1').submit()"><img alt="" src="<?php APPLICATION_PATH ?>/images/button.gif" /></a>
								</p>
							</form>
						</div> <!-- search -->
					</div> <!-- header_content -->
				</div> <!-- header -->
				<div id="content">
					<div id="content-main">
						<?php
							echo $this->layout()->content; 
						 ?>
					</div> <!-- content-main> -->
				</div> <!-- content -->
			<div id="footer">
				<div id="footer_content">
					<div id="footer_content_left">
						<p><span class="h3" style="margin-rigth: 0.5em;">Easylia</span> &copy; 2012 | <a href="./Mentions-legales">Mentions légales</a></p>
						<ul class="menu-liste menu-items">
							<li class="menu-entree item first">
								<a href="http://spip.easylia.com/">Accueil</a>
							</li>
							<li class="menu-entree item">
								<a href="Installation">Installation</a>
							</li>
							<li class="menu-entree item">
								<a href="Formation">Formation</a>
							</li>
							<li class="menu-entree item">
								<a href="Assistance-optimisation">Assistance &amp; optimisation</a>
							</li>
							<li class="menu-entree item">
								<a href="Tarifs">Tarif</a>
							</li>
							<li class="menu-entree item">
								<a href="contact">Contact</a>
							</li>
							<li class="menu-entree item item_formateur">
								<a href="Devenir-formateur">Devenir formateur</a>
							</li>
						</ul>
					</div>
					<div id="footer_content_right">
						<h1 style="margin-bottom: 0;">0810 123 456</h1>
						<p>Prix d'un appel local</p>
					</div> <!-- footer_content_right -->
				</div> <!-- footer-content -->
			</div> <!-- footer -->
		</div><!--Fin Page -->
	</body>		
</html>	
<script type="text/javascript">
$(document).ready(function(){

		// Infobulle sur les liens
		$("a").wTooltip();

         var isLogged = false;
         <?php
            // le namespace est setté en haut de la page
            if(!empty($user->is_logged) && $user->is_logged == true) {?> 
             isLogged = true;
         <?php } ?>
        
       //Récupération des infos et envoie à l'action login du controller utilisateurs.
       $("#submitLogin").click(function(){
           $.ajax({
              type: 'post',
              url: '/utilisateurs/connexionFromIndex',
              data: {'login' : $("#login_top").val(), 'password' : $("#password_top").val(), 'loginFromIndex' : true, 'remember' : $("#remember").val()},
              success : function(data){
                   if(data != ''){
                       $("#userHello").html('Bonjour '+ data + " !");
                       $("#isNotLogged").hide();
                       $("#isLogged").show();
                       location.reload();
                    }else{
                        $("#erreur").html("Votre nom d'utilisateur ou votre mot de passe ne correspond pas !");
                        $("#erreur").show();
                        setTimeout(function() {
                            $( "#erreur" ).fadeOut("slow");
                        }, 2000 );
                    }                
              }
           });
       });
       
       $("#deconnexion").click(function(){
           $.ajax({
               type: 'post',
               url: '/utilisateurs/deconnexion',
               success: function(){
               		location.href = "http://dev.easylia.com";
               }
           }); 
       });
       
       $("#votreCompte").click(function(){
            window.location.replace("/utilisateurs");
       });
                  
       if( isLogged === true){
            $("#isNotLogged").hide();
            $("#isLogged").show();
       }else{
           $("#isNotLogged").show();
           $("#isLogged").hide();
       }

    });
    
	// google analytics
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-23892247-1']);
	_gaq.push(['_setDomainName', '.easylia.com']);
	_gaq.push(['_trackPageview']);
	
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();



</script>

</html>



