
<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Easylia</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/style.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/flexigrid.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/flexigrid.pack.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/fullcalendar.css" rel="stylesheet" type="text/css" />
    <script src="<?php APPLICATION_PATH?>/js/jquery.1.6.2.min.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/cufon-yui.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/cufon-replace.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/Humnst777_BT_700.font.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/Myriad_Pro_400.font.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/flexigrid.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/flexigrid.pack.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/wtootltip.js" type="text/javascript"></script>
    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.slideshow.js"></script>  
    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/script.js"></script>     
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.jcountdown1.3.2.js"></script>	
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/timepicker.js"></script>	
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/fullcalendar.js"></script>  
</head>

<body id="page1">
<div class="right_bgd"></div>
<div class="tail-top">
    <div class="main">
        <div id="header">
        	<a href="#"><img alt="" src="<?php APPLICATION_PATH?>/images/rss.gif" class="rss" /></a>
            <form action="" id="form1">
                <div class="indent"></div>
            </form>
                <div class="indent1">
                	<div class="container">
                    	<ul>
                            <li><a href="http://dev.easylia.com" class="current">Accueil</a></li>
                              <li><a href="/utilisateurs">Profil</a></li>
                        </ul>
                    </div>
                    <a href="http://dev.easylia.com"><img alt="" src="<?php APPLICATION_PATH?>/images/logo.jpg" class="logo" /></a><br />
                </div>
            </div>
<?php
 echo $this->layout()->content; 
 ?>

 <div id="footer">
    	
 </div>
</div>


</body>
<script type="text/javascript">

    $(document).ready(function(){

         var isLogged = false;
         <?php
            // le namespace est setté en haut de la page
            if(!empty($user->is_logged) && $user->is_logged == true) {?> 
             isLogged = true;
         <?php } ?>
        
       //Récupération des infos et envoie à l'action login du controller utilisateurs.
       $("#submitLogin").click(function(){
           $.ajax({
              type: 'post',
              url: '/utilisateurs/connexionFromIndex',
              data: {'login' : $("#login_top").val(), 'password' : $("#password_top").val(), 'loginFromIndex' : true, 'remember' : $("#remember").val()},
              success : function(data){
                   if(data != ''){
                       $("#userHello").html('Bonjour '+ data + " !");
                       $("#isNotLogged").hide();
                       $("#isLogged").show();
                       location.reload();
                    }else{
                        $("#erreur").html("Votre nom d'utilisateur ou votre mot de passe ne correspond pas !");
                        $("#erreur").show();
                        setTimeout(function() {
                            $( "#erreur" ).fadeOut("slow");
                        }, 2000 );
                    }                
              }
           });
       });
       
       $("#deconnexion").click(function(){
           $.ajax({
               type: 'post',
               url: '/utilisateurs/deconnexion',
               success: function(){
               		location.href = "http://dev.easylia.com";
               }
           }); 
       });
       
       $("#votreCompte").click(function(){
            window.location.replace("/utilisateurs");
       });
                  
       if( isLogged === true){
            $("#isNotLogged").hide();
            $("#isLogged").show();
       }else{
           $("#isNotLogged").show();
           $("#isLogged").hide();
       }

    });


</script>
<script type="text/javascript">
	// google analytics
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23892247-1']);
  _gaq.push(['_setDomainName', '.easylia.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>



