
<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Easylia</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/style.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/layout.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/flexigrid.css" rel="stylesheet" type="text/css" />
    <link href="<?php APPLICATION_PATH?>/css/flexigrid.pack.css" rel="stylesheet" type="text/css" />
    <script src="<?php APPLICATION_PATH?>/js/jquery.1.6.2.min.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/cufon-yui.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/cufon-replace.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/Humnst777_BT_700.font.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/Myriad_Pro_400.font.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/flexigrid.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/flexigrid.pack.js" type="text/javascript"></script>
    <script src="<?php APPLICATION_PATH?>/js/wtootltip.js" type="text/javascript"></script>
    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.slideshow.js"></script>  
    <script type="text/javascript" src="<?php APPLICATION_PATH?>/js/script.js"></script>     
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/jquery.jcountdown1.3.2.js"></script>	
	<script type="text/javascript" src="<?php APPLICATION_PATH?>/js/timepicker.js"></script>	
</head>

<body id="page1">
<div class="right_bgd"></div>
<div class="tail-top">
    <div class="main">
        <div id="header">

            <form action="" id="form1">
                <div class="indent">
                    
                  </div>
            </form>
                <div class="indent1">
                	<div class="container">
                    </div>
                    <a href="http://formateurs.easylia.com/inscription"><img alt="" src="<?php APPLICATION_PATH?>/images/logo.jpg" class="logo" id="logo_temp" /></a><br />
                </div>
            </div>

<div id="content">
	<div class="indent-main">
		<div class="container">
			<h2>Confirmation de pré-inscription</h2>
			<p>Votre pré-inscription a été prise en compte.</p><p>Nous reviendrons vers vous dès que les inscriptions seront ouvertes, et vous remercions de l'intérêt que vous portez à Easylia</p>
		</div>
	</div>
</div>


 <div id="footer">
    	
    </div>
 </div>
</div>


</body>
</html>



