<?php
	echo $this->placeholder('menu-connecte');
?>
<h2>Groupe <?php echo $this->nom_groupe ?></h2>
<div id="utilisateurs">
<table id="tableau_utilisateurs">
</table>
</div>
<div id="autorisations">
<table id="tableau_autorisations">
</table>
</div>
<div id="delete_modal" style="display : none;">
    Etes vous sur de vouloir retirer l'utilisateur de ce groupe ? 
</div>
<div id="delete_autorisation_modal" style="display : none">
    Etes vous sûr de vouloir retirer l'autorisation à ce groupe ? 
</div>
<div id="ajout_utilisateur_modal" style="display : none;">
    <p id="nom_groupe"></p><br />
    Veuillez sélectionner le nom de l'utilisateur que vous voulez ajouter : <br />
    <br /><select id="select_ajout_utilisateur_groupe">
    </select>
</div>
<div id="ajout_autorisation_modal" style="display : none;">
    <p id="nom_groupe"></p><br />
    Veuillez sélectionner le nom de l'autorisation que vous voulez ajouter : <br />
    <br /><select id="select_ajout_autorisation_groupe">
    </select>
</div>
<div id="edit_autorisation" style="display : none">
    <label for="droit_accorde">Droit accordé : </label><input type="text" style="width : 20em" id="droit_accorde" />
</div>
<input type="hidden" id="id_groupe" value="<?php echo $this->id_groupe ?>" />
<input type="hidden" id="retirer_utilisateur" value="<?php echo $this->retirer_utilisateur?>" />
<input type="hidden" id="retirer_autorisation" value="<?php echo $this->retirer_autorisation?>" />
<input type="hidden" id="ajouter_utilisateur" value="<?php echo $this->ajouter_utilisateur?>" />
<input type="hidden" id="ajouter_autorisation" value="<?php echo $this->ajouter_autorisation?>" />
<script type="text/javascript">
    $(document).ready(function(){
        // Liste des utilisateurs
        $("#tableau_utilisateurs").flexigrid({
            url : '/groupe/getlisteutilisateurs?id_groupe='+$('#id_groupe').val(),
            dataType: 'json',
            colModel : [
                    {display: 'ID', name : 'id_utilisateur', width : 40, sortable : true, align: 'left'},
                    {display: 'Nom', name : 'nom', width : 150, sortable : true, align: 'left'},
                    {display: 'Prénom', name : 'prenom', width : 150, sortable : true, align: 'left'},
                    {display: 'Nom d\'utilisateur', name :'login', width : 150, sortable : true, align: 'left'},
                    {display: 'Groupe', name :'groupe_name', width : 150, sortable : true, align: 'left'}
            ],
            buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record_user},
                    {separator: true},                    
                    {name: 'Retirer', bclass: 'delete', onpress : delete_record_user}
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom'},
                    {display: 'Prenom', name : 'prenom', isdefault: true},
                    {display: 'Nom d\'utilisateur', name : 'login'},
                    {display: 'Groupe', name :'groupe_name'},                                        
            ],
            sortname: "id_utilisateur",
            sortorder: "asc",
            usepager: true,
            title: "Liste des utilisateurs",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 200,
            singleSelect: true
        });
        $("#utilisateurs .ftitle").append('<span id="info_user" style="color : green"></span>');
        $("#utilisateurs .ftitle").append('<span id="error_user" style="color : red"></span>');
        
        function add_record_user(command, grid){
            // On vérifie si l'utilisateur à le droit
            if($("#ajouter_utilisateur").val() != 'true'){
                 $("#error_user").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#error_user").show();
                 setTimeout(function() {
                     $( "#error_user" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
                         
             var id = $("#id_groupe").val();
                         
             // Récupération de la liste des noms
             $.ajax({
                type : 'post',
                url : '/utilisateurs/getlistenomformate',
                data : {"id_groupe" : id},
                success : function(data){
                    $("#select_ajout_utilisateur_groupe").html(data);
                } 
             });
             
            $("#ajout_utilisateur_modal").dialog({
                title : 'Ajouter un utilisateur à un groupe',
                width : 450,
                height : 300,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                               type : 'post',
                               url : 'ajoututilisateur',
                               data : {'id_groupe' : id, 'id_utilisateur' : $("#select_ajout_utilisateur_groupe").val()},
                               success : function(){
                                     $("#ajout_utilisateur_modal").dialog('close');
                                     $("#tableau_utilisateurs").flexReload();
                                     $("#info_user").html('&nbsp;L\'utilisateur à été ajouté');
                                     $("#info_user").show();
                                     setTimeout(function() {
                                         $( "#info_user" ).fadeOut("slow");
                                     }, 2000 );
                               }
                            });
                           $("#ajout_utilisateur_groupe").dialog('close');
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        function delete_record_user(command, grid){
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error_user").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error_user").show();
                setTimeout(function() {
                    $("#error_user").fadeOut("slow");
                }, 2000 );
                return;
             }
             if ($("#retirer_utilisateur").val() != "true")
             {
                 $("#error_user").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#error_user").show();
                 setTimeout(function() {
                     $("#error_user").fadeOut("slow");
                 }, 2000 );
                 return;
              }
            $("#delete_modal").dialog({
                title : "Retirer un utilisateur",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $('.trSelected',grid).each(function(){
                                var id = this.id.substr(3);
                                $.ajax({
                                    type : 'post',
                                    url : 'removeuserfromgroupe',
                                    data : {'id_utilisateur' : id},
                                    success : function(){
                                        $("#delete_modal").dialog('close');
                                        $("#tableau_utilisateurs").flexReload();
                                        $("#info_user").html('&nbsp;L\'utilisateur à été retiré');
                                        $("#info_user").show();
                                        setTimeout(function() {
                                            $( "#info_user" ).fadeOut("slow");
                                        }, 2000 );
                                    } 
                                });
                            });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        // Liste des autorisations
        $("#tableau_autorisations").flexigrid({
            url : 'getlisteautorisations',
            dataType: 'json',
            colModel : [
                    {display: 'ID', name : 'id_utilisateur', width : 40, sortable : true, align: 'left'},
                    {display: 'Droit', name : 'droit_accorde', width : 300, sortable : true, align: 'left'},
            ],
            buttons : [
                    {name: 'Ajouter', bclass: 'add', onpress : add_record_autorisation},
                    {separator: true},                    
                    {name: 'Retirer', bclass: 'delete', onpress : delete_record_autorisation},
                    {separator: true},
                    {name: 'Editer', bclass: 'edit', onpress: edit_record_autorisation},
            ],
            sortname: "id_autorisation",
            sortorder: "asc",
            usepager: true,
            title: "Liste des autorisations",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 150,
            singleSelect: true
        });
        $("#autorisations .ftitle").append('<span id="info_autorisation" style="color : green"></span>');
        $("#autorisations .ftitle").append('<span id="error_autorisation" style="color : red"></span>');
        
        function add_record_autorisation(command, grid){
            // On vérifie si l'utilisateur à le droit
            if($("#ajouter_autorisation").val() != 'true'){
                 $("#error_autorisation").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                 $("#error_autorisation").show();
                 setTimeout(function() {
                     $( "#error_autorisation" ).fadeOut("slow");
                     }, 2000 );
                return false;
            }
             if($("#id_groupe").val() == 1){
                    $("#error_autorisation").html("&nbsp;Vous ne pouvez pas modifier les autorisations du groupe Administrateur !");
                    $("#error_autorisation").show();
                    setTimeout(function() {
                        $("#error_autorisation").fadeOut("slow");
                    }, 2000 );
                    return;
               }
                         
             var id = $("#id_groupe").val();
                         
             // Récupération de la liste des noms
             $.ajax({
                type : 'post',
                url : 'getlistenomautorisation',
                data : {"id_groupe" : id},
                success : function(data){
                    $("#select_ajout_autorisation_groupe").html(data);
                } 
             });
             
            $("#ajout_autorisation_modal").dialog({
                title : 'Ajouter un utilisateur à un groupe',
                width : 450,
                height : 300,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                               type : 'post',
                               url : 'ajoutautorisation',
                               data : {'id_groupe' : id, 'id_autorisation' : $("#select_ajout_autorisation_groupe").val()},
                               success : function(){
                                     $("#ajout_autorisation_modal").dialog('close');
                                     $("#tableau_autorisations").flexReload();
                                     $("#info_autorisation").html('&nbsp;L\'autorisation à été ajouté');
                                     $("#info_autorisation").show();
                                     setTimeout(function() {
                                         $( "#info_autorisation" ).fadeOut("slow");
                                     }, 2000 );
                               }
                            });
                           $("#ajout_autorisation_groupe").dialog('close');
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        function delete_record_autorisation(command, grid){
            var record_count = $('.trSelected',grid).length;
             if (0 == record_count)
             {
                 $("#error_autorisation").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                 $("#error_autorisation").show();
                 setTimeout(function() {
                     $("#error_autorisation").fadeOut("slow");
                 }, 2000 );
                 return;
              }
              if ($("#retirer_utilisateur").val() != "true")
              {
                  $("#error_autorisation").html('&nbsp;Vous n\'avez pas l\'autorisation d\'effectuer cette action !');
                  $("#error_autorisation").show();
                  setTimeout(function() {
                      $("#info_autorisation").fadeOut("slow");
                  }, 2000 );
                  return;
               }
               if($("#id_groupe").val() == 1){
                    $("#info_autorisation").html("&nbsp;Vous ne pouvez pas modifier les autorisations du groupe Administrateur !");
                    $("#info_autorisation").show();
                    setTimeout(function() {
                        $("#info_autorisation").fadeOut("slow");
                    }, 2000 );
                    return;
               }
             $("#delete_autorisation_modal").dialog({
                 title : "Retirer une autorisation",
                 buttons : [
                     {
                         text : "Valider",
                         click : function(){
                             $('.trSelected',grid).each(function(){
                                 var id = this.id.substr(3);
                                 $.ajax({
                                     type : 'post',
                                     url : 'removeautorisationfromgroupe',
                                     data : {'id_autorisation' : id, "id_groupe" : $('#id_groupe').val()},
                                     success : function(){
                                         $("#delete_autorisation_modal").dialog('close');
                                         $("#tableau_autorisations").flexReload();
                                         $("#info_autorisation").html('&nbsp;L\'autorisation à été retiré');
                                         $("#info_autorisation").show();
                                         setTimeout(function() {
                                             $( "#info" ).fadeOut("slow");
                                         }, 2000 );
                                     } 
                                 });
                             });
                         }
                     },
                     {
                         text : "Annuler",
                         click : function(){
                             $(this).dialog('close');
                         }
                     }
                 ]
             });
        }

        function edit_record_autorisation(command, grid){
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count){
                $("#error_autorisation").html('&nbsp;Veuillez dabord sélectionner une ligne !');
                $("#error_autorisation").show();
                setTimeout(function() {
                $("#error_autorisation").fadeOut("slow");
                }, 2000 );
                return;
            }

             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
                 $("#droit_accorde").val($('td[abbr="droit_accorde"] >div', this).html());
             });  

            $('#edit_autorisation').dialog({
                title : 'Editer une autorisation',
                width : 400,
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : '/groupe/editautorisation',
                                data : {'id' : id, 'droit_accorde' : $('#droit_accorde').val()},
                                success : function(){
                                    $('#edit_autorisation').dialog('close');                                    
                                    $('#tableau_autorisations').flexReload();
                                    $("#info_autorisation").html('&nbsp;L\'autorisation à été modifié');
                                    $("#info_autorisation").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );
                                }
                            });
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
    }); 
</script>