<div id="client_data">
	<h5 style = "border-bottom : 1px solid">Coordonnées du client</h5><br />
<?php
	echo "<p id='nom_prenom'>".$this->nom_prenom."</p><br />";
	echo "<p id='adresse'>".$this->adresse."</p><br />";
	echo "<p id='adresse2'>".$this->adresse2."</p><br />";
	echo "<p id='coordonnees'>".$this->telephone."</p><br />";
?>
</div>
<br />
<div id="rdv_data">
	<h5 style = "border-bottom : 1px solid">Informations sur le rendez-vous</h5><br />
	<p>Date : <?php echo $this->date ?></p><br />
	<p>Durée : <?php echo $this->duree ?></p><br />
	<p>Formation : <?php echo $this->formation ?></p><br />
</div>
