<?php
	echo $this->placeholder('menu-connecte');
?>
<table id="tableau_formation"></table>
<div id="delete_dialog" style="display : none">
	Etes vous sur de vouloir supprimer cette formation ? 
</div>
<div id="add_formateur_self" style="display : none">
	Etes vous sur de vouloir vous positionner sur cette formation ? 
</div>
<div id="add_formateur_admin" style="display : none">
	Choisissez le formateur que vous voulez ajouter : <br /><br />
	<select id="formateur">
	
	</select>
</div>
<input type="hidden" id="sans_formateur" value="<?php echo $this->sans_formateur?>" />
<input type="hidden" id="ajouter_formateur" value="<?php echo $this->ajouter_formateur ?>" />
<input type="hidden" id="modifier_formateur" value="<?php echo $this->modifier_formateur ?>" />
<input type="hidden" id="supprimer_formateur" value="<?php echo $this->supprimer_formateur ?>" />
<input type="hidden" id="ajouter_formation" value="<?php echo $this->ajouter_formation ?>" />
<input type="hidden" id="modifier_formation" value="<?php echo $this->modifier_formation ?>" />
<input type="hidden" id="supprimer_formation" value="<?php echo $this->supprimer_formation ?>" />
<input type="hidden" id="type_certification" />
<?php
	echo $this->input;
?>
<script type="text/javascript" >
	$(document).ready(function(){
		
		var sans_formateur = $("#sans_formateur").val();
			
		if($("#sans_formateur").val() == "")
			sans_formateur = false; 
			
		$("#heure_disponible").buttonset();
	
        $("#tableau_formation").flexigrid({
            url : '/formation/getlisteformation?sansFormateur='+sans_formateur,
            dataType: 'json',
            colModel : [
                    {display: 'Nom', name : 'type', width : 250, sortable : true, align: 'center'},
                    {display: 'Durée (H)', name : 'nombre_heure', width : 50, sortable : true, align: 'center'},
                    {display: 'Client', name :'client', width : 150, sortable : false, align: 'center'},
                    {display: 'Formateur', name :'formateur', width : 150, sortable : false, align: 'center'},                    
                    /* {display: 'Date', name : 'date', width : 150, sortable : true, align: 'center'}, */
                    /* {display: 'Payée', name : 'payee', width : 100, sortable : true, align: 'center'} */
            ],
            buttons : [
                    {name: 'Editer', bclass: 'edit', onpress : edit_record},
                    {separator: true},                    
                    {name: 'Supprimer', bclass: 'delete', onpress : delete_record},
                    {separator: true},
                    {name: 'Se positioner sur la formation', bclass: 'add', onpress: add_formateur},
                    {separator: true},
                    {name : 'Positionner un formateur sur la formation', bclass : 'add', onpress: add_formateur_admin}
            ],
            searchitems : [
                    {display: 'Nom', name : 'nom', isdefault: true},
                    {display: 'Client', name : 'client'},
                    {display: 'Formateur', name : 'formatter'},
                    {display: 'Date', name :'date'}                                        
            ],
            sortname: "id_formation",
            sortorder: "asc",
            usepager: true,
            title: "Liste des formations",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 475,
            singleSelect: true
        });
        $(".ftitle").append('<span id="info" style="color : green"></span>');
        $(".ftitle").append('<span id="error" style="color : red"></span>');
        
        function edit_record(command, grid){
        	$("#error").html('&nbsp;Pas encore implémenté !');
           	$("#error").show();
           	setTimeout(function() {
           		$("#error").fadeOut("slow");
           	}, 2000 );
        }
        
        function delete_record(command, grid){
        	if($("#supprimer_formation").val() != true){
        		$("#error").html('&nbsp;Vous n\'avez pas les droits pour effectuer cette action !');
           		$("#error").show();
          		 	setTimeout(function() {
           			$("#error").fadeOut("slow");
           		}, 2000 );
        	}
        
        	var record_count = $('.trSelected',grid).length;
       	
            if (0 == record_count)
            {
            	$("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
            	$("#error").show();
            	setTimeout(function() {
            		$("#error").fadeOut("slow");
            	}, 2000 );
            	return;
            }
            
          	var id;
        	
        	$('.trSelected', grid).each(function(){
    	 		id = this.id.substr(3);	
        	});
            
            $("#delete_dialog").dialog({
            	title : "Supprimer une formation",
            	buttons : [
            		{
            			text : "Valider",
            			click : function(){
            				$.ajax({
				            	type : "post",
				            	url : "delete",
				            	data : {'id_formation' : id},
				            	success : function(){
				            		$("#tableau_formation").flexReload();
				            		$("#info").html('&nbsp;Formation supprimée !');
				            		$("#info").show();
				            		setTimeout(function() {
				            			$("#info").fadeOut("slow");
				            		}, 2000 );
				            		$("#delete_dialog").dialog("close");
				            	}
				            });	
	
            			}
            		},
            		{
            			text : "Annuler", 
            			click : function(){
            				$(this).dialog("close");
            			}
            		}
            	]
            });
         
        }
        
        function add_formateur(command, grid){
        	
            // Permet à un formateur de s'ajouter sur une formation
        	var record_count = $('.trSelected',grid).length;
       	
            if (0 == record_count)
            {
            	$("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
            	$("#error").show();
            	setTimeout(function() {
            		$("#error").fadeOut("slow");
            	}, 2000 );
            	return;
            }
        
	        var id;
        	
        	$('.trSelected', grid).each(function(){
    	 		id = this.id.substr(3);	
        	});
        	
        	// Vérifie si le formateur possède la certification adaptée
			$.ajax({
        		type : "post",
        		async : false,
        		url : "checkcertification",
        		data : {id_formation : id},
        		success : function(data){
    				$("#type_certification").val(data);
    			}
        	});
					
			if($("#type_certification").val() == 'false'){
            	$("#error").html('&nbsp;Vous n\'avez pas passé la certification adaptée à cette certification');
            	$("#error").show();
            	setTimeout(function() {
            		$("#error").fadeOut("slow");
            	}, 2000 );
            	return;
            }
        	

		
			// Récupère les informations sur la formations et les affiche
			getFormationData(id);
			
        	$("#add_formateur_self").dialog({
        		title : 'Se positionner sur une formation',
        		width : 900,
        		height : 570,
        		buttons : [
        			{
        				text : "Valider", 
        				click : function(){
        					$.ajax({
        						type : "post",
        						url : "addformateurtoformation",
        						data : {"id_formation" : id, "heure" : $("input[type='radio']:checked").val()},
        						success : function(){
        							$("#tableau_formation").flexReload();
				            		$("#info").html('&nbsp;Vous avez été positionné sur la formation !');
				            		$("#info").show();
				            		setTimeout(function() {
				            			$("#info").fadeOut("slow");
				            		}, 2000 );
				            		$("#add_formateur_self").dialog("close");

        						}
        					})
        				}
        			},
        			{
        				text : "Annuler",
        				click : function(){
        					$(this).dialog('close');
        				}
        			}
        		]
        	});
        }
        
        function add_formateur_admin(command, grid){
        	// Permet à un administrateur d'ajouter un formateur à une formation
        	if($("#ajouter_formateur").val() != "true"){
        		$("#error").html('&nbsp;Vous n\'avez pas les droits pour effectuer cette action !');
            	$("#error").show();
            	setTimeout(function() {
            		$("#error").fadeOut("slow");
            	}, 2000 );
            	return;
        	}
        	
        	var record_count = $('.trSelected',grid).length;
       	
            if (0 == record_count)
            {
            	$("#error").html('&nbsp;Veuillez dabord sélectionner une ligne !');
            	$("#error").show();
            	setTimeout(function() {
            		$("#error").fadeOut("slow");
            	}, 2000 );
            	return;
            }
        
	        var id;
        	
        	$('.trSelected', grid).each(function(){
    	 		id = this.id.substr(3);	
        	});
        	
        	$.ajax({
        		type : "post",
        		url : "getlistenomformateur",
        		success : function(data){
        			$("#formateur").html(data);
        		}
        	});
        	       	
        	$("#add_formateur_admin").dialog({
        		title : "Ajouter un formateur à une formation",
        		buttons : [
        			{
        				text : "Valider",
        				click : function(){
        					$.ajax({
	        					type : "post",
	        					url : "addformateurtoformation",
	        					data : {"id_formation" : id, "id_formateur" : $("#formateur").val()},
	        					success : function(){
	        						$("#tableau_formation").flexReload();
					            	$("#info").html('&nbsp;Le formateur a été positionné sur la formation !');
					            	$("#info").show();
					            	setTimeout(function() {
					            		$("#info").fadeOut("slow");
					            	}, 2000 );
					            	$("#add_formateur_admin").dialog("close");
	
	        					}
        					});
        				}	
        			},
        			{
        				text : "Annuler",
        				click : function(){
        					$(this).dialog('close');
        				}
        			}
        		]
        	});    	
        }
        
        function getFormationData(id_formation){
        	// Récupère les informations de la formation et les créneaux disponible
        	$.ajax({
        		type : "post",
        		url : "/formation/getformationdata",
        		data : {id : id_formation},
        		beforeSend : function(){
        			console.log('toto');
        		},
        		success : function(data){
					$("#add_formateur_self").html(data);
        		}
        	});
        }
        
        /*
function checkCertification(id_formation){
        	// Vérifie si le formateur à la certification correspondante à la formation
			var result;
	
        	$.ajax({
        		type : "post",
        		url : "checkcertification",
        		data : {id_formation : id_formation},
        		success : function(data){
					$("#type_certification").val('toto');
			    }
        	});
        	
        }
*/
	
	});
</script>