<?php 
	echo $this->placeholder('menu-connecte');
?>
<h2 class="h5_modifie">Mes formations</h2>
<div id="calendrier">
</div>	
<div id="event_detail" style="display : none"></div>
<script type="text/javascript">
	$(document).ready(function(){
		$('#calendrier').fullCalendar({
			weekends : true,
			weekMode : 'liquid',
			firstDay : 1,
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			buttonText : { today : "Aujourd'hui", month : "mois", agendaWeek : "semaine", agendaDay : "journ&eacute;e"},
			monthNames : ['Janvier','F\u00e9vrier','Mars','Avril','Mai','Juin','Juillet','Ao\u00fbt','Septembre','Octobre','Novembre','D\u00e9cembre'],
			monthNamesShort : ['Jan','Fev','Mar','Avr','Mai','Juin','Juil','Aout','Sep','Oct','Nov','Dec'],
			dayNames : ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
			dayNamesShort : ['Dim','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Sam'],
			events : 'getcalendardata',
			defaultView : 'agendaWeek',
			titleFormat : {
				day: 'dddd d MMMM yyyy' ,
				week : " d [ yyyy]{ '&#8212;' d MMMM yyyy}",
			},
			minTime : '8am',
			maxTime : '8pm',
			allDaySlot : false,
			axisFormat : "HH'h'(mm)",
			timeFormat : "HH'h'mm{- HH'h'mm}",
			columnFormat : {
				week : "dddd dd/M",
				day : "dddd dd/M"
			},
			//theme : true,
			eventClick : function(calEvent, jsEvent, view){
				getEventData(calEvent.id);
			}
		});

		function getEventData(event_id){
			$.ajax({
				type : "post",
				url : 'geteventdata',
				data : {id : event_id},
				success : function(data){
					$("#event_detail").html(data);
					$("#event_detail").dialog({
						title : "Détails du rendez-vous",
						width : 500,
						height : 500,
						buttons : [
							{
								text : "OK",
								click : function(){
									$(this).dialog('close');
								}
							}
						]
					});
				}
			});
		}
	});	
</script>