<?php
	echo $this->placeholder('menu-connecte');
?>
<table id="tableau_reponse">
</table>
<div id="add_form" style="display : none">
    <?php
        echo $this->add_form;
    ?>
</div>
<div id="delete_dialog" style="display : none">
    <p>Etes vous sur de vouloir supprimer cette question ? </p>
</div>
<div id="edit_form" style="display : none">
    <?php
        echo $this->edit_form;
    ?>
</div>
<input type="hidden" id="id_demande" value="<?php echo $this->id_demande?>" />

<script type="text/javascript">
    $(document).ready(function(){
        $("#tableau_reponse").flexigrid({
            url : '/Reponses/getlistereponse?id='+$('#id_demande').val(),
            dataType: 'json',
            colModel : [
                {display: 'Réponse', name : 'reponse', width : 150, sortable : true, align: 'left'},
                {display: 'Réponse juste', name : 'est_juste', width: 150, sortable:true, align :'left'}
            ],
            buttons : [
                {name: 'Ajouter', bclass: 'add', onpress : add_record},
                {separator: true},                    
                {name: 'Editer', bclass: 'edit', onpress : edit_record},
                {separator: true},
                {name: 'Supprimer', bclass: 'delete', onpress : delete_record}
            ],
            searchitems : [
                {display: 'Réponse', name : 'question', isdefault: true}
            ],
            sortname: "id_reponse",
            sortorder: "asc",
            usepager: true,
            title: "Liste des réponses",
            useRp: true,
            rp: 20,
            showTableToggleBtn: false,
            resizable: false,
            height: 480,
            singleSelect: true
        });
        $(".ftitle").append('<span id="error" style="color : red">&nbsp;</span>');
        $(".ftitle").append('<span id="info" style="color : green">&nbsp;</span>');
        
        function add_record(command, grid){
            $("#reponse_add").val('');
            $("#est_juste_add").attr('checked', false);
            $("#add_form").dialog({
                title : "Ajouter une réponses",
                buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            var estJuste = 0;
                            if($("#est_juste_add").attr('checked') == "checked"){
                                estJuste = 1;
                            }
                            $.ajax({
                                type : 'post',
                                url : '/Reponses/ajouterreponse',
                                data : {
                                    'id_question' : $("#id_demande").val(),
                                    'reponse' : $("#reponse_add").val(),
                                    'est_juste' : estJuste
                                },
                                success : function(){
                                    $("#tableau_reponse").flexReload();
                                    $("#add_form").dialog('close');
                                    $("#info").html("Question ajoutée !");
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );                                    
                                }
                            })
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                ]
            });
        }
        
        function edit_record(command, grid){            
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }
             
             var id;
             var is_checked;
             $('.trSelected',grid).each(function(){
                id = this.id.substr(3);
                $("#reponse").val($('td[abbr="reponse"] >div', this).html());
                is_checked = 0;
                if($('td[abbr="est_juste"] >div', this).html() == "oui"){
                    is_checked = 1;}
                    
                if(is_checked == 1){
                    $("#est_juste").attr('checked', true);
                }
             });            
             
             $("#edit_form").dialog({
                 title : "Editer une question",
                 width : 550,
                 buttons : [
                     {
                         text : "Valider",
                         click : function(){
                             var estJuste = 0;
                             if($("#est_juste").attr('checked') == "checked"){
                                 estJuste = 1;
                             }
                             $.ajax({
                                 type : 'post',
                                 url : '/Reponses/editer',
                                 data : {
                                     'id_reponse' : id,
                                     'id_question' : $("#id_demande").val(),
                                     'reponse' : $("#reponse").val(),
                                     'est_juste' : estJuste
                                 },
                                 success : function(){
                                     $("#tableau_reponse").flexReload();
                                     $("#edit_form").dialog('close');
                                     $("#info").html("Question editée !");
                                     $("#info").show();
                                     setTimeout(function() {
                                         $( "#info" ).fadeOut("slow");
                                     }, 2000 );                                    
                                 }
                             })
                         }
                     },
                     {
                         text : "Annuler",
                         click : function(){
                             $(this).dialog('close');
                         }
                     }
                 ]
             });
        }
        
        function delete_record(command, grid){
            var record_count = $('.trSelected',grid).length;
            if (0 == record_count)
            {
                $("#error").html('Veuillez dabord sélectionner une ligne !');
                $("#error").show();
                setTimeout(function() {
                    $("#error").fadeOut("slow");
                }, 2000 );
                return;
             }

             var id;
             $('.trSelected',grid).each(function(){
                 id = this.id.substr(3);
             });
             
             $("#delete_dialog").dialog({
                 title : "Supprimer une question",
                 buttons : [
                    {
                        text : "Valider",
                        click : function(){
                            $.ajax({
                                type : 'post',
                                url : '/Reponses/delete',
                                data : {'id_reponse' : id},
                                success : function(){
                                    $("#tableau_reponse").flexReload();
                                    $("#delete_dialog").dialog('close');
                                    $("#info").html("Question supprimée !");
                                    $("#info").show();
                                    setTimeout(function() {
                                        $( "#info" ).fadeOut("slow");
                                    }, 2000 );
                                }
                            })
                        }
                    },
                    {
                        text : "Annuler",
                        click : function(){
                            $(this).dialog('close');
                        }
                    }
                 ]
             });
        }
    });
</script>