<?php
	echo $this->placeholder('menu-connecte');
?>
<table id="tableau_motivation"></table>
<div id="formulaire_question" style="display : none;">
	<p style="margin-left : 0.7em; margin-bottom : 0.5em"><label class="ajouter_question_label" for="question">Question : </label><textarea id="question" class="question"></textarea></p>
	<p><input type="submit" id="valider_question_reponse" value="Enregistrer" /> <span id="info_enregistrer" style="color : green"></span><span id="erreur_enregistrer" style="color : red"></span></p>
</div> <!-- formulaire_question -->
<div id="supprimer_question" style="display : none">
	<p>Êtes vous sur de vouloir supprimer cette question ? </p>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#tableau_motivation").flexigrid({
	url : '/questions/getquestionmotivation',
	dataType: 'json',
	colModel : [
	        {display: 'Question', name : 'question', width : 1000, sortable : true, align: 'left'},
	],
	buttons : [
		{name: 'Ajouter', bclass: 'add', onpress: add_record},
		{separator: true},
		{name: 'Editer', bclass: 'edit', onpress: edit_record},
		{separator: true},
		{name: 'Supprimer', bclass: 'delete', onpress: delete_record}
	],
	searchitems : [
	        {display: 'Question', name : 'question'}
	],
	sortname: "id_question",
	sortorder: "asc",
	usepager: true,
	title: "Liste des questions de motivation",
	useRp: true,
	rp: 20,
	showTableToggleBtn: false,
	resizable: false,
	height: 500,
	singleSelect: true
	});
	$(".ftitle").append('<span id="info" style="color : green"></span>');
	$(".ftitle").append('<span id="error" style="color : red"></span>');
	
	// Lorsque on enregistre une question
	$("#valider_question_reponse").click(function(){

		// On récupère les valeurs
		var question = $("#question").val();

		// On vérifie que la question a été remplie
		if(question == ""){
			$("#erreur_enregistrer").html("Veuillez remplir la question");
            $("#erreur_enregistrer").show();
                setTimeout(function() {
                    $( "#erreur_enregistrer" ).fadeOut("slow");
                }, 2000 );  
			return;
		}
			
		// On enregistre le tout
		$.ajax({
			type : "post",
			url : "/questions/ajouter",
			data : {question : question, motivation : 1},
			success : function(){
				// On remet le formulaire à zero
				$('#question').val('');	
				
				// On affiche la confirmation
				$("#info_enregistrer").html("Votre question a été enregistrée");
                $("#info_enregistrer").show();
                setTimeout(function() {
                    $( "#info_enregistrer" ).fadeOut("slow");
                }, 2000 );    
			}
		});		
   	});
	
	function add_record(command, grid){
		 // On affiche le bouton enregistrer
		 $('#valider_question_reponse').show();
		 
		 // On vide la question par sécurité
		 $('#question').val('');
	
		$('#formulaire_question').dialog({
			width : 620,
			title : 'Ajouter une question',
			buttons : [
				{
					text : 'Fermer',
					click : function(){
						$(this).dialog('close');
						$('#tableau_motivation').flexReload();
					}
				}
			]
		});
	}
	
	function edit_record(command, grid){
		/*
if($("#editer_question").val() != "true"){
		    $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
		    $("#error").show();
		    setTimeout(function() {
		        $( "#error" ).fadeOut("slow");
		    }, 2000 );
		    return;
		}
*/
		
		var record_count = $('.trSelected',grid).length;
		if (0 == record_count)
		{
		    $("#error").html('Veuillez dabord sélectionner une ligne !');
		    $("#error").show();
		    setTimeout(function() {
		        $("#error").fadeOut("slow");
		    }, 2000 );
		    return;
		 }
		 
		 var id;
         $('.trSelected',grid).each(function(){
             id = this.id.substr(3);
             $("#question").val($('td[abbr="question"] >div', this).html());
         });      
		 
		 // On masque le bouton enregistrer
		 $('#valider_question_reponse').hide();
		 
		 $('#formulaire_question').dialog({
		 	title : 'Modifier une question',
		 	width: 620,
		 	buttons : [
		 		{
		 			text : 'Valider',
		 			click : function(){
		 				$.ajax({
		 					type : 'post',
		 					url : 'editer',
		 					data : {id_question : id, question : $("#question").val(), motivation : 1},
		 					success : function(){
		 						$("#formulaire_question").dialog('close');
		 						$("#tableau_motivation").flexReload();
		 					}
		 				});
		 			}
		 		},
		 		{
		 			text : 'Annuler',
		 			click : function(){
		 				$(this).dialog('close');
		 			}
		 		}
		 	]
		 });	
	}
	
	function delete_record(command, grid){
/*
		if($("#supprimer").val() != "true"){
		    $("#error").html("Vous n'avez pas le droit d'effectuer cette action !");
		    $("#error").show();
		    setTimeout(function() {
		        $( "#error" ).fadeOut("slow");
		    }, 2000 );
		    return;
		}
*/

		
		var record_count = $('.trSelected',grid).length;
		if (0 == record_count)
		{
		    $("#error").html('Veuillez dabord sélectionner une ligne !');
		    $("#error").show();
		    setTimeout(function() {
		        $("#error").fadeOut("slow");
		    }, 2000 );
		    return;
		 }
		 
		 var id;
         $('.trSelected',grid).each(function(){
             id = this.id.substr(3);
         });    
		 
		 $("#supprimer_question").dialog({
		 	title : "Supprimer une question",
		 	buttons: [
		 		{
		 			text : "Valider",
		 			click : function(){
		 				$.ajax({
		 					type : 'post',
		 					url : 'delete',
		 					data : {id_question : id, motivation : 1},
		 					success : function(){
		 						$('#supprimer_question').dialog('close');
		 						$('#tableau_motivation').flexReload();
		 					}
		 				});
		 			}
		 		},
		 		{
		 			text : "Annuler",
		 			click : function(){
		 				$(this).dialog('close');
		 			}
		 		}
		 	]
		 });
	}
});
</script>