
<?php echo $this->doctype();
$user = new Zend_Session_Namespace('user');?>
<h1>Formulaire d'inscription au poste de formateur</h1>
<div class="form-center">
	<p id="inscription_texte">
		Le recrutement des formateurs est ouvert à toute personne majeure (qui a la possibilité de s’immatriculer, pour ensuite facturer les prestations effectuées à Easylia).
	</p>
	<p id="info_inscription"><i>Tous les champs marqués d'une * sont obligatoires.</i></p>
	<form id="inscription_form" enctype="application/x-www-form-urlencoded" method="post" action="/inscription-formateur">
	<dl class="zend_form">
		<div id="form-content">
			<div id="inscription_civilite">
				<h4>Informations personnelles</h4>
			</div>
			<dt id="inscription_type-label"><label for="inscription_type" class="optional"><span class="red">*</span> Civilité :</label></dt>
			<dd id="inscription_type-element">
				<select name="type" id="type">
				    <option value="mr" >M.</option>
				    <option value="mlle">Mlle</option>
				    <option value="mme" >Mme</option>
				</select></dd>
			<dt id="nom-label"><label for="nom" class="optional"><span class="red">*</span> Nom :</label></dt>
			<dd id="nom-element">
				<input type="text" name="nom" id="nom" value="" /></dd>
			<dt id="prenom-label"><label for="prenom" class="optional"><span class="red">*</span> Prénom :</label></dt>
			<dd id="prenom-element">
				<input type="text" name="prenom" id="prenom" value="" /></dd>
			<!--<dt id="siret-label"><label for="siret" class="optional">Siret :</label></dt>
			<dd id="siret-element">
				<input type="text" name="siret" id="siret" value="" /></dd>-->
			<dt id="adresse-label"><label for="adresse" class="optional"><span class="red">*</span> Adresse :</label></dt>
			<dd id="adresse-element">
				<input type="text" name="adresse" id="adresse" value="" /></dd>
			<dt id="adresse2-label"><label for="adresse2" class="optional">Complément d'adresse :</label></dt>
			<dd id="adresse2-element">
				<input type="text" name="adresse2" id="adresse2" value="" /></dd>
			<dt id="codePostal-label"><label for="codePostal" class="optional"><span class="red">*</span> Code postal :</label></dt>
			<dd id="codePostal-element">
				<input type="text" name="codePostal" id="codePostal" value="" /></dd>
			<dt id="ville-label"><label for="ville" class="optional"><span class="red">*</span> Ville <i style="font-size : 10.3px;">(Se remplit automatiquement en fonction du code postal)</i> :</label></dt>
			<dd id="ville-element">
				<input type="text" name="ville" id="ville" value="" /></dd>
			<dt id="telephone-label"><label for="telephone" class="optional"><span class="red">*</span> Téléphone :</label></dt>
			<dd id="telephone-element">
				<input type="text" name="telephone" id="telephone" value="" /></dd>
			<dt id="dateNaissance-label"><label for="dateNaissance" class="optional"><span class="red">*</span> Date de naissance :</label></dt>
			<dd id="dateNaissance-element">
				<input type="text" name="dateNaissance" id="dateNaissance" value="" /><span style="color : orange; margin-left: 4em"><small><i>Vous devez avoir au moins 18 ans pour vous inscrire</i></small></span>
      </dd>
			<dt id="paysNaissance-label"><label for="paysNaissance" class="optional"><span class="red">*</span> Pays de naissance :</label></dt>
			<dd id="paysNaissance-element">
				<select name="paysNaissance" id="paysNaissance" style="width : 12em"> 
                         <option value="France" selected="selected">France </option>
                         <option value="Afghanistan">Afghanistan </option>
                         <option value="Afrique_Centrale">Afrique_Centrale </option>
                         <option value="Afrique_du_sud">Afrique_du_Sud </option> 
                         <option value="Albanie">Albanie </option>
                         <option value="Algerie">Algerie </option>
                         <option value="Allemagne">Allemagne </option>
                         <option value="Andorre">Andorre </option>
                         <option value="Angola">Angola </option>
                         <option value="Anguilla">Anguilla </option>
                         <option value="Arabie_Saoudite">Arabie_Saoudite </option>
                         <option value="Argentine">Argentine </option>
                         <option value="Armenie">Armenie </option> 
                         <option value="Australie">Australie </option>
                         <option value="Autriche">Autriche </option>
                         <option value="Azerbaidjan">Azerbaidjan </option>
                         <option value="Bahamas">Bahamas </option>
                         <option value="Bangladesh">Bangladesh </option>
                         <option value="Barbade">Barbade </option>
                         <option value="Bahrein">Bahrein </option>
                         <option value="Belgique">Belgique </option>
                         <option value="Belize">Belize </option>
                         <option value="Benin">Benin </option>
                         <option value="Bermudes">Bermudes </option>
                         <option value="Bielorussie">Bielorussie </option>
                         <option value="Bolivie">Bolivie </option>
                         <option value="Botswana">Botswana </option>
                         <option value="Bhoutan">Bhoutan </option>
                         <option value="Boznie_Herzegovine">Boznie_Herzegovine </option>
                         <option value="Bresil">Bresil </option>
                         <option value="Brunei">Brunei </option>
                         <option value="Bulgarie">Bulgarie </option>
                         <option value="Burkina_Faso">Burkina_Faso </option>
                         <option value="Burundi">Burundi </option>
                         <option value="Caiman">Caiman </option>
                         <option value="Cambodge">Cambodge </option>
                         <option value="Cameroun">Cameroun </option>
                         <option value="Canada">Canada </option>
                         <option value="Canaries">Canaries </option>
                         <option value="Cap_vert">Cap_Vert </option>
                         <option value="Chili">Chili </option>
                         <option value="Chine">Chine </option> 
                         <option value="Chypre">Chypre </option> 
                         <option value="Colombie">Colombie </option>
                         <option value="Comores">Colombie </option>
                         <option value="Congo">Congo </option>
                         <option value="Congo_democratique">Congo_democratique </option>
                         <option value="Cook">Cook </option>
                         <option value="Coree_du_Nord">Coree_du_Nord </option>
                         <option value="Coree_du_Sud">Coree_du_Sud </option>
                         <option value="Costa_Rica">Costa_Rica </option>
                         <option value="Cote_d_Ivoire">Côte_d_Ivoire </option>
                         <option value="Croatie">Croatie </option>
                         <option value="Cuba">Cuba </option>
                         <option value="Danemark">Danemark </option>
                         <option value="Djibouti">Djibouti </option>
                         <option value="Dominique">Dominique </option>
                         <option value="Egypte">Egypte </option> 
                         <option value="Emirats_Arabes_Unis">Emirats_Arabes_Unis </option>
                         <option value="Equateur">Equateur </option>
                         <option value="Erythree">Erythree </option>
                         <option value="Espagne">Espagne </option>
                         <option value="Estonie">Estonie </option>
                         <option value="Etats_Unis">Etats_Unis </option>
                         <option value="Ethiopie">Ethiopie </option>
                         <option value="Falkland">Falkland </option>
                         <option value="Feroe">Feroe </option>
                         <option value="Fidji">Fidji </option>
                         <option value="Finlande">Finlande </option>
                         <option value="France">France </option>
                         <option value="Gabon">Gabon </option>
                         <option value="Gambie">Gambie </option>
                         <option value="Georgie">Georgie </option>
                         <option value="Ghana">Ghana </option>
                         <option value="Gibraltar">Gibraltar </option>
                         <option value="Grece">Grece </option>
                         <option value="Grenade">Grenade </option>
                         <option value="Groenland">Groenland </option>
                         <option value="Guadeloupe">Guadeloupe </option>
                         <option value="Guam">Guam </option>
                         <option value="Guatemala">Guatemala</option>
                         <option value="Guernesey">Guernesey </option>
                         <option value="Guinee">Guinee </option>
                         <option value="Guinee_Bissau">Guinee_Bissau </option>
                         <option value="Guinee equatoriale">Guinee_Equatoriale </option>
                         <option value="Guyana">Guyana </option>
                         <option value="Guyane_Francaise ">Guyane_Francaise </option>
                         <option value="Haiti">Haiti </option>
                         <option value="Hawaii">Hawaii </option> 
                         <option value="Honduras">Honduras </option>
                         <option value="Hong_Kong">Hong_Kong </option>
                         <option value="Hongrie">Hongrie </option>
                         <option value="Inde">Inde </option>
                         <option value="Indonesie">Indonesie </option>
                         <option value="Iran">Iran </option>
                         <option value="Iraq">Iraq </option>
                         <option value="Irlande">Irlande </option>
                         <option value="Islande">Islande </option>
                         <option value="Israel">Israel </option>
                         <option value="Italie">italie </option>
                         <option value="Jamaique">Jamaique </option>
                         <option value="Jan Mayen">Jan Mayen </option>
                         <option value="Japon">Japon </option>
                         <option value="Jersey">Jersey </option>
                         <option value="Jordanie">Jordanie </option>
                         <option value="Kazakhstan">Kazakhstan </option>
                         <option value="Kenya">Kenya </option>
                         <option value="Kirghizstan">Kirghizistan </option>
                         <option value="Kiribati">Kiribati </option>
                         <option value="Koweit">Koweit </option>
                         <option value="Laos">Laos </option>
                         <option value="Lesotho">Lesotho </option>
                         <option value="Lettonie">Lettonie </option>
                         <option value="Liban">Liban </option>
                         <option value="Liberia">Liberia </option>
                         <option value="Liechtenstein">Liechtenstein </option>
                         <option value="Lituanie">Lituanie </option> 
                         <option value="Luxembourg">Luxembourg </option>
                         <option value="Lybie">Lybie </option>
                         <option value="Macao">Macao </option>
                         <option value="Macedoine">Macedoine </option>
                         <option value="Madagascar">Madagascar </option>
                         <option value="Madère">Madère </option>
                         <option value="Malaisie">Malaisie </option>
                         <option value="Malawi">Malawi </option>
                         <option value="Maldives">Maldives </option>
                         <option value="Mali">Mali </option>
                         <option value="Malte">Malte </option>
                         <option value="Man">Man </option>
                         <option value="Mariannes du Nord">Mariannes du Nord </option>
                         <option value="Maroc">Maroc </option>
                         <option value="Marshall">Marshall </option>
                         <option value="Martinique">Martinique </option>
                         <option value="Maurice">Maurice </option>
                         <option value="Mauritanie">Mauritanie </option>
                         <option value="Mayotte">Mayotte </option>
                         <option value="Mexique">Mexique </option>
                         <option value="Micronesie">Micronesie </option>
                         <option value="Midway">Midway </option>
                         <option value="Moldavie">Moldavie </option>
                         <option value="Monaco">Monaco </option>
                         <option value="Mongolie">Mongolie </option>
                         <option value="Montserrat">Montserrat </option>
                         <option value="Mozambique">Mozambique </option>
                         <option value="Namibie">Namibie </option>
                         <option value="Nauru">Nauru </option>
                         <option value="Nepal">Nepal </option>
                         <option value="Nicaragua">Nicaragua </option>
                         <option value="Niger">Niger </option>
                         <option value="Nigeria">Nigeria </option>
                         <option value="Niue">Niue </option>
                         <option value="Norfolk">Norfolk </option>
                         <option value="Norvege">Norvege </option>
                         <option value="Nouvelle_Caledonie">Nouvelle_Caledonie </option>
                         <option value="Nouvelle_Zelande">Nouvelle_Zelande </option>
                         <option value="Oman">Oman </option>
                         <option value="Ouganda">Ouganda </option>
                         <option value="Ouzbekistan">Ouzbekistan </option>
                         <option value="Pakistan">Pakistan </option>
                         <option value="Palau">Palau </option>
                         <option value="Palestine">Palestine </option>
                         <option value="Panama">Panama </option>
                         <option value="Papouasie_Nouvelle_Guinee">Papouasie_Nouvelle_Guinee </option>
                         <option value="Paraguay">Paraguay </option>
                         <option value="Pays_Bas">Pays_Bas </option>
                         <option value="Perou">Perou </option>
                         <option value="Philippines">Philippines </option> 
                         <option value="Pologne">Pologne </option>
                         <option value="Polynesie">Polynesie </option>
                         <option value="Porto_Rico">Porto_Rico </option>
                         <option value="Portugal">Portugal </option>
                         <option value="Qatar">Qatar </option>
                         <option value="Republique_Dominicaine">Republique_Dominicaine </option>
                         <option value="Republique_Tcheque">Republique_Tcheque </option>
                         <option value="Reunion">Reunion </option>
                         <option value="Roumanie">Roumanie </option>
                         <option value="Royaume_Uni">Royaume_Uni </option>
                         <option value="Russie">Russie </option>
                         <option value="Rwanda">Rwanda </option>
                         <option value="Sahara Occidental">Sahara Occidental </option>
                         <option value="Sainte_Lucie">Sainte_Lucie </option>
                         <option value="Saint_Marin">Saint_Marin </option>
                         <option value="Salomon">Salomon </option>
                         <option value="Salvador">Salvador </option>
                         <option value="Samoa_Occidentales">Samoa_Occidentales</option>
                         <option value="Samoa_Americaine">Samoa_Americaine </option>
                         <option value="Sao_Tome_et_Principe">Sao_Tome_et_Principe </option> 
                         <option value="Senegal">Senegal </option> 
                         <option value="Seychelles">Seychelles </option>
                         <option value="Sierra Leone">Sierra Leone </option>
                         <option value="Singapour">Singapour </option>
                         <option value="Slovaquie">Slovaquie </option>
                         <option value="Slovenie">Slovenie</option>
                         <option value="Somalie">Somalie </option>
                         <option value="Soudan">Soudan </option> 
                         <option value="Sri_Lanka">Sri_Lanka </option> 
                         <option value="Suede">Suede </option>
                         <option value="Suisse">Suisse </option>
                         <option value="Surinam">Surinam </option>
                         <option value="Swaziland">Swaziland </option>
                         <option value="Syrie">Syrie </option>
                         <option value="Tadjikistan">Tadjikistan </option>
                         <option value="Taiwan">Taiwan </option>
                         <option value="Tonga">Tonga </option>
                         <option value="Tanzanie">Tanzanie </option>
                         <option value="Tchad">Tchad </option>
                         <option value="Thailande">Thailande </option>
                         <option value="Tibet">Tibet </option>
                         <option value="Timor_Oriental">Timor_Oriental </option>
                         <option value="Togo">Togo </option> 
                         <option value="Trinite_et_Tobago">Trinite_et_Tobago </option>
                         <option value="Tristan da cunha">Tristan de cuncha </option>
                         <option value="Tunisie">Tunisie </option>
                         <option value="Turkmenistan">Turmenistan </option> 
                         <option value="Turquie">Turquie </option>
                         <option value="Ukraine">Ukraine </option>
                         <option value="Uruguay">Uruguay </option>
                         <option value="Vanuatu">Vanuatu </option>
                         <option value="Vatican">Vatican </option>
                         <option value="Venezuela">Venezuela </option>
                         <option value="Vierges_Americaines">Vierges_Americaines </option>
                         <option value="Vierges_Britanniques">Vierges_Britanniques </option>
                         <option value="Vietnam">Vietnam </option>
                         <option value="Wake">Wake </option>
                         <option value="Wallis et Futuma">Wallis et Futuma </option>
                         <option value="Yemen">Yemen </option>
                         <option value="Yougoslavie">Yougoslavie </option>
                         <option value="Zambie">Zambie </option>
                         <option value="Zimbabwe">Zimbabwe </option>
                    </select>
               </dd>
      <dt id="departementNaissance-label" ><label for="departementNaissance" class="optional"><span class="red">*</span> Département de naissance :</label></dt>
      <dd id="departementNaissance-element" >
        <input type="text" name="departementNaissance" id="departementNaissance" value="" /></dd>
     <div id="info_inscription_span">
          <p class='errors_inscription'><span id='info_nom'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_prenom'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_adresse'>&nbsp;</span></p>
          <p class='errors_inscription' style="margin-top: 1em;"><span id='info_codePostal'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_ville'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_telephone'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_dateNaissance'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_paysNaissance'>&nbsp;</span></p>
          <p class='errors_inscription' style="margin-top: 1em;"><span id='info_departementNaissance'>&nbsp;</span></p>
          <p class='errors_inscription' style="margin-top: 7em;"><span id='info_login'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_password'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_password_conf'>&nbsp;</span></p>
          <p class='errors_inscription'><span id='info_email'>&nbsp;</span></p>
          <p class='errors_inscription' style='margin-top: 0.5em;margin-left: -10em;'><span id='info_submit'>&nbsp;</span></p>
     </div> <!-- info_inscription -->

			<div id="inscription_login">
				<h4>Informations de connexion</h4>
			</div>
			<dt id="login-label"><label for="login" class="optional"><span class="red">*</span> Nom d'utilisateur :</label></dt>
			<dd id="login-element">
				<input type="text" name="login" id="login" value="" /></dd>
			<dt id="password-label"><label for="password" class="optional"><span class="red">*</span> Mot de passe<i> (8 caratères, 1 majuscule, 1 chiffre)</i> :</label></dt>
			<dd id="password-element">
				<input type="password" name="password" id="password" value="" /></dd>
			<dt id="password_conf-label"><label for="password_conf" class="optional"><span class="red">*</span> Confirmez le mot de passe :</label></dt>
			<dd id="password_conf-element">
				<input type="password" name="password_conf" id="password_conf" value="" /></dd>
			<dt id="mail-label"><label for="mail" class="optional"><span class="red">*</span> Adresse E-mail :</label></dt>
			<dd id="mail-element">
				<input type="text" name="mail" id="mail" value="" /></dd>
			<dt id="submit-label">&#160;</dt><dd id="submit-element">
				<input type="submit" name="submit" id="submit_inscription" value="Valider" /></dd>
			<dt id="csrf-label">&#160;</dt>
			<dd id="csrf-element">
				<input type="hidden" name="csrf" value="aba16d4f1bf0547303d91b4a02ceb80a" id="csrf" />
			</dd>
		</div> <!-- form-content -->
	</dl>
	</form>	
	<br />
	<div id="information_inscriptions">
		<p>
		<small>
			Les informations que vous nous communiquez ne sont jamais confiées à des tiers. En application de la loi n° 2004-801 du 6 août 2004 relative à la protection des personnes physiques à l'égard des traitements de données à caractère personnel, modifiant la loi n° 78-17 du 6 janvier 1978, vous disposez par ailleurs d'un droit d'accès, de rectification, de modification et de suppression concernant les données qui vous concernent. Vous pouvez exercer ce droit en envoyant un e-mail à contact@easylia.com.
		</small>
		</p>
	</div>
</div> <!-- form-center -->
<script type="text/javascript">

    $(document).ready(function(){
		var cache = {};
                         
        // Ajout des champs pour le design
        $("dd").addClass("inscription-right"); 
        $("dt").addClass("inscription-left");
        $("#login-label > label").attr("id","inscription-login");
        $("#password-label > label").attr("id","inscription-password");
        $("#nom-label > label").attr('id', 'inscription_nom');
        $("#prenom-label > label").attr('id', 'inscription_prenom');
        $("#adresse-label > label").attr('id', 'inscription_adresse');
        $("#adresse2-label > label").attr('id', 'inscription_adresse2');
        $("#codePostal-label > label").attr('id', 'inscription_codePostal');
        $("#ville-label > label").attr('id', 'inscription_ville');
        $("#telephone-label > label").attr('id', 'inscription_telephone');
        $("#mail-label > label").attr('id', 'inscription_mail');
                          
        // Date picker sur le champ dateNaissance

        var date = new Date();
        var annee = date.getFullYear() - 18;

        $("#dateNaissance").datepicker({
          changeYear : true, 
          autoSize : true,
          defaultDate: null,
          dateFormat : 'dd/mm/yy', 
          changeMonth : true, 
          yearRange : '-80 : -18',
          maxDate : -6570,
          onClose : function(){ 
            $("#dateNaissance").focus() 
          }
        });      
               
               
        // Autocomplétion de la ville et du code postal
       
        $("#codePostal, #ville").autocomplete({
            source: function(request, response){
               var objData = {};
               if($(this.element).attr('id') == 'codePostal'){
                   objData = {codePostal : request.term, pays : 'FR', maxRows : 10};
               }else{
                   objData = {ville : request.term, pays : 'FR', maxRows : 10};
               }
           
               $.ajax({
                  url : "/Autocomplete/index",
                  dataType : "json",
                  data : objData,
                  type : 'POST',
                  success : function(data){
                      // Ajout de reponse dans le cache
					   cache[('FR' + '-' + request.term)] = data;
                      response($.map(data, function (item){
                          return{
                              label : item.code_postal + ", " + item.ville,
                              value: function (){
									if ($(this).attr('id') == 'codePostal'){
										$('#ville').val(item.ville);
										//$('#ville').attr('disabled', 'disabled');
										return item.code_postal;
									}
									else{
										$('#codePostal').val(item.code_postal);
										$('#codePostal').attr('disabled', true);
										return item.ville;
									}
								}
                          }
                      }));
                  }
               });            
            },
            minLength : 2,
            delay : 0
        });
        
        // Variables pour la validation du submit
        var nom_check = false;
        var prenom_check = false;
        var adresse_check = false;
        var code_postal_check = false;
        var telephone_check = false;
        var date_naissance_check = false;
        var pays_naissance_check = false;
        var login_check = false;
        var password_check = false;
        var password_conf_check = false;
        var mail_check = false;
        var departement_naissance_check = false;
        var array_check = [];

        // Vérification de okForSubmit et envoie du form si ok
        $("#submit_inscription").click(function(event){

          $('#submit_inscription').focus();

          if(array_check.length > 0)
               array_check = [];

          // On rapelle toutes les vérifications au cas ou
          telephone_check = telephoneCheck($('#telephone').val());
          password_check = passwordCheck($('#password').val());
          password_conf_check = passwordconfCheck($('#password').val(), $('#password_conf').val());
          date_naissance_check = datenaissanceCheck($('#dateNaissance').val());
          nom_check = nomCheck($('#nom').val());
          prenom_check = prenomCheck($('#prenom').val());
          adresse_check = adresseCheck($('#adresse').val());
          code_postal_check = codepostalCheck($('#codePostal').val());
          login_check = loginCheck($('#login').val());
          mail_check = mailCheck($('#mail').val());

          if(!$('#departementNaissance').is(':visible'))
               departement_naissance_check = true;
          else
               departement_naissance_check = departementnaissanceCheck($('#departementNaissance').val());

          array_check.push(nom_check);
          array_check.push(prenom_check);
          array_check.push(adresse_check);  
          array_check.push(code_postal_check);
          array_check.push(telephone_check);
          array_check.push(date_naissance_check);
          array_check.push(departement_naissance_check);
          array_check.push(login_check);
          array_check.push(password_check);
          array_check.push(password_conf_check);
          array_check.push(mail_check);
          
            if(jQuery.inArray(false, array_check) == -1){
               $("#inscription_form").submit();
            }else{
              $("#info_submit").html("Veuillez remplir tous les champs requis avant de valider");
              $("#info_submit").show();
              setTimeout(function() {
                  $( "#info_submit" ).fadeOut("slow");
              }, 2000 );
              return false;
            }
        });
        
        // Vérification de l'existance du login
        $("#login").blur(function(){
            login_check = loginCheck($('#login').val());
        });
        
        // Vérification du champs téléphone
        $("#telephone").blur(function(){
            telephone_check = telephoneCheck($('#telephone').val());
        });
        
        // Vérification de la validité et de la non-existance de l'adresse mail
        $("#mail").blur(function(){
            mail_check = mailCheck($('#mail').val());
        });

        // Vérification de la longueur du password
        $("#password").blur(function(){
          password_check = passwordCheck($('#password').val());
        });
        
        $("#password_conf").blur(function(){
          password_conf_check = passwordconfCheck($('#password').val(), $('#password_conf').val());
        });
        
        // Vérification du format de la date
        $("#dateNaissance").blur(function(){
           date_naissance_check = datenaissanceCheck($('#dateNaissance').val());
        });
        
        // Vérification du remplissage de tout les champs
        
        $("#nom").blur(function(){
         nom_check = nomCheck($('#nom').val());
        });
        
        $("#prenom").blur(function(){
          prenom_check = prenomCheck($('#prenom').val());
        });
        
        $("#adresse").blur(function(){
          adresse_check = adresseCheck($('#adresse').val());
        });
        
        $("#codePostal").blur(function(){
          code_postal_check = codepostalCheck($('#codePostal').val());
        });
        
        // $("#ville").blur(function(){
        //     if($('#ville').val().length > 0){
        //         $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_ok.png' height='20px' width='20px' alt='valide' />"); 
        //     }else
        //         $("#info_ville").html("<img src='<?php APPLICATION_PATH?>/images/icone_erreur.png' height='20px' width='20px' alt='erreur' />&nbsp; Veuillez saisir votre ville ");
        // });
            
        $("#departementNaissance").blur(function(){
           departement_naissance_check = departementnaissanceCheck($('#departementNaissance').val());
        });
        
        $("#paysNaissance").change(function(){
          paysnaissanceCheck($('#paysNaissance').val());
        });
        
    });


</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23892247-1']);
  _gaq.push(['_setDomainName', '.easylia.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>



